### ISSUE TITLE
Consider reducing the default Pool size for Cluster/Sentinel

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#102]
The [DefaultClientFunc](https://godoc.org/github.com/mediocregopher/radix#DefaultClientFunc), which is (surprise) the default function for instantiating new clients for both Redis Cluster and Sentinel clients, currently always creates a pool with 20 connections. 

Having 20 connections per pool can easily waste resources both on the clients and the server, especially since there are always multiple pools for both Redis Cluster and Sentinel. In case of a small Redis Cluster with 6 nodes (3 masters, 3 replicas) the current default will create 120 connections, most of which are probably never be used (e.g. replica connections are rarely used).

And this is only for a single instance of a Go application. Many users will have multiple instances (e.g. for scaling or availability), which will multiply the number of connections needed.

Before automatic pipelining was introduced, each command on a pool required using a dedicated connection which meant that having multiple connections was the only way to scale, but since we now have automatic pipelining (which is on by default), we should consider reducing the number of connections for the pools returned by `DefaultClientFunc`.

We could also consider setting a default overflow size (see [PoolOnFullBuffer](https://godoc.org/github.com/mediocregopher/radix#PoolOnFullBuffer)), for users that benefit from more connections, although that is probably a rare case and could be left to the users as it is right now.

Although I think that users should always create a custom `ClientFunc` for production use, having a good default also seems important to me.

**Comment by mediocregopher** [comment]
I agree lowering the number of default connections would be a good idea, like you say 20 is high when pipelining is enabled by default anyway.

I'm a bit confused by this:
> We could also consider setting a default overflow size (see PoolOnFullBuffer), for users that benefit from more connections.

If you mean that PoolOnFullBuffer should be used by default, it already is. By default it gets set to:
```
PoolOnFullBuffer((size / 3)+1, 1 * time.Second)
```

**Comment by nussjustin** [comment]
> If you mean that PoolOnFullBuffer should be used by default, it already is. By default it gets set to:

Yeah, forgot about that having a default value. 

I see that you reduced the size to 4 in e628410 already, which seems ok to me.

**Comment by mediocregopher** [comment]
Cool, gonna go ahead and close this then. Thanks!
