### ISSUE TITLE
Add support for TLS connections

### ISSUE THREAD

**Issue by Resonance1584** [mediocregopher/radix#103]
We are using AWS Elasticache for Redis which adds an optional TLS layer to the connection. https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html

This feature is required in order to use AUTH with Elasticache.

It is a relatively minor change to add a TLS Dial option to radix, but I do understand if you'd rather keep this library simpler.

**Comment by mediocregopher** [comment]
Merged, thanks for the PR! :)
