### ISSUE TITLE
CLIENT REPLY OFF support?

### ISSUE THREAD

**Issue by maciej** [mediocregopher/radix#106]
Redis supports turning off server replies (with a confusingly named function `CLIENT REPLY OFF`). This feature is useful for mass data loads.

https://redis.io/commands/client-reply

Is there a way of having radix work in this mode?

The naive code below wait for a reply even though none is to be expected:

```go
func noReplyRadix() {
	netConn, err := net.Dial("tcp", redisAddr)
	if err != nil {
		log.Fatal(err)
	}
	defer netConn.Close()
	redisConn := radix.NewConn(netConn)

	err = redisConn.Do(radix.Cmd(nil, "CLIENT", "REPLY", "OFF"))
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Got here!") // never gets here
}
```

**Comment by nussjustin** [comment]
You can implement a custom `CmdAction` that does not unmarshal the result:

```go
type noReplyCmdAction struct {
    radix.CmdAction
}

func (n noReplyCmdAction) Run(conn radix.Conn) error { return conn.Encode(n) }
```

Normally a implementation of `Run` would call `conn.Decode(n)` if there was no error, but since we don't have anything to decode, we can just return with decoding anything.

With this you can wrap your `radix.Cmd(...)` call in a `noReplyCmdAction` like

```go
    err = redisConn.Do(noReplyCmdAction{radix.Cmd(nil, "CLIENT", "REPLY", "OFF")})
    if err != nil {
        log.Fatal(err)
    }   
    fmt.Println("Got here!") // never gets here
```

This works for me.

My full code:

```go
package main

import (
	"fmt"
	"log"
	"net"

	radix "github.com/mediocregopher/radix/v3"
)

type noReplyCmdAction struct {
	radix.CmdAction
}

func (n noReplyCmdAction) Run(conn radix.Conn) error { return conn.Encode(n) }

var redisAddr = "127.0.0.1:6379"

func noReplyRadix() {
	netConn, err := net.Dial("tcp", redisAddr)
	if err != nil {
		log.Fatal(err)
	}
	defer netConn.Close()
	redisConn := radix.NewConn(netConn)

	err = redisConn.Do(noReplyCmdAction{radix.Cmd(nil, "CLIENT", "REPLY", "OFF")})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("Got here!") // never gets here
}

func main() {
	noReplyRadix()
}
```

**Comment by mediocregopher** [comment]
@maciej, just wanted to make sure you saw that there's a `radix.Dial` function, you don't have to create a `net.Conn` manually unless you want to.

**Comment by maciej** [comment]
@mediocregopher thank you for pointing out `radix.Dial`! I haven't seen it as I took a quick look at the API!

@nussjustin unfortunately I found this solution to not acceptable performance-wise.
Let me explain why:

1) `(*connWrap) Encode(m resp.Marshaler) error` flushes the write buffer resulting in a socket write:
```go
func (cw *connWrap) Encode(m resp.Marshaler) error {
	if err := m.MarshalRESP(cw.brw); err != nil {
		return err
	}
	return cw.brw.Flush()
}
```
which is slow

2) much less importantly `radix.Cmd` is not returned to an internal `sync.Pool` resulting in an unnecessary allocation. It's only returned on the decode path:
```go
func (c *cmdAction) UnmarshalRESP(br *bufio.Reader) error {
	if err := (resp2.Any{I: c.rcv}).UnmarshalRESP(br); err != nil {
		return err
	}
	cmdActionPool.Put(c)
	return nil
}
```

There are workarounds, however arguably ugly:
1) implement `radix.Conn` that does not `Flush()` in `Encode()`
2) implement `resp.Unmarshaller` that does nothing in `UnmarshalRESP` and call `cmd.UnmarshalRESP(nil)`

I wrote some benchmarks measuring the time it takes to call a "SET foo bar" command in Redis

* BenchmarkSingleSet - the vanilla version, waiting for a server server replies
* BenchmarkSingleSetWithNoReply - no replies, still flushes after each write
* BenchmarkSingleSetWithNoReplyManualFlush - utilises the workarounds mentioned above
* BenchmarkSingleSetManual - baseline for writing as fast as possible directly to a buffered net.Conn

```
benchmark                                               iter        time/iter   bytes alloc        allocs
---------                                               ----        ---------   -----------        ------
BenchmarkSingleSet-8                                   30000   41519.00 ns/op       32 B/op   1 allocs/op
BenchmarkSingleSetWithNoReply-8                       200000    7561.00 ns/op       32 B/op   1 allocs/op
BenchmarkSingleSetWithNoReplyManualFlush-8           1000000    1001.00 ns/op       32 B/op   1 allocs/op
BenchmarkSingleSetWithNoReplyManualFlushNoDecode-8   1000000    1021.00 ns/op      144 B/op   2 allocs/op
BenchmarkSingleSetManual-8                           2000000     997.00 ns/op        0 B/op   0 allocs/op
```

code: https://gist.github.com/maciej/f2f3145f4b0ad8bd66380446fe622c0b

**Comment by mediocregopher** [comment]
@maciej I'm afraid your requirements are reaching the limits of what radix would want to provide in its API. Which is not to say you can't do it with radix, but if we were to provide for every possible use-case in the most efficient way then the API would be enormous. But you can do what you want if you implement `radix.Action` and `radix.Conn` yourself, as I've done here:

```go
package main

import (
	"bufio"
	"io"
	"net"

	"github.com/mediocregopher/radix/v3"
	"github.com/mediocregopher/radix/v3/resp"
	"github.com/mediocregopher/radix/v3/resp/resp2"
)

type noResponseCmd []string

func (nrCmd noResponseCmd) MarshalRESP(w io.Writer) error {
	var err error
	marshalBulkString := func(str string) {
		if err != nil {
			return
		}
		err = resp2.BulkString{S: str}.MarshalRESP(w)
	}

	err = resp2.ArrayHeader{N: len(nrCmd)}.MarshalRESP(w)
	for i := range nrCmd {
		marshalBulkString(nrCmd[i])
	}
	return err
}

func (nrCmd noResponseCmd) Run(conn radix.Conn) error {
	return conn.Encode(nrCmd)
}

// TODO if this is intended to work with Cluster this will need to be properly
// implemented.
func (nrCmd noResponseCmd) Keys() []string {
	return nil
}

////////////////////////////////////////////////////////////////////////////////

type bulkConn struct {
	net.Conn
	brw *bufio.ReadWriter
}

func newBulkConn(conn net.Conn) *bulkConn {
	return &bulkConn{
		Conn: conn,
		brw:  bufio.NewReadWriter(bufio.NewReader(conn), bufio.NewWriter(conn)),
	}
}

func (bc *bulkConn) Do(a radix.Action) error {
	return a.Run(bc)
}

func (bc *bulkConn) Encode(m resp.Marshaler) error {
	return m.MarshalRESP(bc.brw)
}

func (bc *bulkConn) Flush() error {
	return bc.brw.Writer.Flush()
}

func (bc *bulkConn) Decode(u resp.Unmarshaler) error {
	return u.UnmarshalRESP(bc.brw.Reader)
}

func (bc *bulkConn) NetConn() net.Conn {
	return bc.Conn
}

////////////////////////////////////////////////////////////////////////////////

func main() {
	netConn, err := net.Dial("tcp", "127.0.0.1:6379")
	if err != nil {
		panic(err)
	}

	conn := newBulkConn(netConn)

	nrCmd := noResponseCmd{"CLIENT", "REPLY", "OFF"}
	if err := conn.Do(nrCmd); err != nil {
		panic(err)
	}

	for k, v := range map[string]string{"foo": "bar", "baz": "buz"} {
		nrCmd = append(nrCmd[:0], "SET", k, v)
		if err := conn.Do(nrCmd); err != nil {
			panic(err)
		}
	}

	if err := conn.Flush(); err != nil {
		panic(err)
	}
}
```

(This isn't much different than your `BenchmarkSingleSetManual`, but it's using the `resp2` package to make it a bit more usable.)

This could be done with less code by calling `noResponseCmd.MarshalRESP` directly with a `*bufio.Reader` which is wrapping a `net.Conn`, but this way will give you more wiggle room later. I would note that `bulkConn` should not be used as the `radix.Conn` in any pool, since `Flush` needs to be called manually and pool won't do that.

**Comment by maciej** [comment]
@mediocregopher I understand. I'll close the ticket.

Thank you for providing the `bulkConn` implementation. The code is cleaner compared to what I wrote.
