### ISSUE TITLE
passing AUTH password via URI ONLY in NewSentinel makes PersistentPubSub blocks 

### ISSUE THREAD

**Issue by yushizhao** [mediocregopher/radix#112]
I assume PersistentPubSub only get password from DialAuthPass. 
If we do "redis://:fancyPassword@127.0.0.1:26379", PersistentPubSub will not use the fancyPassword to sub "switch-master".

**Comment by mediocregopher** [comment]
Hi @yushizhao, thanks for using radix :) PersistentPubSub uses [DefaultConnFunc](https://github.com/mediocregopher/radix/blob/master/radix.go#L244) if a `ConnFunc` is not passed into the `PersistentPubSub` function. `DefaultConnFunc` is simply a wrapper around `Dial`, which does do the `redis://` schema handling, including auth. Can you post an example of how you're using PersistentPubSub which is showing this problem?

**Comment by yushizhao** [comment]
okay,
this works:
package main

import (
	"fmt"

	"github.com/mediocregopher/radix"
)

func main() {
	address := []string{
		"redis://:12345678@127.0.0.1:26379",
		"redis://:12345678@127.0.0.1:26380",
		"redis://:12345678@127.0.0.1:26381",
	}

	customConnFunc := func(network, addr string) (radix.Conn, error) {
		return radix.Dial(network, addr,
			// radix.DialTimeout(1*time.Second),
			radix.DialAuthPass("12345678"),
		)
	}

	sentinel, err := radix.NewSentinel("mymaster", address, radix.SentinelConnFunc(customConnFunc))
	if err != nil {
		fmt.Println(err)
	}

	m, s := sentinel.Addrs()
	fmt.Println(m)
	fmt.Println(s)
}
And this blocks:
package main

import (
	"fmt"

	"github.com/mediocregopher/radix"
)

func main() {
	address := []string{
		"redis://:12345678@127.0.0.1:26379",
		"redis://:12345678@127.0.0.1:26380",
		"redis://:12345678@127.0.0.1:26381",
	}

	// customConnFunc := func(network, addr string) (radix.Conn, error) {
	// 	return radix.Dial(network, addr,
	// 		// radix.DialTimeout(1*time.Second),
	// 		radix.DialAuthPass("12345678"),
	// 	)
	// }

	// sentinel, err := radix.NewSentinel("mymaster", address, radix.SentinelConnFunc(customConnFunc))
	sentinel, err := radix.NewSentinel("mymaster", address)
	if err != nil {
		fmt.Println(err)
	}

	m, s := sentinel.Addrs()
	fmt.Println(m)
	fmt.Println(s)
}

**Comment by mediocregopher** [comment]
I see what the problem is. The issue is that `NewSentinel` is retrieving the full list of sentinel addresses from one of the given sentinels. When it does that it's losing the password sent with the original addresses. I refactored the URL parsing code a bit so that the credentials are carried over. Can you please try out #120 and double check that it fixes the issue for you?

**Comment by yushizhao** [comment]
Yes! It works now.
