### ISSUE TITLE
shall we add Sentinel::SentinelAddrs()?

### ISSUE THREAD

**Issue by yushizhao** [mediocregopher/radix#114]
I want to monitor not only masters and slaves but also sentinels. 
But you know what the innerSpin() is doing everything I want! So all I need is, like output masters and slaves with Addrs(), output sentinels' addresses with something like SentinelAddrs(). 
I am probably going to fork and do it on my own, but if other people also want it, how about we add it here?

**Comment by mediocregopher** [comment]
Hi @yushizhao , that sounds like a great idea! I look forward to the PR :)
