### ISSUE TITLE
how to PSub slaves in sentinel?

### ISSUE THREAD

**Issue by yushizhao** [mediocregopher/radix#119]
After get slaves using Sentinel::Client(), we can Do(cmd) with it, but how about Sub and PSub?

**Comment by mediocregopher** [comment]
The `Client` method will return a Pool of connections, but the Sub and PSub functions were more designed to interact with a single connection. I would recommend using the `Sentinel.Addrs` method and creating your pubsub connections off of that.

**Comment by yushizhao** [comment]
I see. Use something like DialPrimary and DialSecondary. Like dialSentinel.

**Comment by mediocregopher** [comment]
Yup!
