### ISSUE TITLE
 in Sentinel::innerSpin(), how to determine whether a node is down

### ISSUE THREAD

**Issue by yushizhao** [mediocregopher/radix#121]
I am considering using `s-down-time` for two reason
1 easier to parse than `flags`
2 innerSpin() will connect to one sentinel, let's say A. Then, `s-down-time` will only exist, if, in A's view, a sentinel is down.
Therefore, we can get lived sentinels as A + sentinels do not have `s-down-time`.

**Comment by mediocregopher** [comment]
The reason I'm hesitant to make this change is that I don't see what's wrong with the current behavior. The only time the client ever needs to know the list of sentinel addresses is when its connection to the last sentinel instance was cut for some reason. If that sentinel, or the client's connection to it, is so unstable that it's randomly dropping out of existence, I wouldn't necessarily trust its view of which other sentinels are alive or not anyway. I'd rather have full knowledge of all sentinels in the client and try to connect to them all.

I don't want to just outright say "no", but I think there needs to be more justification as to why it's necessary to complicate the behavior of the client.

**Comment by yushizhao** [comment]
First of all, thank you for your comment and your consideration!
I understand, this may not be a useful feature to most of us. So I probably do this around the current client without change it.
The reason I need it is, I simply want to monitor all instances for operation purpose. I can try to connect all the instances manually, but since their are poking each other all the time, I trust their judgement.
