### ISSUE TITLE
EvalAction randomly crash

### ISSUE THREAD

**Issue by nsagnett** [mediocregopher/radix#123]
Hello ! 

I'm using lua scripting to fetch batch messages from Redis and sometimes, my soft crashes without any reason :
```
unexpected fault address 0x866f53
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x866f53 pc=0x866f53]
goroutine 117 [running]:
runtime.throw(0xb061e7, 0x5)
/usr/local/go1.12.5/src/runtime/panic.go:617 +0x72 fp=0xc000236cc8 sp=0xc000236c98 pc=0x4489d2
runtime.sigpanic()
/usr/local/go1.12.5/src/runtime/signal_unix.go:397 +0x401 fp=0xc000236cf8 sp=0xc000236cc8 pc=0x45d381
github.com/mediocregopher/radix/v3.(*evalAction).Run(0xc0020be960, 0xc41580, 0xc000478d40, 0xc000478d40, 0x471b01)
/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/action.go:417 +0x83 fp=0xc000236d40 sp=0xc000236cf8 pc=0x866f53
github.com/mediocregopher/radix/v3.(*ioErrConn).Do(...)
/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/pool.go:51
github.com/mediocregopher/radix/v3.(*Pool).Do(0xc00053c2a0, 0xc39b80, 0xc0020be960, 0x0, 0x0)
/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/pool.go:524 +0xe3 fp=0xc000236d80 sp=0xc000236d40 pc=0x869e93
```
Thanks

**Comment by nussjustin** [comment]
Are you using the `Action` returned by `(EvalScript).Cmd` multiple times in different goroutines? `Action` instances should not be used concurrently unless explicitly allowed in the documentation. In case of the `Action` returned by `(EvalScript).Cmd` (which is a `*evalAction`) using the same `Action` instance multiple times in different goroutines will lead to races. 

Did you try building your program with the race detector enabled? (by passing the `-race` flag to `go build`/`go install`/`go run`). If I'm correct running the program with the race detector enabled should lead to a big error message being printed.

**Comment by nsagnett** [comment]
Thanks for the precision ! 

Unfortunately, i'm using it from only one goroutine and the documentation example to use EVAL says "set as a global variable.
Also, I can't find any part talking about concurrent uses Action

**Comment by mediocregopher** [comment]
Hi @nsagnett, can you post an example showing how you're using `EvalScript`? Note that the `EvalScript` is intended to be a global variable, but the `Action` which is returned from the `Cmd` method is only intended to be used once, just like the top-level `Cmd` and `FlatCmd` function.

**Comment by nsagnett** [comment]
Yes, sure
```
package redis

import (
	"fmt"
	"github.com/mediocregopher/radix/v3"
)

const lrangeLtrimScriptFmt = `
		local res = redis.call("LRANGE", KEYS[1], %s, %s)
		redis.call("LTRIM", KEYS[1], %s, %s)
		return res
`

type Client struct {
	pool            *radix.Pool
	lrangeLtrimEval radix.EvalScript
	config          *Config
}

func NewClient(config *Config) (*Client, error) {
	pool, err := radix.NewPool("unix", "/tmp/redis.sock", 3)
	if err != nil {
		return nil, err
	}
	return &Client{
		pool:            pool,
		lrangeLtrimEval: radix.NewEvalScript(1, fmt.Sprintf(lrangeLtrimScriptFmt, "0", "999", "1000", "-1")),
		config:          config,
	}, pool.Do(radix.Cmd(nil, "PING"))
}

func (c *Client) FetchMessages() [][]byte {

	var results []string
	_ = c.pool.Do(c.lrangeLtrimEval.Cmd(&results, "redis-queue"))

	if len(results) == 0 {
		_ = c.pool.Do(radix.Cmd(&results, "BLPOP", "redis-queue", "1"))
		if len(results) == 2 {
			return [][]byte{[]byte(results[1])}
		}
	}

	messages := make([][]byte, len(results))
	for i, res := range results {
		messages[i] = []byte(res)
	}

	return messages
}
```

**Comment by nsagnett** [comment]
An other stack trace : 
```
unexpected fault address 0x8654bf
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8654bf pc=0x8654bf]
goroutine 109 [running]:
runtime.throw(0xb061e7, 0x5)
/usr/local/go1.12.5/src/runtime/panic.go:617 +0x72 fp=0xc000258b98 sp=0xc000258b68 pc=0x4489d2
runtime.sigpanic()
/usr/local/go1.12.5/src/runtime/signal_unix.go:397 +0x401 fp=0xc000258bc8 sp=0xc000258b98 pc=0x45d381
github.com/mediocregopher/radix/v3/resp/resp2.(*Any).UnmarshalRESP(0xc0003ec6a0, 0xc000504180, 0xc000258cd0, 0x18)
<autogenerated>:1 +0x5f fp=0xc000258c08 sp=0xc000258bc8 pc=0x8654bf
github.com/mediocregopher/radix/v3.(*connWrap).Decode(0xc0003aece0, 0xc34d20, 0xc0003ec6a0, 0xc0003ec6a0, 0xc000258cd0)
/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/radix.go:245 +0x42 fp=0xc000258c38 sp=0xc000258c08 pc=0x86a832
github.com/mediocregopher/radix/v3.(*ioErrConn).Decode(0xc0003aed00, 0xc34d20, 0xc0003ec6a0, 0xc0003ec6a0, 0x0)
/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/pool.go:43 +0x4b fp=0xc000258c88 sp=0xc000258c38 pc=0x86852b
github.com/mediocregopher/radix/v3.(*evalAction).Run.func1(0xa98a00, 0xc0003ec680, 0x44774f)
/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/action.go:414 +0xf7 fp=0xc000258cf8 sp=0xc000258c88 pc=0x86b9a7
github.com/mediocregopher/radix/v3.(*evalAction).Run(0xc001a28ea0, 0xc41580, 0xc0003aed00, 0xc0003aed00, 0x471b01)
#011/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/action.go:417 +0x83 fp=0xc000258d40 sp=0xc000258cf8 pc=0x866f53
github.com/mediocregopher/radix/v3.(*ioErrConn).Do(...)
/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/pool.go:51
github.com/mediocregopher/radix/v3.(*Pool).Do(0xc0003a0000, 0xc39b80, 0xc001a28ea0, 0x0, 0x0)
/home/admin/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/pool.go:524 +0xe3 fp=0xc000258d80 sp=0xc000258d40 pc=0x869e93
```

**Comment by mediocregopher** [comment]
Hmmm, that is exceedingly strange. Your code is fine with me, and that error indicates it's panicking when trying to read from the connection, which shouldn't really happen. All that I can think is that it has to do with using redis over a unix socket, which is a use-case I haven't tested much. Does this problem still happen if you connect to redis over tcp?

**Comment by nsagnett** [comment]
Now that you say it, I've an other program which similar code but connected over tcp and I've never seen this kind of problem, I will switch connection mode. Thanks !
But Have you an idea to fix that with Unix socket ?

**Comment by nussjustin** [comment]
Can you tell us what Go version you are using? And what OS and kernel you are running? 

A unix socket should not behave differently than a TCP socket and even if there is a problem with the socket you should never get a SIGSEGV.

This should never happen in any Go program that does not use the unsafe package. Since neither radix nor your code example use the unsafe package, this must either be a bug in Go runtime, the generated code or the kernel itself.

The line with the faulting address `pc` points to an auto-generated function, which means this could be caused by some optimization. You could try to build your program with optimizations disabled (`go build -gcflags '-N -l'`) to see if the error only happens with optimizations enabled.

**Comment by nsagnett** [comment]
Thanks for the explanation, it's clear !
Go 1.12.5 on Linux debian stretch amd64

**Comment by mediocregopher** [comment]
Hi @nsagnett, did you get a chance to try out your code with the gcflags that justin posted? I'm curious what the cause of this could be, but since I can't reproduce it locally I'm not sure where else to go with this issue.

**Comment by nsagnett** [comment]
Hi @mediocregopher , sorry but i've not tried this because I switch to tcp socket (it was a hotfix, this issue appears only in production..) so I can't take the risk to build without optimization.
For the moment, switching from Unix to TCP socket seems fix it

**Comment by mediocregopher** [comment]
Do you mind if I close this then? I know we didn't fix the original issue but I don't think that's a problem in radix, seems more like a go runtime issue to me.

**Comment by nsagnett** [comment]
Yes I think, thanks for advices !
