### ISSUE TITLE
expected * got -/

### ISSUE THREAD

**Issue by codeliger** [mediocregopher/radix#124]
> FATAL   consumer/consumer.go:62 Failed to connect to redis      {"REDIS_HOST": "0.0.0.0:6379", "error": "expected prefix \"*\", got \"-\""}

Anyone have this error? I cannot figure it out.

**Comment by nussjustin** [comment]
Could you show us how you connect to Redis? Are you connecting to a standalone Redis server or a cluster instance?

Your error says that your app failed to connect to Redis and that it got an `expected prefix %q, got %q` style error, but connecting to Redis does not normally involve any reading or writing, so you should normally never get one of these.

Are you passing a password (either via URL or via `DialAuthPass`) or do you select a DB when connecting (again either via URL or via `DialSelectDB`)? These are the only two cases that come to my mind where radix would send some commands before returning a new connection to the user.

**Comment by mediocregopher** [comment]
I'm going to modify this error message so it's a little more helpful. I don't think people should need to know protocol details to debug a problem like this.

**Comment by codeliger** [comment]
I think the problem was solved when i `docker-compose up` a redis cluster instead of a single `redis:4.0` docker instance.

I was simply passing `0.0.0.0:6379` after trying `:6379`

**Comment by mediocregopher** [comment]
It sounds like you fixed it then, @codeliger? Can I close this issue or are you still having problems?

**Comment by mediocregopher** [comment]
I'll go ahead and close it, feel free to reopen if you're still having problems.
