### ISSUE TITLE
How do I use pubsub in redis-cluster environment?

### ISSUE THREAD

**Issue by melkus** [mediocregopher/radix#133]
Hello

I cannot find any method to create a pubsub connection from Cluster. The only idea that came to my mind is to get cluster topo, get random node address and then use permanent pubsub to establish a standalone connection to it. And I will have to monitor cluster topo change.

Do you have better advice?

**Comment by mediocregopher** [comment]
Hi @melkus ! Yes your strategy sounds like the best one. You can have the topo retrieval be a part of the `ConnFunc` which is passed into `PersistentPubSub`, like so:

```go
ps := radix.PersistentPubSub("", "", func(string, string) (radix.Conn, error) {
    topo := cluster.Topo()
    node := topo[rand.Intn(len(topo))]
    return radix.Dial("tcp", node.Addr)
})
```

You shouldn't have to do any monitoring of the cluster's topo yourself, as all publishes should get gossiped to all nodes in the cluster. If the node that `PersistentPubSub` is currently connected to becomes unavailable this will automatically pick a new alive node in the cluster and connect to that.

**Comment by nussjustin** [comment]
@mediocregopher maybe this should be added as an example? this seems like something that could come up quite often.

**Comment by melkus** [comment]
@mediocregopher thanks a lot.
@nussjustin it would be great to have an example like that. I spent much time searching for a snippet.

**Comment by mediocregopher** [comment]
Yeah an example is a good idea, I'll leave this issue open as a reminder to do that soon.

**Comment by mediocregopher** [comment]
Added an [example](https://godoc.org/github.com/mediocregopher/radix#example-PersistentPubSub--Cluster) under PersistentPubSub.
