### ISSUE TITLE
Support Redis 6 TYPE filter in Scanner

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#140]
Redis 6 will add support for filtering the keys returned by `SCAN` for keys containing values of a specific type (as returned by the `TYPE` command, e.g. `string`).

The implementation is basically what one would expect: For every key Redis checks the type and skips keys that don't have matching types. The big difference from manually filtering out keys that don't is that with the new `TYPE` option there is no need to execute N extra commands per `SCAN` iteration (where N is the number of keys returned), which can become quite expensive and slow when not using Lua scripts.

For users of older Redis versions we could try to give a nice error message (the default would be "ERR syntax error") and give an example using a Lua script.

PR for the change in Redis: antirez/redis#6116
PR for the documentation on redis.io: antirez/redis-doc#1137

**Comment by nussjustin** [comment]
Just realized that Lua scripts can't be used with the `Scanner` type, so giving an example would not help too much.

**Comment by mediocregopher** [comment]
Adding a `Type` field to `ScanOpts` seems straightforward enough 👍 

> For users of older Redis versions we could try to give a nice error message

I'm not sure if that's worth the effort, unless there's an easy way for us to know that their version of redis doesn't support `Type`. But if all we have is the `ERR syntax error` message then that might be too flimsy of evidence to go on.

**Comment by mediocregopher** [comment]
Well, actually, when is redis 6 slated to be released? It's currently only in unstable right? I think we should wait till it goes into rc before adding this.

**Comment by nussjustin** [comment]
I created this issue so we don't forget this. Redis 6 is still a few months away I think.

**Comment by nussjustin** [comment]
Sent a PR since Redis RC1 is out now and the GA should be in a few weeks.
