### ISSUE TITLE
EvalAction never runs EVAL, only EVALSHA

### ISSUE THREAD

**Issue by everettcaleb** [mediocregopher/radix#149]
When I run my EvalAction.Cmd(), it always fails with the following "NOSCRIPT" error:

```
NOSCRIPT No matching script. Please use EVAL.
```

Here's a snippet that shows how I'm using it (I cannot show the real code since this is for work):

```go
var data string
if err := pool.Do(script.Cmd(&data, "MYKEY", strconv.FormatInt(time.Now().Unix(), 10))); err != nil {
	return nil, fmt.Errorf("failed to run Lua script: %v", err)
}
if data == "" {
	return nil, nil
}
```

Where `pool` is a `*radix.Pool` and `script` is a `radix.EvalScript`.

While troubleshooting, I modified some code in `action.go` locally to get more debug info. Here's the code with my changes (just `MarshalRESP` and `Run`):

```go
func (ec *evalAction) MarshalRESP(w io.Writer) error {
	fmt.Printf("evalAction.MarshalRESP: %+v\n", ec) // ADDED

	// EVAL(SHA) script/sum numkeys args...
	if err := (resp2.ArrayHeader{N: 3 + len(ec.args)}).MarshalRESP(w); err != nil {
		return err
	}

	var err error
	if ec.eval {
		fmt.Println("USING EVAL") // ADDED
		err = marshalBulkStringBytes(err, w, eval)
		err = marshalBulkString(err, w, ec.script)
	} else {
		fmt.Println("NOT USING EVAL") // ADDED
		err = marshalBulkStringBytes(err, w, evalsha)
		err = marshalBulkString(err, w, ec.sum)
	}

	err = marshalBulkString(err, w, strconv.Itoa(ec.numKeys))
	for i := range ec.args {
		err = marshalBulkString(err, w, ec.args[i])
	}
	return err
}

func (ec *evalAction) Run(conn Conn) error {
	run := func(eval bool) error {
		ec.eval = eval
		fmt.Println("evalAction func run eval=", eval) // ADDED
		fmt.Printf("evalAction: %+v\n", ec) // ADDED
		if err := conn.Encode(ec); err != nil {
			return err
		}
		return conn.Decode(resp2.Any{I: ec.rcv})
	}

	err := run(false)
	if err != nil && strings.HasPrefix(err.Error(), "NOSCRIPT") {
		err = run(true)
	}
	return err
}
```

This is the (script redacted) log output I get when I run the test code snippet:

```
evalAction func run eval= false
evalAction: &{EvalScript:{script:REDACTED
 sum:5bad24f2ee4390d367eee730d6a0645a409d1e61 numKeys:1} args:[MYKEY 1563817342] rcv:0xc000150350 eval:false}
evalAction.MarshalRESP: &{EvalScript:{script:REDACTED sum:5bad24f2ee4390d367eee730d6a0645a409d1e61 numKeys:1} args:[MYKEY 1563817342] rcv:0xc000150350 eval:false}
NOT USING EVAL
evalAction func run eval= true
evalAction: &{EvalScript:{script:REDACTED sum:5bad24f2ee4390d367eee730d6a0645a409d1e61 numKeys:1} args:[MYKEY 1563817342] rcv:0xc000150350 eval:true}
failed to run Lua script: NOSCRIPT No matching script. Please use EVAL.
```

And in addition, here's the MONITOR output from the Redis instance (redacted where confidential):

```
1563818548.404515 EVALSHA 5bad24f2ee4390d367eee730d6a0645a409d1e61 1 MYKEY 1563818548
1563818551.638893 INFO
1563818561.649949 INFO
1563818571.727928 INFO
```

So it almost looks like it never gets re-run. Weird.

**Comment by everettcaleb** [comment]
I'll continue digging and if I can fix it, I will submit a PR.

**Comment by nussjustin** [comment]
`*ioErrConn` [was changed](https://github.com/mediocregopher/radix/blob/master/pool.go#L36-L58) to return early when `lastIOErr` is not `nil`. I guess you are running into a side effect of this, but haven't tested if this is really the problem.

**Comment by nussjustin** [comment]
Does the problem reproduce on a normal `Conn` (not a `Pool`)?

**Comment by everettcaleb** [comment]
I haven't tried with a regular Conn, but given it's an interface shouldn't the behavior be the same anyway (philosophically)? I can add code to clear the last error if you'd like and test that, too.

**Comment by everettcaleb** [comment]
Changing `Run()` to clear the last error resolves this problem. It's a bit hacky to do this so may not be a good final solution but if you're cool with it I can submit a PR.

```go
func (ec *evalAction) Run(conn Conn) error {
	run := func(eval bool) error {
		ec.eval = eval
		fmt.Println("evalAction func run eval=", eval)
		fmt.Printf("evalAction: %+v\n", ec)
		if c, ok := conn.(*ioErrConn); ok {
			c.lastIOErr = nil
		}
		if err := conn.Encode(ec); err != nil {
			return err
		}
		return conn.Decode(resp2.Any{I: ec.rcv})
	}

	err := run(false)
	if err != nil && strings.HasPrefix(err.Error(), "NOSCRIPT") {
		err = run(true)
	}
	return err
}
```

**Comment by nussjustin** [comment]
This fails (I added this to `TestIoErrConn`):

```go
	t.Run("ReusableAfterRESPError", func(t *T) {
		ioc := newIOErrConn(dial())
		defer ioc.Close()

		err1 := ioc.Do(Cmd(nil, "EVAL", "Z", "0"))
		require.IsType(t, resp2.Error{}, err1)

		err2 := ioc.Do(Cmd(nil, "GET", randStr()))
		require.Nil(t, err2)
	})
```

The following makes the test pass:

```diff
diff --git a/pool.go b/pool.go
index 5c43926..ae229ac 100644
--- a/pool.go
+++ b/pool.go
@@ -9,6 +9,7 @@ import (
        errors "golang.org/x/xerrors"
 
        "github.com/mediocregopher/radix/v3/resp"
+       "github.com/mediocregopher/radix/v3/resp/resp2"
        "github.com/mediocregopher/radix/v3/trace"
 )
 
@@ -51,7 +52,7 @@ func (ioc *ioErrConn) Decode(m resp.Unmarshaler) error {
        err := ioc.Conn.Decode(m)
        if nerr, _ := err.(net.Error); nerr != nil {
                ioc.lastIOErr = err
-       } else if err != nil && !errors.As(err, new(resp.ErrDiscarded)) {
+       } else if err != nil && !errors.As(err, new(resp2.Error)) && !errors.As(err, new(resp.ErrDiscarded)) {
                ioc.lastIOErr = err
        }
        return err
```

The problem is this breaks 2 other tests in `TestPipeliner`. Will think of a fix.

**Comment by everettcaleb** [comment]
OK. I'm going to run with my temporary hack of clearing the error in place since this satisfies my use-case that I need right now. Let me know when you have a more permanent fix :)

**Comment by everettcaleb** [comment]
Maybe it would be better to always run `EVAL` the first time an `EvalScript` is used? I know this introduces state on the application-side, but it may be better than having to change error handling stuff for this.

**Comment by nussjustin** [comment]
> Maybe it would be better to always run EVAL the first time an EvalScript is used? I know this introduces state on the application-side, but it may be better than having to change error handling stuff for this.

This wouldn't work. We would need to track this in the `EvalScript` from which the `evalAction` was created, but that would prevent the `EvalScript` from being used with other Redis nodes that don't already the script loaded.

**Comment by everettcaleb** [comment]
I'll close my PR if you think yours resolves this better. Just figured I'd offer an alternative since this works for me locally.

**Comment by mediocregopher** [comment]
So what I'm curious about is: why is the `resp2.Error` getting returned from `EvalScript` not being wrapped in an `ErrDiscarded`? I'm gonna look into that real quick, because that might be the "true" solution there.

**Comment by mediocregopher** [comment]
So just to add to the confusion, there's another PR which would fix this problem. The return from `Any.UnmarshalRESP` wasn't wrapping the error in an `ErrDiscarded` for the case of the message being a RESP error, so I fixed the problem there, rather than in Pool.

**Comment by mediocregopher** [comment]
Actually, the docs on `Any` specifically say:

```
// If an error type is read in the UnmarshalRESP method then a resp2.Error will
// be returned with that error, and the value of I won't be touched.
```
so maybe having Any returning a `resp2.ErrDiscarded` instead would qualify as a breaking change? That's really unfortunate. I'm gonna go to sleep and maybe some good excuse to change it anyway will come to me in the morning :P

**Comment by nussjustin** [comment]
@mediocregopher  You could implement `As` on `resp2.Error` so that it could be handled by `xerrors.As(err, new(resp.ErrDiscarded))`. That way you wouldn't have to change `Any` at all.

**Comment by mediocregopher** [comment]
That's a great idea! I went ahead and did that in my PR, thanks :)

**Comment by mediocregopher** [comment]
Merged that, thanks @nussjustin !

@everettcaleb thanks for opening the issue and making the PR, sorry it couldn't go through. For future reference: my main issue with it was that it introduced redis specific functionality (the NOSCRIPT error) into the `resp2` package, which is intended to be agnostic to where the protocol is being used. Obviously the package has some features which make using it with redis _easier_, but nothing which could _only_ be used with redis.

**Comment by mediocregopher** [comment]
Gonna leave the package as it is for a few days, if no other issues pop up I'll tag this as `v3.3.3`, since this is a big breakage.

**Comment by everettcaleb** [comment]
@mediocregopher I wasn't super attached to the PR 👍  I really want to thank both you and @nussjustin for the quick responses and the effort you put into fixing this. You guys are awesome 🥇
