### ISSUE TITLE
resp2 to support io.Writer reciever on unmarshall array

### ISSUE THREAD

**Issue by maorlipchuk** [mediocregopher/radix#154]
As part of the Cmd API there is a great functionality that allow us to use an io.Writer interface as a receiver. (see https://github.com/mediocregopher/radix/blob/master/action.go#L159 comment [1])
It looks from the code that an io.Writer reciever is supported for bulk string values fetched from Redis(based on the BulkStringPrefix '$' see [2]) although for array, the io.Writer is only supported when the receiver points to a slice although I would need to use it for a struct (see [3])
How array should be handled with io.Writer for struct?
Is there any chance to add an example in the documentation?

Thanks 

[1]
> // Cmd is used to perform a redis command and retrieve a result. It should not
> // be passed into Do more than once.
> //
> // If the receiver value of Cmd is a primitive, a slice/map, or a struct then a
> // pointer must be passed in. It may also be an io.Writer, an
> // encoding.Text/BinaryUnmarshaler, or a resp.Unmarshaler. See the package docs
> // for more on how results are unmarshaled into the receiver.
> 

[2] https://github.com/mediocregopher/radix/blob/master/resp/resp2/resp.go#L936
[3] https://github.com/mediocregopher/radix/blob/master/resp/resp2/resp.go#L1054

**Comment by mediocregopher** [comment]
Hi @maorlipchuk ! I'm not sure I quite understand what your situation is. Are you trying to unmarshal into a struct where one of the fields is an `io.Writer`, something like:

```go
var foo struct {
    A string
    B io.Writer
}

err := client.Do(radix.Cmd(&foo, "HGETALL", "mykey"))
```

if so that should just work, if it doesn't it would be a bug. Could you post an example of what you're trying to do?

**Comment by maorlipchuk** [comment]
Thanks for the quick response @mediocregopher.
I apologize for being unclear, I will try to clarify my question:

I got a struct [1] and I use this struct to implement the io.writer interface by implementing the Write method [2]:
[1] `type Temp struct {}`

[2] 
```
func (t Temp) Write(data []byte) (n int, err error) {
	  //doSomething with data
	  return 0, nil
      }
```

Now, for a simple "get" command, everything works as expected:
        `client.Do(radix.Cmd(&Temp{}, "get", "key")`
Executing the command above will get me to my Write method
(From the code it looks that resp#UnmarshalRESP will use the BulkStringPrefix and resp#unmarshalSingle will clasify Temp as io.Writer and Write method will be called. (see line 850 in resp.go))

but when I want to call "smembers" for example the behaviour is different.
 `client.Do(radix.Cmd(&Temp{}, "smembers", "smembers_key")`
Instead of clasify my struct as an io.writer and call my Write method
it seems that we go though resp.go#unmarshalArray (line 956) which does other functionality.
I would assume that using io.writer will simply pass the reponse's bytes of the redis result without clasifying it, or perhaps I'm doing something wrong...

I hope the explanation makes it more clear now,
Thanks

**Comment by mediocregopher** [comment]
Ok, I understand what you're doing now, thanks for the explanation :)

> I would assume that using io.writer will simply pass the reponse's bytes of the redis result without clasifying it, or perhaps I'm doing something wrong...

I think that's where the confusion is. `resp2.Any.UnmarshalRESP` will only try to use the `Write` method if there is a non-array RESP element being read off the wire. I don't think it could be any other way. For the SMEMBERS case, what would you expect to get written to the Writer? A concatenation of all the members? All members separated by some delimiter? It's not obvious what exactly the driver will do in that case, so I think it's better to not do anything.

Are you intending that `Temp` should have both single element responses (like from GET) and multi-element responses (like from SMEMBERS) processed by `Write`? Or did you intend instead to do something like:

```go
var temps []Temp
client.Do(radix.Cmd(&temps, "SMEMBERS", "key"))
```

That would allocate `temps` with a `Temp` for each member of `key`, and then call `Write` on each `Temp` for its respective member (or it should, if radix works correctly).

If you really do want to have `Temp` be able to handle both single element and array responses, I think you'll have to have it implement `UnmarshalRESP` itself. It shouldn't be too hard, inside the method you would:
1) Peek the `bufio.Reader` to see what the message type is (the different types are defined in the `resp2` package.
2) If it's an array, use `resp2.ArrayHeader` to read the header and find out the number of elements.
  a) For each element read off the bytes in some way. You can use `resp2.Any` along with your `Temp` to take advantage of the `Write` method, but how exactly you do it is up to you.
3) If it's not an array, use `resp2.Any` to read directly into the `Temp` (which will use the `Write` method).

Hope that makes sense, I can help you with the specific code if you're having trouble, but I would need to know exactly what you think should happen when you're reading an array.

**Comment by maorlipchuk** [comment]
Great answer, Thanks!
I think that I will try to implement UnmarshalRESP as you suggested, if I will have any problems I will let you know.
Thanks again!

**Comment by mediocregopher** [comment]
@maorlipchuk do you mind if I close this issue? did you get it working?
