### ISSUE TITLE
HSACN, ZSCAN, ... not supporting?

### ISSUE THREAD

**Issue by sjang** [mediocregopher/radix#162]
Hello,
Thesedays, I am crush on Golang.
I think that Radix is a very efficient redis client.
Today, I tried to use the HSCAN command.
But, it is not working so I checked the code. I found the below.

<pre><code>
func (c *Cluster) NewScanner(o ScanOpts) Scanner {
	if strings.ToUpper(o.Command) != "SCAN" {
		panic("Cluster.NewScanner can only perform SCAN operations")
	}
.
.
.
</code></pre>

Does it mean that HSCAN, ZSCAN are not supporting except SCAN?

Thanks.

**Comment by sjang** [comment]
Hi, @mediocregopher 
I will try it.
Thank you for reply.

**Comment by mediocregopher** [comment]
I went ahead and added a bit of extra documentation about this, gonna close this issue. If you still have any questions feel free to re-open this issue or create a new one :)

**Comment by sjang** [comment]
good close
