### ISSUE TITLE
Cluster sync may takes times when a node is stopped

### ISSUE THREAD

**Issue by dprofeta** [mediocregopher/radix#166]
Hello,
I noticed doing chaos testing that request may be block on the addrForKey, because the sync was taking time (around 10ms) to close the connection to a node that is stopping.

I will submit a PR to defer the close after the swap of the pool so that the lock can be released.

**Comment by mediocregopher** [comment]
Good catch, I look forward to your PR :) Has the chaos testing revealed any other issues? How has radix held up overall?
