### ISSUE TITLE
Parsing role command output

### ISSUE THREAD

**Issue by adamflott** [mediocregopher/radix#167]
Is this possible to represent with a type? Not sure how to read this output.
```
$ redis-cli role
1) "master"
2) (integer) 2067836187
3) 1) 1) "10.3.0.198"
      2) "6379"
      3) "2067836187"
   2) 1) "10.3.0.79"
      2) "6379"
      3) "2067835652"
   3) 1) "10.3.0.218"
      2) "6379"
      3) "0"
```

**Comment by mediocregopher** [comment]
Yeah, that's a weird one >_< I'd recommend unmarshalling into a
`[]resp2.RawMessage`, and then for each of the three elements you can
unmarshal into a type that makes sense.

Alternatively, if you're really worried about performance, you could write
a custom `resp.Unmarshaler`. I'd check out some of the custom stream types
to get an idea on how that works (or I can help if you need).

**Comment by adamflott** [comment]
Ok now that I've gone through some of the protocol it has now made more sense.

I only needed the first piece (`resp2.BulkString`) which worked perfect with 

```
var roleRawOutput []resp2.RawMessage
client.Do(radix.Cmd(&roleRawOutput, "ROLE"))
var role resp2.BulkString
roleRawOutput[0].UnmarshalInto(&role)
fmt.Println(role.S)
```

Thanks for the pointer! You can close if you've like
