### ISSUE TITLE
Locking on sentinel close

### ISSUE THREAD

**Issue by albinanto** [mediocregopher/radix#172]
Hi,

I code redis client that use sentinel but it seems lock on wait group while calling Close()

	package main

	import (
		"github.com/mediocregopher/radix"
		"log"
	)

	func main() {
		sentinel, err := radix.NewSentinel("mymaster", []string{"127.0.0.1:26379", "127.0.0.2:26379"})

		if err != nil {
			log.Println(err)
			return
		}

		defer sentinel.Close()

		if err := sentinel.Do(radix.Cmd(nil, "PUBLISH", "pub", "this is a message")); err != nil {
			log.Println(err)
		}

		log.Println("finish")
	}

The code will not exit after print finish.

**Comment by nussjustin** [comment]
The code basically deadlocks when updating the clients and/or sentinel addresses trying to acquire `sc.l`, which is held by the goroutine that called `Close` and which is waiting on the background goroutines to exit. Moving the `Lock`/`Unlock` calls after the `sc.closeWg.Wait()` calls fixes the problem.

**Comment by mediocregopher** [comment]
merged and tagged a new release
