### ISSUE TITLE
Implement random replica reads for Sentinel and Cluster

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#174]
Currently commands on Sentinel and Cluster instances are always send to the corresponding master node. For users with high traffic, especially when including many writes, the master can quickly become a bottleneck. A common way to work around this is sending (some) reads to replicas instead. This lifts some load from the master while increasing the chance for stale data (since Cluster and Sentinel are both AP systems the possibility is already there even when reading from the master).

Doing this with the current API is possible but also quite cumbersome. I propose that we add a way for both `Cluster` and `Sentinel` to make replica reads on random replicas, possibly through an extra method `Read` that works like `Do` but sends the command to a replica.

For Sentinel the nodes must be configured with `replica-read-only` to allow reads from replicas which could just be documented.

For Cluster each connection must manually call `READONLY` once, which is hard to implement with the current API and may be something we would need to require from the users to do themselves with a customer ClientFunc.

**Comment by mediocregopher** [comment]
(Sorry it took so long to respond to this -_-)

Starting with Sentinel seems to be the easiest option. I would suggest the name `DoSecondary` rather than `Read`; it's a bit wordier but it's more accurate, and conveys that the method is related to the `Do` method.

The `READONLY` thing is hard. Even if the user does use a custom `ClientFunc` there's the issue that the current Cluster implementation will promote a secondary Pool to a primary one during a failover event, if it can, rather than tear them down and start from scratch. But if all the Conns in the secondary Pool are in read-only mode, however they got in that mode, Cluster needs to be aware of that so it knows not to use the Pool.

**Comment by nussjustin** [comment]
> But if all the Conns in the secondary Pool are in read-only mode, however they got in that mode, Cluster needs to be aware of that so it knows not to use the Pool.

That shouldn't be necessary.

Contrary to its name the `READONLY` command does not make the connection read only (yeah, I know...). If you send `READONLY` on a connection you can still write to it, assuming it's a master. This also works when the server was still a replica when the connection was put into `READONLY` mode and only became a master after that, while the connection is still open.

You can take a look at the code that handles the `READONLY` flags for clusters here: https://github.com/antirez/redis/blob/cf6cbbb881556d0665e3c1a417ee1eacb0be857f/src/cluster.c#L5667-L5677

**Comment by mediocregopher** [comment]
Crazy >_< I wonder if there's any harm in just setting READONLY on all cluster connections then....

**Comment by nussjustin** [comment]
Just found a comment from @antirez that greatly clarifies the behavior of `READONLY`: https://github.com/antirez/redis/issues/2216#issuecomment-67939222

Quoting the important part:

> In general READONLY is basically free since it's a per-connection setting, once issued it's a contract between processes in a distributed system, it means "Hi, I'm a client, and I am aware I'm getting possibly stale data here. Moreover I want to just read so don't redirect me unless I try to write".
> 
> About the original feature request, it is not needed AFAIK, because the READONLY flag has effects only on slaves. If the node changes state from slave to master, the READONLY flag is totally ignored by the commands dispatching code:
> 
> [...]
> 
> So I guess we have nothing to do about this and we can close the issue unless we get further arguments. So for now I'm keeping this open to get your feedbacks. Thanks.

So my observations are the correct and intended behavior and it's just the documentation that is unclear.

**Comment by nussjustin** [comment]
Both sentinel and cluster support are now merged.

@mediocregopher There are already 13 merged PRs since the last release. I'd say it's time for a new release, wdyt?

**Comment by mediocregopher** [comment]
Yeah I'd say we're about due. There's one more issue that just got opened up, #204 , which might make the cut as well though.

**Comment by mediocregopher** [comment]
204 is down to wait, so I went ahead and tagged `v3.5.0`.
