### ISSUE TITLE
Question: Nil Pool Reference

### ISSUE THREAD

**Issue by msyihchen** [mediocregopher/radix#175]
It looks like programmer must guarantee that Redis must be active when starting the client program. If Redis is down and we create radix pool struct, NewPool returns a nil reference. Is it possible that it returns a non-nil pool reference and tries connecting until Redis is up?

**Comment by mediocregopher** [comment]
Hi @msyihchen ! `NewPool` should also return an error in that case. If you'd like to have it try to reconnect I'd recommend sticking your connection logic in a `for` loop in your application and retrying until it works:

```
// most basic implementation
var p *radix.Pool
var err error
for {
    if p, err = radix.NewPool(...); err == nil {
        break
    }
    log.Printf("couldn't connect to redis: %v", err)
    time.Sleep(1 * time.Second)
}
```

 Having radix do this internally would require quite a few more configuration options to `NewPool` (how many times to try reconnecting? for how long? which errors should cause it to give up? should it log the errors?). It's easier for everyone if the user does it on their end.

Hope that helps!

**Comment by msyihchen** [comment]
Thank you.

**Comment by cbenning** [comment]
@mediocregopher I would like to suggess this be revisited. I don't think a segfault is a very good "expected behaviour" when using any API correctly regardless of the timing of the calls.

I am using redis as a cache and if redis is not up I ignore it and fetch from source. This quirck of the API will complicate a use-case such as this. Most other clients would just retry to establish the connection and return error if failure occurs.

**Comment by mediocregopher** [comment]
@cbenning I think there might be a misunderstanding about the original issue. There should never be any segfaults from within radix, if there are please open an issue with that. If redis isn't up at the time `NewPool` is called it should return an error, and your application can decide what to do at that point.

**Comment by cbenning** [comment]
@mediocregopher Yeah digging further I've realized the error in my comment. In the case I found, the NewPool returned an error but also a non-nil client which my code ended up using regardless (which caused a segfault). That is obviously my fault and I have solved that issue. But just for your information it does indeed return a non-nil result which causes a segfault lower down if used.
