### ISSUE TITLE
radix.Client doesn't know redis server mode

### ISSUE THREAD

**Issue by msyihchen** [mediocregopher/radix#176]
It looks like the pool client created by NewPool cannot work with clustered redis and the cluster client created by NewCluster cannot work with non-clustered redis.
Ideally, programmers only need to pass in address and redis password without worrying about which radix.Client implementation to use. Do we have a common implementation of redis client that's able to detect Redis mode and decide if it's a pool client or cluster client?

**Comment by nussjustin** [comment]
It shouldn't be hard to build such an abstraction, but the question for me is how useful such an abstract would be.

Clusters have restrictions that standalone instances don't have (off the top of my head: only one database and commands must only work with keys on the current shard) and often need more complex handling in the applications (e.g. failover timeouts, consistency). Applications must, or rather should, thus still be build with cluster support in mind.

Given how simple this should be to implement¹ I don't think this should be in radix.

¹ Example implementation (untested)

```go
func SmartDial(network, addr string) (radix.Client, error) {
	c, err := radix.Dial(network, addr)
	if err != nil {
		return nil, err
	}

	infoErr := c.Do(radix.Cmd(nil, "CLUSTER", "INFO"))
	if infoErr == nil {
		_ = c.Close()
		return radix.NewCluster(network, addr)
	}
	if !strings.Contains(infoErr.Error(), "This instance has cluster support disabled") {
		_ = c.Close()
		return nil, err
	}

	return c, nil
}
```

**Comment by msyihchen** [comment]
Thank you.
