### ISSUE TITLE
NewScanner isn't a a function of Pool

### ISSUE THREAD

**Issue by msyihchen** [mediocregopher/radix#177]
In scanner.go, NewScanner expects a Pool client.
// NewScanner creates a new Scanner instance which will iterate over the redis
// instance's Client using the ScanOpts.
//
// NOTE if Client is a *Cluster this will not work correctly, use the NewScanner
// method on Cluster instead.
func NewScanner(c Client, o ScanOpts) Scanner {
}

In cluster_scanner.go, it has this function for Client with Cluster implementation,
func (c *Cluster) NewScanner(o ScanOpts) Scanner {
}

It looks like we have to end up writing something like the following:
var scanner radix.Scanner
switch typedClient := client.(type) {
case *radix.Cluster:
	scanner = typedClient.NewScanner(scanOpt)
case *radix.Pool:
	scanner = radix.NewScanner(typedClient,
		scanOpt)

Is it possible that radix library has the following function so we just need to call client.NewScanner(scanOpt)?
func (p *Pool) NewScanner(o ScanOpts) Scanner {

**Comment by mediocregopher** [comment]
Hi @msyihchen , I agree that the Scanner functions are pretty ugly, but I don't think adding yet another `NewScanner` method will help to fix that. Type checking on what your `Client` is is currently the recommended way to do it. Sorry :(
