### ISSUE TITLE
Determining if connection closed and reconnecting

### ISSUE THREAD

**Issue by mikesun** [mediocregopher/radix#182]
What would be the best way to check if a connection in a pool has closed (due to the Redis instance closing the connection) and then initiating a reconnect?

**Comment by nussjustin** [comment]
What is your goal? The pool will automatically create a new connection if an existing one is closed. If you just want to know when a connection is closed / reopened you can use the `trace` package to get this information.

**Comment by mikesun** [comment]
I'd like the pool to auto-reconnect to a Redis instance if the instance goes down and comes back up. It appears that the pool just does that in my testing. I was confused by what was said in this prior issue: https://github.com/mediocregopher/radix/issues/175#issuecomment-557753942

**Comment by mediocregopher** [comment]
That issue was referring to the specific case where the redis instance is not available while Pool is being initialized. Once initialized the Pool will remake connections which get disconnected. As justin said, you can use the `trace` package to monitor when it closes and reopens connections. Hope this helps, feel free to reopen the issue if you have any more questions :)

**Comment by misterEggroll** [comment]
Below is code I used to continually poll my redis server to:
a. Establish a connection
b. Once established, keep checking if the connection was maintained.

I'm making use of the `PING` redis command to do this.
```
package main

import (
	"fmt"
	"github.com/mediocregopher/radix/v3"
	"io"
	"time"
)

// NewRadixRedisClient - Return a redis client
func NewRadixRedisClient(host, port interface{}) (*radix.Pool, error) {
	redisClient, err := radix.NewPool("tcp", fmt.Sprintf("%v:%v", host, port), 10)
	if err != nil {
		return nil, err
	}
	return redisClient, nil
}

func main() {
	var client *radix.Pool
	var err error
	var deferred bool

	closeRedisConn := func(closeable io.Closer) {
		if closeable != nil {
			_ = client.Close()
		}
	}

	// Redis client - Initialize and connect
	if client, err = NewRadixRedisClient("localhost", 6379); err == nil {
		deferred = true
		defer closeRedisConn(client)
	}

	for {
		tick := time.Tick(time.Second * 2)
		quit := make(chan int)
		select {
		case <-tick:
			var err error
			var pong string
			mn := radix.MaybeNil{Rcv: &pong}
			fmt.Println("-------------\nCheck ...")
			if client == nil{
				fmt.Println("Connection not initialized. Attempting to reconnect ...")
				if client, err = NewRadixRedisClient("localhost", 6379); err == nil {
					deferred = true
					defer closeRedisConn(client)
				}
			} else {
				if err = client.Do(radix.Cmd(&mn, "PING")); err != nil {
					fmt.Println(err)
				} else {
					if pong == "PONG" {
						fmt.Println("Connected.")
						if !deferred {
							defer closeRedisConn(client)
							deferred = true
						}
					}
				}
			}
		case <-quit:
			// Stop polling and return
			return
		}
	}
}
```
NOTE: Please ignore code to close the pool. That has no use here, but is greatly useful in a goroutine containing similar code.

This code will ensure that initializing the redis connection is attempted even after failing the first time.

This is how I had my redis server setup for execution of the above:
Run script -> Server down -> Server up -> Server down -> Server up

The program output is as follows:

```
-------------
Check ...
Connection not initialized. Attempting to reconnect ...
-------------
Check ...
Connected.
-------------
Check ...
EOF
-------------
Check ...
read tcp [::1]:54873->[::1]:6379: read: connection reset by peer
-------------
Check ...
dial tcp [::1]:6379: connect: connection refused
-------------
Check ...
Connected.
```

Is this the correct approach or is there a better way to do this ?

**Comment by mediocregopher** [comment]
@misterEggroll I think you might need to reread the docs on [defer](https://gobyexample.com/defer) :) You're deferring a lot of calls to `closeRedisConn` within your `main` function, but since that function never returns they won't ever get called.
