### ISSUE TITLE
How to use Redis tracking.

### ISSUE THREAD

**Issue by luboszk** [mediocregopher/radix#183]
I'm wondering if currently, that library supports Redis tracking (documentation)[https://redis.io/topics/client-side-caching]. If not could anyone point me into the direction of how we could add support for that feature?
Any help would be really appreciated.

Cheers,
Lubosz.

**Comment by mediocregopher** [comment]
It looks like there's nothing that radix would need to do to support the
feature over RESP2. But perhaps a helper type, like was done with SCAN
calls, could be useful, since it's pretty involved. I'm definitely open to
proposals there. Also curious about:

* How does this interact with cluster?
* What different use-cases need to be supported?

**Comment by diltram** [comment]
@mediocregopher our use-case is like that:
1. We have an app which runs health checks against external systems, after the change of the state (system died or some connection issue happen) it stores information in Redis under some specific key eg. dc1/cluster1/name-of-external-system
2. Another application when receives traffic checks in Redis what's the status of that system. To decrease latency it needs to keep the cached status of the data and be informed when the status changes.
To be exact the application is an inline load balancer that manages a few hundred thousand backend members which status it monitors. The latency and amount of data exchanged must be kept as low as possible.

To provide that functionality we can use Pub/Sub but then it would require us to load all of the keys from the database and watch for changes but client-side caching looks way more promising than that, especially when new Opt-In caching would be available.

Could you point me in some direction? I was trying to find code about the SCAN which you mentioned but I was not able. Also, could you tell me more if it would be possible to achieve the redirect of notifications to a separate connection? It would be really helpful for us as it would allow us to keep our code clean and nicely organized.

Thanks a lot for all of the information and help!

Lubosz

**Comment by mediocregopher** [comment]
> I was trying to find code about the SCAN which you mentioned but I was not able.

What I was referring to was the helper types like [Scanner](https://godoc.org/github.com/mediocregopher/radix#Scanner) and [Cluster.NewScanner](https://godoc.org/github.com/mediocregopher/radix#Cluster.NewScanner). What I was pointing out was that, while it would be possible to perform SCANing with radix without radix having that `Scanner` functionality, doing so manually everytime is annoying, so it's useful to have that helper. I think the same thing will be likely to be the case with client-side caching. So I'm open to PRs with client-side caching helpers implemented :)

> Also, could you tell me more if it would be possible to achieve the redirect of notifications to a separate connection?

I think it's definitely possible to use [PersistentPubSub](https://godoc.org/github.com/mediocregopher/radix#PersistentPubSub) to receive updates about cached keys, and have another go-routine running which would then fetch the updated values based on the notifications from the pubsub.

I don't think I'll be able to have time to really implement this myself, but I'm curious how it goes for you, so please keep me updated if you can :)

**Comment by diltram** [comment]
Thanks a lot for all of the clarification @mediocregopher.

For now I will implement in my application a driver using simple `PersistentPubSub`. After having that implementation in place I will start working on getting that tracking implemented in here.
Will update the issue as I'm gonna start working on that.

**Comment by mediocregopher** [comment]
He @luboszk, I'm going to go ahead and close this issue for now, since it's been a bit since it's seen any activity. If you have any further questions feel free to re-open the issue or create a new one :)
