### ISSUE TITLE
Support authentication with username and password

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#188]
Redis 6 will introduce the concept of different users as part of the new ACL support.

We currently only support configuring a password via `DialAuthPass` and ignore usernames set via the URL/DSN.

I propose we...

1. Add a new function `DialAuthUser` that takes a username and a password.
2. Stop ignoring the username provided via URL/DSN.
3. Allow setting the username via URL parameter

If both a username and password is provided (either via `DialAuthUser` or via DSN/URL) radix should automatically try sending both. If only a password and no username is provided it should just send the password. This should work since Redis 6 still supports the old `AUTH` syntax (the old syntax `AUTH <password>` gets interpreted as `AUTH default <password>`).

This will break users with Redis versions < 6 that set a username other than "default" in their URL/DSN, but this shouldn't be a problem and I assume most people don't do this.

**Comment by mediocregopher** [comment]
That all sounds good to me :) Thanks for keeping up with the redis 6 changes. I've been mulling if it's worth it (or even possible) to shoehorn RESP3 support into `radix/v3` or if we should cut a new version and do some housekeeping.

**Comment by nussjustin** [comment]
Supporting RESP 2 and 3 at once with radix/v3 may get a bit annoying. Plus a new version would allow us to maybe clean other things up a bit.

(Which reminds me that I still need to add support for it to my nussjustin/resp package... meh)
