### ISSUE TITLE
FlatCmd causes panic

### ISSUE THREAD

**Issue by ollevche** [mediocregopher/radix#189]
Hi! I don't sure if it's undefined behavior or i misused the API, but here is my problem. I have a struct with a field of pointer type and this field causes panic in FlatCmd. Is it a bug?

Here is the code illustrating the problem:

```
package main

import (
	"fmt"
	"github.com/mediocregopher/radix/v3"
)

func main() {
	p, err := radix.NewPool("tcp", ":6379", 2)
	if err != nil {
		fmt.Println(err)
		return
	}

	obj := struct {
		// StrPtrField *string // uncomment this line for panic
		IntField    int
	}{
		IntField: 1,
	}

	err = p.Do(radix.FlatCmd(nil, "HMSET", "key", obj))
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

**Comment by mediocregopher** [comment]
Hi @ollevche, that code definitely should not cause a panic, and it definitely does on my machine as well. Good find, and thanks for the easy reproduction steps :) I will try to track it down in the next week.

**Comment by ollevche** [comment]
There's one more thing to mention. It's impossible to recover the panic from client side code. I guess, your code doesn't `recover()` goroutines it started, so any undiscovered bug with panic is able to shut down an entire app. Example code:

```
package main

import (
	"fmt"
	"github.com/mediocregopher/radix/v3"
)

func main() {
	p, err := radix.NewPool("tcp", ":6379", 2)
	if err != nil {
		fmt.Println(err)
		return
	}

	obj := struct {
		StrPtrField *string // uncomment this line for panic
		IntField int
	}{
		IntField: 1,
	}

	defer func() {
		if r := recover(); r != nil {
			fmt.Println("recovered panic")
		}
	}()

	err = p.Do(radix.FlatCmd(nil, "HMSET", "key", obj))
	if err != nil {
		fmt.Println(err)
		return
	}
}

```

What's your point on this? Placing `recover()` calls everywhere?
