### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by cameron-elliott** [mediocregopher/radix#193]
Hey,
I just did a topical, godocs based examination of the top three Redis for go clients, and Radix wins IMHO.

The part I that sold it for me, was the documentation on transactions,
being rusty with Redis, but needing a erase/bulk load in a transaction, the great documentation made it clear you had really thought about this, and the (short) comparison of Lua vs WithEval really helped a lot, also.

The funny thing is, for my use case, I think my transaction are better suited to WithEval  than Lua,
as I need to do a bulk load from a database, and I don't know how big that will get, so rather than a monster bulk-lua-load, I think pushing down all key sets via seperate or chunked commands is a better path.
(Don't want to be pushing down 1MB lua bulk load scripts)

Anyway, thanks for the great documentation, and package!

**Comment by mediocregopher** [comment]
Thanks for the kind words @cameron-elliott :) Just wanna double check that you mean `WithConn` and not `WithEval`, cause `WithEval` isn't a thing in this package :P 

`WithConn` for transactions definitely has a place, and I suppose bulk loading is one of those places. If speed is a concern you could some further things, like using [CLIENT REPLY](https://redis.io/commands/client-reply) to turn off responses after you've done your erase command(s), then sending your bulk loading data just using the [Conn.Encode](https://godoc.org/github.com/mediocregopher/radix#Conn) method (you can pass the `CmdAction` objects right into it, it just won't unmarshal the response, which is good cause there won't be one). Then, before `WithConn` returns, be sure to turn client replies back on.

Hope that didn't add confusion (or waste your time cause you already knew it), just an idea. In any case, thanks again for the kind words, feel free to open an issue with any questions you have :)

**Comment by mediocregopher** [comment]
Going to go ahead and close this, if you have any other questions/comments feel free to re-open it or make a new issue :)
