### ISSUE TITLE
NOAUTH Authentication required.

### ISSUE THREAD

**Issue by shyce** [mediocregopher/radix#194]
Hey @mediocregopher and contributors,

I'm trying to connect to my local sentinel stack. Connection works great, as verified by changing the password and validating that "ERR invalid password" appears.

The sentinel configuration is very stock but I've included it at the bottom, as well as my stub code that I'm trying to execute and the resultant log of being unable to set a key:

```golang
        myPassword := "myPassword"
	customConnFunc := func(network, addr string) (radix.Conn, error) {
		return radix.Dial(network, addr,
			radix.DialTimeout(10*time.Second),
			radix.DialAuthPass(myPassword),
		)
	}

	sentinel, err := radix.NewSentinel("myApp", []string{"redis-sentinel:26379"}, radix.SentinelConnFunc(customConnFunc))

	if err != nil {
		panic(err)
	}

	var testVal string
	err = sentinel.Do(radix.Cmd(nil, "SET", "test", "mykey"))

	if err != nil {
		log.Fatal("Set key: ", err)
	}

	err = sentinel.Do(radix.Cmd(&testVal, "GET", "test"))

	log.Warn(testVal)

	if err != nil {
		log.Fatal("Get key: ", err)
	}
```

```bash
FATA[0001] Set key: NOAUTH Authentication required.
```

**Settings**
_The following options are set in sentinel conf:_
requirepass myPassword
sentinel auth-pass myApp myPassword

_Options in master conf:_
appendonly yes
masterauth myPassword
requirepass myPassword
bind 0.0.0.0

_Options in slaves conf:_
appendonly yes
masterauth myPassword
requirepass myPassword
bind 0.0.0.0
slaveof redis-master 6379

**Comment by shyce** [comment]
It's not ideal, but this is what I'm doing now to get things working (please tell me if this is standard):

```golang

func keyTest(conn radix.Conn) error {
	myPassword := "myPassword"
	var testVal string
	err := conn.Do(radix.Cmd(nil, "AUTH", myPassword))
	err = conn.Do(radix.Cmd(nil, "SET", "test", "mykey."))

	if err != nil {
		log.Fatal("Set key: ", err)
	}

	err = conn.Do(radix.Cmd(&testVal, "GET", "test"))

	log.Warn(testVal)

	if err != nil {
		log.Fatal("Get key: ", err)
	}

	return nil
}

func main() {
        myPassword := "myPassword"
	sentinel, err := radix.NewSentinel("myApp", []string{"redis://:" + myPassword + "@redis-sentinel:26379"})

	if err != nil {
		panic(err)
	}

	err = sentinel.Do(radix.WithConn("myApp", keyTest))
}
```

**Comment by shyce** [comment]
I couldn't find a way to do this in the base lib, for future readers; here is my final abstraction.

Abstraction:
```golang
func withAuth(password string, actions []radix.CmdAction) func(radix.Conn) error {
	return func(conn radix.Conn) error {
		err := conn.Do(radix.Cmd(nil, "AUTH", password))
		for _, action := range actions {
			err = conn.Do(action)
			if err != nil {
				return err
			}
		}
		defer conn.Close()
		if err != nil {
			return err
		}
		return nil
	}
}
```

Usage:
```golang
var name string
var age int
setName := radix.Cmd(nil, "SET", "name", "bob")
setAge := radix.Cmd(nil, "SET", "age", "30")
getName := radix.Cmd(&name, "GET", "name")
getAge := radix.Cmd(&age, "GET", "age")

err = sentinel.Do(radix.WithConn("myApp", withAuth("myPassword", []radix.CmdAction{setName, setAge, getName, getAge})))

log.Info(name)
log.Info(age)
```

**Comment by mediocregopher** [comment]
Hi @shyce ! The problem you're having is because `SentinelConnFunc` only applies to the connection being made to the sentinel instance itself, not to the primary/secondary redis instances. You'll need to use `SentinelPoolFunc` as well so that the connection pools being made for your redis instances also use your `customConnFunc`. Something like this:

```go
myPassword := "myPassword"
customConnFunc := func(network, addr string) (radix.Conn, error) {
	return radix.Dial(network, addr,
		radix.DialTimeout(10*time.Second),
		radix.DialAuthPass(myPassword),
	)
}

customPoolFunc := func(network, addr string) (radix.Client, error) {
	return radix.NewPool(network, addr, 10, radix.PoolConnFunc(customConnFunc))
}

sentinel, err := radix.NewSentinel("myApp", []string{"redis-sentinel:26379"},
	radix.SentinelConnFunc(customConnFunc),
	radix.SentinelPoolFunc(customPoolFunc),
)
```

Hope that helps!

**Comment by shyce** [comment]
That makes sense, thanks @mediocregopher! I didn't find a lot of good examples for Sentinel in the godoc; maybe we could add a snippet?

**Comment by mediocregopher** [comment]
Yeah, an example for `NewSentinel` using both no custom funcs and using both of them might go a long way. Same with `NewCluster`.

**Comment by mediocregopher** [comment]
Doing some housekeeping, going to close this issue since it won't be relevant once v4 is out.
