### ISSUE TITLE
error:io.EOF  you can fix it

### ISSUE THREAD

**Issue by yuanshuli11** [mediocregopher/radix#200]
https://github.com/mediocregopher/radix/blob/master/pool.go#L369
if p.opts.pingInterval > 0 && size > 0 {
		p.atIntervalDo(p.opts.pingInterval, func() { p.Do(Cmd(nil, "PING")) })
}

Ping only for one conn. the ohter conns will  be closed by server。

Fix: Exec PING    using every conn in pool.

**Comment by mediocregopher** [comment]
Hello @yuanshuli11 , I haven't noticed any problems with the code as it is while using it, can you provide a test case that reproduces the problem you're seeing? While Pool will only PING one conn at a time, it does so periodically, and is configured by default such that each connection will get PING'd evey five seconds or so. You can configure that interval further using [PoolPingInterval](https://godoc.org/github.com/mediocregopher/radix#PoolPingInterval), if you would like to.

**Comment by yuanshuli11** [comment]
Oh,My pingInterval is 10*time.Minutes.
So Some EOF will happen....
Thank you!
