### ISSUE TITLE
Support for Monitor command

### ISSUE THREAD

**Issue by steve21168** [mediocregopher/radix#203]
I am wondering if the redis MONITOR command is supported and if so is there an example of how to use it?

I tried running the command with a string and it does run and return the first value of "OK".  But that value never changes.  Also tried with a slice of strings which remained an empty slice.

**Comment by mediocregopher** [comment]
Hi @steve21168 ! Radix does support MONITOR, but it requires using the [resp2](https://godoc.org/github.com/mediocregopher/radix/resp/resp2) package directly:

```go
	conn, err := radix.Dial("tcp", "localhost:6379")
	if err != nil {
		panic(err)
	}

	// Rather than `Do`-ing the command, which would write the command and read
	// the response, only write the command, and we'll read responses manually
	// in the for loop.
	if err := conn.Encode(radix.Cmd(nil, "MONITOR")); err != nil {
		panic(err)
	}

	for {
		var ss resp2.SimpleString
		if err := conn.Decode(&ss); err != nil {
			panic(err)
		}

		fmt.Printf("%q\n", ss.S)
	}
```

Hope that helps!
