### ISSUE TITLE
Non-working MaybeNil for hashmap keys

### ISSUE THREAD

**Issue by xakep666** [mediocregopher/radix#206]
Currently `MaybeNil` can't be used for non-existing hashmap keys detection. Operations like `HGETALL` always returns empty list reply `$0\r\n` which treated as non-nil response.
I have two suggestions about it:
* Add such check to `MaybeNil` - can probably break compatibility
* Add `MaybeEmpty` or extend `MaybeNil` with `IsEmpty` field

**Comment by mediocregopher** [comment]
Hello @xakep666 , is there any problem with unmarshaling into a `[]string` and checking the length? Or if all you really only need to know if the key exists or not you can use the `EXISTS` command.

**Comment by xakep666** [comment]
Approach with `[]string` works. But usage of `MaybeNil` with struct scanning requires smaller amount of code (and smaller amount of requests for approach with `EXISTS`) and looks more idiomatic.
My use-case: 
* try to `HGETALL` struct from cache
* if response is empty list - it's miss and we should perform operation than add result to cache
* if response is not empty list - it's hit and we just return scanned struct.

**Comment by mediocregopher** [comment]
Ok, I understand your use-case I think. I'd be open to adding an `EmptyArray` field to `MaybeNil`, if you'd like to add it :) The essence of the change would be to modify its `UnmarshalRESP` method to unmarshal `rm` into a `resp2.ArrayHeader` and check the header's `N` for -1 or 0, and set `MaybeNil`'s fields accordingly.
