### ISSUE TITLE
TestDialAuth fails on Redis 6

### ISSUE THREAD

**Issue by filipecosta90** [mediocregopher/radix#207]
Hi there, given that on Redis 6 AUTH can have either one or two arguments, and that when only 1 argument is passed the default user is considered, the error message is now different than the previous `"ERR Client sent AUTH, but no password is set"`. We can now have the `"ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?"`. 
To fix and be backward compatible we need to include this new error message ( if we want to really ensure error messages validation )

Current test fail on redis 6
```
$ go test ./...
--- FAIL: TestDialAuth (0.00s)
    radix_test.go:71: error "ERR Client sent AUTH..." expected, got: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct? (test:struct { url string; dialOptPass string }{url:"redis://user:myPass@127.0.0.1:6379", dialOptPass:""})
FAIL
FAIL    github.com/mediocregopher/radix/v3      29.457s
ok      github.com/mediocregopher/radix/v3/internal/bytesutil   0.062s
ok      github.com/mediocregopher/radix/v3/resp 0.033s
ok      github.com/mediocregopher/radix/v3/resp/resp2   0.004s
?       github.com/mediocregopher/radix/v3/trace        [no test files
```

**Comment by filipecosta90** [comment]
closing as I was using an old master. =)

**Comment by mediocregopher** [comment]
Glad you got it sorted out :)
