### ISSUE TITLE
"no pools available" even after cluster fully recovered.

### ISSUE THREAD

**Issue by madhukant** [mediocregopher/radix#208]
Observed issue while all the nodes of Redis cluster went down.

## Issue Details:
The issue started coming when all nodes of cluster went down.
After cluster starts recovering following sequence of error were encountered:

```
CLUSTERDOWN The cluster is down
CLUSTERDOWN Hash slot not served
no pools available
```

even after fully recovering the cluster "no pools available" didn't stop coming.

#### Redis Cluster
- No. of Nodes : 9
- No. of Replica : 2

#### Golang 
golang version 1.12.9 using go module style setup

##### Bringing Redis Cluster UP:
```
- git clone https://github.com/madhukant/redis-cluster-docker.git
```

```
- cd redis-cluster-docker/redis
```

```
- docker image build -t redis-cluster-node .
```

```
- cd ..
```

```
- docker-compose up -d
```

```
- docker exec -it redis-cluster-docker_redis-1_1 redis-cli -p 7001 --cluster create 10.0.0.11:7001 10.0.0.12:7002 10.0.0.13:7003 10.0.0.14:7004 10.0.0.15:7005 10.0.0.16:7006 10.0.0.17:7007 10.0.0.18:7008 10.0.0.19:7009 --cluster-replicas 2 --cluster-yes
```

### Start Go program:

- Sample Program Repo - ```git clone https://github.com/madhukant/radixTestingGolang.git```
- Build and start using - ```./goredis -address=localhost:7001```

### Wait for 3-5 sec to set/get some keys and then bring DOWN redis cluster

- ```docker-compose down```

### Observation and Bringing UP Cluster setup:

- First you will see "EOF" and then "i/o timeout"
- as soon as i/o timeout encountered bring UP cluster using -

```
- docker-compose up -d
```

> #### Wait for sometime after bringing up all the nodes using above command. yet the cluster is not ready. we need to create cluster using all the 9 nodes using below command.

> #### Wait for some time between bring up the nodes and creating cluster (As per real world scenario, it didn't happened at the same time). In between this steps go program will start giving "no pools available" error.

```
- docker exec -it redis-cluster-docker_redis-1_1 redis-cli -p 7001 --cluster create 10.0.0.11:7001 10.0.0.12:7002 10.0.0.13:7003 10.0.0.14:7004 10.0.0.15:7005 10.0.0.16:7006 10.0.0.17:7007 10.0.0.18:7008 10.0.0.19:7009 --cluster-replicas 2 --cluster-yes
```

**Comment by mediocregopher** [comment]
Thank you for the super detailed repro steps, very much appreciated :) I'll check it out this evening and see what I can see.

**Comment by madhukant** [comment]
while debugging I found that the Sync depends on pools array to be filled in.
#### (c *Cluster) Sync() Call No. 1:
when it goes to get topology from cluster swarm from function "(c *Cluster) getTopo" it returns
```
tt == []
err == nil
```

This happens between "nodes came up" and "cluster yet not created" ( means master/slave arrangement yet not created on redis server).

At that time topology didn't exist and though it goes to below piece of code:
c.pools is having all the previous connection but got deleted as tm is empty.

```
		tm := tt.Map()
		for addr, p := range c.pools {
			if _, ok := tm[addr]; !ok {
				toclose = append(toclose, p)
				delete(c.pools, addr)
			}
		}
```

#### (c *Cluster) Sync() Call No. 2:
Now next "(c *Cluster) Do" comes and it goes to "c.doInner". Over there while calling c.pool error starts coming as "no pools available".

Ideally everything is correct till now. It should correct (update with new topology and start executing new commands) itself just after next Sync call. But pool never get filled with new topology after many Sync calls. This happens due to 'c.pool(**""**)' is being called from "(c *Cluster) Sync()".

**Comment by madhukant** [comment]
Fixed and this has been tested. @mediocregopher Thank you.
