### ISSUE TITLE
RESP3

### ISSUE THREAD

**Issue by undefined7887** [mediocregopher/radix#210]
Hey everyone! Redis 6.0 is out, any plans for implementing RESP3 protocol?

**Comment by mediocregopher** [comment]
Yes, it's planned to be included in `radix/v4`, which I would like to start working on soon, but there's some other projects I need to finish up first. I'll go ahead and write up a an issue now for that, though, so we can start getting feedback on other changes people would like to see.

**Comment by mediocregopher** [comment]
Moving RESP3 discussion to #212, thanks for the motivation :)
