### ISSUE TITLE
Benchmark against https://github.com/go-redis/redis

### ISSUE THREAD

**Issue by letientai299** [mediocregopher/radix#215]
I'm just curious about performance different compare to `go-redis`, which is quite popular.

**Comment by mediocregopher** [comment]
Hello @letientai299 , there's actually a PR open for adding go-redis benchmarks, #134, I just never got the chance to run them. It hasn't been high on my list of priorities, but if someone else wanted to take a shot at it that'd be great :)

**Comment by mediocregopher** [comment]
I cherry-picked that PR onto the v4 branch of this project, so go-redis will be included in the benchmarks once I get around to properly running them.
