### ISSUE TITLE
BenchmarkParallelGetSet redigo missconfig

### ISSUE THREAD

**Issue by bogdanciuca** [mediocregopher/radix#221]
Hi,

I was looking through the benchmarks and noticed a huge difference for `redigo` (-50% performance) when pipelining (see [code](https://github.com/mediocregopher/radix/blob/master/bench/bench_test.go#L243)).

Going through the code, it looks like there's no pipelining involved (see [docs](https://godoc.org/github.com/gomodule/redigo/redis#hdr-Pipelining)). 

Therefore I've opened a [PR](https://github.com/mediocregopher/radix/pull/220). Thanks!

**Comment by mediocregopher** [comment]
Closing, see my comment in the PR.
