### ISSUE TITLE
Do Pipeline Cmd got panic from `MarshalRESP `

### ISSUE THREAD

**Issue by wsc-sky** [mediocregopher/radix#226]
panic: runtime error: index out of range [1] with length 1

goroutine 9730 [running]:
github.com/mediocregopher/radix/v3.(*cmdAction).MarshalRESP(0xc304e79420, 0x2d14d40, 0xc2fc01c900, 0x0, 0x0)
/root/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.2/action.go:263 +0x182
github.com/mediocregopher/radix/v3.pipeline.MarshalRESP(0xc30083ca00, 0x8, 0x28, 0x2d14d40, 0xc2fc01c900, 0x2030c3, 0x8)
/root/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.2/action.go:499 +0x72
github.com/mediocregopher/radix/v3.(*connWrap).Encode(0xc2fc874640, 0x2d18280, 0xc30e35c340, 0x41078d, 0x20)
/root/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.2/conn.go:86 +0x4f
github.com/mediocregopher/radix/v3.(*ioErrConn).Encode(0xc2fc874660, 0x2d18280, 0xc30e35c340, 0xc30e35c340, 0x2030c3)
/root/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.2/pool.go:41 +0x5c
github.com/mediocregopher/radix/v3.pipeline.Run(0xc30083ca00, 0x8, 0x28, 0x2d8a7c0, 0xc2fc874660, 0x2458dd14, 0xe4ea2dd0280e4)
/root/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.2/action.go:450 +0x79
github.com/mediocregopher/radix/v3.(*ioErrConn).Do(...)
/root/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.2/pool.go:62
github.com/mediocregopher/radix/v3.(*Pool).Do(0xc001ad4600, 0x2d4a680, 0xc30e35c320, 0xc30e35c320, 0x2d92060)
/root/go/pkg/mod/github.com/mediocregopher/radix/v3@v3.5.2/pool.go:591 +0xef
git.garena.com/shopee/deep/paidads-recall/flash.(*worker).workGetFromRemote(0xc00841c3c0, 0xc30a10af00)
/root/go/src/git.garena.com/shopee/deep/paidads-recall/flash/worker.go:75 +0x330
git.garena.com/shopee/deep/paidads-recall/flash.(*worker).work(0xc00841c3c0)
/root/go/src/git.garena.com/shopee/deep/paidads-recall/flash/worker.go:33 +0xee

My usage code: 
bsArr = make([][]radix.CmdAction, num)
for ...{
  cmds[j] = append(cmds[j], radix.Cmd(&(bsArr[i]), "GET", localKey))
}
for ...{
  redisPools[i].Do(radix.Pipeline(cmds[i]...)), and there is no duplicated cmd in cmds
}
In my scenario, I init multiple pools for different redis servers, and will call redisPool.Do() concurrently.

**Comment by nussjustin** [comment]
The panic happens here:

https://github.com/mediocregopher/radix/blob/v3.5.2/action.go#L263

The only index access is the `c.args[i]` which shouldn't fail since `i` is an index returned by `range` over `c.args`. This sounds like a race condition.

Have you tried running your code with `-race`? `CmdAction`s can only be used once and only by one client. Have you checked that you are not using any `CmdAction`s multiple times?

**Comment by wsc-sky** [comment]
Hi, 
I checked my code, there is a retry mechanism which will reuse CmdActions, thank you very much for your help ! I will close this issue .
