### ISSUE TITLE
Got abnormal unicode bytes when using Pipeline

### ISSUE THREAD

**Issue by wsc-sky** [mediocregopher/radix#227]
This this how I used the lib:
```
bytesArr := make([][]byte, n)
for i := range bytesArr {
  bytesArr[i] = syncPool.Get().(byte)[:0]
}
p := radix.Pipeline(
	radix.Cmd(&(bytesArr[0]), "GET", "key1"),
	radix.Cmd(&(bytesArr[1]),  "GET", "key2"),
       .....
)
for i := range bytesArr {
  err := proto.Unmarshal(bytesArr[i], targetStrct)

  syncPool.Put(bytesArr[i])
}
```
example bytes I got:
```
"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000 ....\u0000\u0000\u0000\u0000"
```

My value in redis is the bytes which is marshal by protobuf, but sometime I got bytesArr in unicode format, which may cause my proto unmarshal failed, can anyone give me some hints for this problem?

**Comment by nussjustin** [comment]
How are you using the values? All your code shows is how you take them from a pool, read into them and then pool them again. The string you showed contains just a bunch of 0-bytes (which is why they are encoded using unicode escape sequences, since a 0 byte would otherwise be invisible).

**Comment by wsc-sky** [comment]
I will Unmarshal these byte arrays into protobuf structures. Ok, I got that why it shown as unicode, so I how can I know when radix lib will give me the broken byte array ? For example, when I use radix.Pipeline, can I get the error or status for each command ?

**Comment by nussjustin** [comment]
How are you executing the pipeline? If there is an error it will be returned by the call to `(Client).Do(p)`, but your code snippet does not show how you call this. Did you make sure to check the error?

**Comment by wsc-sky** [comment]
Hi, I did check the error from (Client).Do(p), the error is nil, but sometime the bytes I got from the redis are broken.

**Comment by nussjustin** [comment]
Have you run your code with the race detector enabled? Have you tried allocating fresh slices instead of using a pool? (When compiling with race detector enabled sync.Pool should always return nil IIRC)

**Comment by mediocregopher** [comment]
@wsc-sky this appears to be a dead issue so I'm going to close it. Please feel free to re-open it if you're still having this issue (but also please answer justin's questions first :) )
