### ISSUE TITLE
Support connection to redis over the unix socket. 

### ISSUE THREAD

**Issue by dpipemazo** [mediocregopher/radix#231]
Hello! Redis can [accept connections over the unix socket](https://redis.io/topics/clients) and this is actually something we do quite typically at Elementary Robotics since we run redis on the edge as the primary data bus for our robots. We're currently using Redis Time Series + Grafana and were hoping to get the ability for their Grafana plugin (which uses this redis client) to connect to the redis datasource over the unix socket as it simplifies things a bit for us and marginally improves performace.

My original issue for this was filed on the [grafana redis datasource](https://github.com/RedisTimeSeries/grafana-redis-datasource/issues/58).

Would it be possible to add support for connecting to redis via the unix socket?

Thanks for taking a look!

**Comment by mediocregopher** [comment]
Hello @dpipemazo ! While it's not a use-case I use frequently (or ever, tbh), as far as I know this driver should already support unix sockets. Both [Dial](https://pkg.go.dev/github.com/mediocregopher/radix/v3?tab=doc#Dial) and [NewPool](https://pkg.go.dev/github.com/mediocregopher/radix/v3?tab=doc#NewPool) take in a network and address parameter which end up getting sent down to `net.Dial`. Can you show how you're trying to use unix sockets and how it's failing?

**Comment by mediocregopher** [comment]
I did a bit of digging out of interest, I think [this](https://github.com/RedisTimeSeries/grafana-redis-datasource/blob/master/pkg/datasource.go#L211) is the starting point of whatever changes are going to be needed. radix doesn't easily support unix sockets for sentinel or cluster (though with some custom ConnFuncs it could be done, but it doesn't really make sense to). For a pool connected to a single instance it should be fine though.

**Comment by mikhailredis** [comment]
@mediocregopher When I googled, I can't find anything regarding Unix sockets and Radix like you said.
`Radix.Dial` should work with "unix" and I am going to try it now:
```
conn, err = radix.Dial("unix", socket)
```
Thank you.

**Comment by dpipemazo** [comment]
Thank you for the quick reply! Sure -- I'm setting it in the "Add Datasource" settings of the [Redis Grafana Plugin](https://github.com/RedisTimeSeries/grafana-redis-datasource/issues/58). It seems to be returning an error of:
```
getinstance error: dial tcp: address /shared/metrics.sock: missing port in address
```

Screenshot below
![Screenshot from 2020-08-27 20-00-02](https://user-images.githubusercontent.com/2764032/91516425-4cda2e80-e8a0-11ea-8b74-da3f09280d23.png)

This agrees well with what you found. I did find [these docs on dial](https://golang.org/pkg/net/#Dial) that suggest if used with "unix" a standard filesystem path should suffice.

**Comment by dpipemazo** [comment]
We were able to get this working -- thanks for the tip!
