### ISSUE TITLE
Will the connection to the pool or cluster be auto recovered

### ISSUE THREAD

**Issue by huanwu** [mediocregopher/radix#233]
I have a question. I am implementing a radix client as the following code to support both instance or cluster mode (either return a Pool from radix.NewPool or a cluster from radix.NewCluster). Then call radixClient.Do(...). My question is if the connection to the redis is disconnected in the middle either network issue or reploy the redis, will the connection be auto recovered after that? What's the behavior during the disconnection. Thanks!

func NewRadixClient() (radix.Client, error) {
	customConnFunc := func(network, addr string) (radix.Conn, error) {
		var conn radix.Conn
		var err error
		conn, err = radix.Dial(network, addr,
			radix.DialTimeout(1*time.Minute),
			radix.DialAuthPass(""),
		)

		if err != nil {
			fmt.Println("error in conn")
			return nil, err
		}

		return conn, nil
	}

	poolFunc := func(network, addr string) (radix.Client, error) {
		var pool radix.Client
		var err error
		pool, err = radix.NewPool(network, addr, 6, radix.PoolConnFunc(customConnFunc))
		if err != nil {
			fmt.Println("error in pool function")
			return nil, err
		}

		return pool, nil
	}

	clusterFunc := func(addr string) (radix.Client, error) {
		var cluster radix.Client
		var err error
		cluster, err = radix.NewCluster([]string{"127.0.0.1:30001", "127.0.0.1:30002"},
			radix.ClusterPoolFunc(poolFunc))

		if err != nil {
			fmt.Println("error when create cluster")
			return nil, err
		}

		return cluster, nil
	}

	return clusterFunc("127.0.0.1:30001")
}

radixClient, _ := NewRadixClient()
radixClient.Do(...)

**Comment by mediocregopher** [comment]
Hello @huanwu , broken connections will be recreated after the `Do` has been called. If the connection disconnects in the middle of `Do` then that action will see an error, but the connection will still get recreated later for subsequent actions. Hope that helps!

**Comment by huanwu** [comment]
Thanks for the confirmation!
