### ISSUE TITLE
panic error when unmarshal failed

### ISSUE THREAD

**Issue by Kuri-su** [mediocregopher/radix#236]
* Go version: ` go1.13.12 linux/amd64`
* OS: `Ubuntu 20.04`
* pkgVersion: `github.com/mediocregopher/radix/v3 v3.5.2`

---

if i run this code , it will be panic

```go
package main

import (
	"encoding/json"
	"fmt"
	"github.com/mediocregopher/radix/v3"
)

func main() {
	var err error
	Key := "hGet2-0"
	hashKey := "xxa"
	hashValue := map[string]string{
		"xx": "11",
	}
	hashValueStr, err := json.Marshal(hashValue)
	if err != nil {
		panic(err)
	}

	// ====== begin in here ======

	db, err := radix.NewPool("tcp", "127.0.0.1:6379", 1, nil)
	if err != nil {
		panic(err)
	}

	if err = db.Do(radix.Cmd(nil, "HSET", Key, hashKey, string(hashValueStr))); err != nil {
		panic(err)
	}

	var a = map[string]string{}
	if err = db.Do(radix.Cmd(&a, "HGET", Key, hashKey)); err != nil {
		panic(err)
	}

	fmt.Println(a)
	fmt.Println(hashValue)
}
```

it will say 

```
panic: can't unmarshal into *map[string]string, message body was: "{\"xx\":\"11\"}"
```

please take a look, thx :)

> thank you and your hard work :+1:

**Comment by nussjustin** [comment]
radix does not support unmarshalling specific encodings like JSON from a command. radix will only unmarshal the RESP encoded messages returned by Redis. In your case redis returns a bulk string which radix can then decode into a normal Go string, but that's about it. radix doesn't care about what the bulk string contains.

If you want to directly unmarshal JSON you will have to create a custom `resp.Unmarshaler` that decodes the JSON and then pass this unmarshaler to `radix.Cmd`.

**Comment by Kuri-su** [comment]
> radix does not support unmarshalling specific encodings like JSON from a command. radix will only unmarshal the RESP encoded messages returned by Redis. In your case redis returns a bulk string which radix can then decode into a normal Go string or, depending on the type of the receiver, e.g. a number, but that's about it. radix doesn't care about what the bulk string contains.
> 
> If you want to directly unmarshal JSON you will have to create a custom `resp.Unmarshaler` that decodes the JSON and then pass this unmarshaler to `radix.Cmd`.

cool, let me try about this XD

**Comment by nussjustin** [comment]
Something like this should work (not tested):

```go
type MyAwesomeUnmarshaler struct {
	I interface{}
}

func (mau *MyAwesomeUnmarshaler) UnmarshalRESP(br *bufio.Reader) error {
	var b resp2.BulkStringBytes
	if err := b.UnmarshalRESP(br); err != nil {
		return err
	}
	return json.Unmarshal(b.B, mau.I)
}
```

Basically you just unmarshal the RESP string into bytes using `resp2.BulkStringBytes` and then call `json.Unmarshal` on the result. To use the custom unmarshaler you just call `radix.Cmd` like this:

```go
radix.Cmd(MyCustomUnmarshaler{&a}, "HGET", Key, hashKey)
```

**Comment by Kuri-su** [comment]
> Something like this should work (not tested):
> 
> ```go
> type MyAwesomeUnmarshaler struct {
> 	I interface{}
> }
> 
> func (mau *MyAwesomeUnmarshaler) UnmarshalRESP(br *bufio.Reader) error {
> 	var b resp2.BulkStringBytes
> 	if err := b.UnmarshalRESP(br); err != nil {
> 		return err
> 	}
> 	return json.Unmarshal(b.B, mau.I)
> }
> ```
> 
> Basically you just unmarshal the RESP string into bytes using `resp2.BulkStringBytes` and then call `json.Unmarshal` on the result. To use the custom unmarshaler you just call `radix.Cmd` like this:
> 
> ```go
> radix.Cmd(MyCustomUnmarshaler{&a}, "HGET", Key, hashKey)
> ```

ok , i writed a simple unmarsheler like this ,I started trying to transform it into this

```go
func (c *RedisV2) Unmarshal2Value(res string, v interface{}) error {
	if res == "" {
		return nil
	}

	switch typeValue := v.(type) {
	case *string:
		*typeValue = res
	case *interface{}:
		*typeValue = res
	default:
		err := jsoniter.UnmarshalFromString(res, v)
		if err != nil {
			return errors.Trace(err)
		}
	}

	return nil
}
```



Thank you for your patience :) :+1:

**Comment by mediocregopher** [comment]
To add on, radix also supports unmarshaling bulk strings into [TextUnmarshalers](https://golang.org/pkg/encoding/#TextUnmarshaler) and [BinaryUnmarshalers](https://golang.org/pkg/encoding/#BinaryUnmarshaler), so if your receiver type were to implement an `UnmarshalText(text []byte) error` method that would also work. It can be a bit tricky with the json unmarshaler, because that will also treat TextUnmarshalers specially, but it can be made to work with something like:

```go
type jsonUnmarshaler struct {
    i interface{}
}

func (ju *jsonUnmarshaler) UnmarshalText(b []byte) error {
    return json.Unmarshal(ju.i)
}

// to actually use it:
var m map[string]string
err := db.Do(radix.Cmd(jsonUnmarshaler{&m}, "HGET", Key, hashKey))
```

(I didn't actually test it, but something like that should work)
