### ISSUE TITLE
Radix v3 random test results

### ISSUE THREAD

**Issue by flaviuvadan** [mediocregopher/radix#237]
I am currently using `github.com/mediocregopher/radix/v3` for interfacing with Redis. In the unit tests I have written, I am performing multiple actions sequentially, such as getting a record, altering it, and getting it again to check results. However, at random, tests will fail because of assertions for the 3rd step, which checks that a record was actually altered. I am adding a sample implementation with comments in place of code that is not relevant:

Function called in test:
```Golang
func (r *whateverStruct) SetField(ctx context.Context, ID, field, value string) error {
	// do some validation to make sure ID exists...

	if err := r.connPool.Do(radix.Cmd(nil, utils.WATCH, ID)); err != nil {
		return newError( "SetField failed to watch %s, err: %s", ID, err)
	}

	// WATCH actions have to be followed up with an UNWATCH so that the fields can be modified by other requests
	// note that EXEC actions also perform UNWATCH
	unwatchRequired := true
	defer func() {
		if unwatchRequired {
			if err := r.connPool.Do(radix.Cmd(nil, utils.UNWATCH)); err != nil {
				logging.Errorf(ctx, "Delete failed to perform UNWATCH on %s, err: %s", ID, err)
			}
		}
	}()

	if err := r.connPool.Do(radix.WithConn(ID, func(conn radix.Conn) error {
		if err := conn.Do(radix.Cmd(nil, utils.MULTI)); err != nil {
			return err
		}

		// if any of the calls after the MULTI call error it's important that the transaction is discarded. This isn't strictly necessary if the
		// error was a network error, as the connection would be closed by the client anyway, but it's important otherwise
		var err error
		defer func() {
			if err != nil {
				// the return from DISCARD doesn't matter. If it's an error then it's a network error and the Conn will be closed by the client
				_ = conn.Do(radix.Cmd(nil, utils.DISCARD))
			}
		}()

		if err = conn.Do(radix.Cmd(nil, utils.HSET, ID, field, value)); err != nil {
			return err
		}

		if err = conn.Do(radix.Cmd(nil, utils.EXEC)); err != nil {
			return err
		}

		return nil
	})); err != nil {
		return err
	}

	unwatchRequired = false
	return nil
}
```

Actual test:
```Golang
SetFieldTestSuite struct {
	suite.Suite

	miniRedis *miniredis.Miniredis
	connPool  *radix.Pool
        repo      Repository
}

func (s *SetFieldTestSuite) SetupTest() {
	if mr, err := miniredis.Run(); err != nil {
		log.Fatalf("failed to start miniredis, err: %s", err)
	} else {
		s.miniRedis = mr
	}

	if cp, err := radix.NewPool("tcp", s.miniRedis.Addr(), 50); err != nil {
		log.Fatalf("failed to create connection pool, err: %s", err)
	} else {
		s.connPool = cp
	}

	s.repo = New(s.connPool)
}

func (s *SetFieldTestSuite) TearDownTest() {
	_ = s.connPool.Close()
	s.miniRedis.Close()
}

func (s *SetFieldTestSuite) TestWorksAsExpected() {
	ctx := context.Background()
	ID := randStringOfLength(32)
	record := &v1.Record{
		Id:     ID,
                 Field: "42",
	}
	createErr := s.repo.Create(ctx, record) // this Create uses HMSET for multiple fields, implemented similar to above
	s.Nil(createErr) // this is nil in tests i.e never fails

	setErr := s.repo.SetField(ctx, ID, "field", "100")
	s.Nil(setErr) // this is nil in the tests i.e never fails

	record, getErr := s.repo.Get(ctx, ID)
	s.Nil(getErr) // this succeeds too!

	s.Equal(ID, record.ID)  // this is ok, works fine
        s.Equal("100", record.Field)  // THIS _SOMETIMES_ ERRORS OUT
}
```

The test uses [MiniRedis](https://github.com/alicebob/miniredis) as the Redis instance. 

The problem I have is `s.Equal` (inherits from `suite.Suite`) sometimes succeeds, but sometimes fails. The successful case is when the field was indeed updated, while the failing case is due to the field not being updated. Interestingly, adding a `time.Sleep(1 * time.Second)`, or `s.miniRedis.FastForward(1 * time.Second)` does not help (I thought it might because of some potential thread still running in the background). Surprisingly, adding print statements between the calls for `Set` and `Get` makes the test pass - always (so far). 

Any thoughts on why this might be the case? Could this be related to Radix, or MiniRedis?

**Comment by flaviuvadan** [comment]
I think the issue is that the `WATCH` command is executed outside of the transaction. The `WithConn` documentation clearly outlines: 
```Golang
// NOTE that WithConn only ensures all inner Actions are performed on the same
// Conn, it doesn't make them transactional. Use MULTI/WATCH/EXEC within a
// WithConn for transactions, or use EvalScript
```

**Comment by mediocregopher** [comment]
Hi @flaviuvadan , I think the issue is that your WATCH statement is not happening within the WithConn callback. Everytime `Do` is called on a Pool it's probably going to run the action on a different Conn than the previous `Do` call. So you're calling WATCH on one Conn, and then doing the rest of your transaction on a different Conn. Can you try moving the WATCH inside the WithConn and see if that works?

**Comment by flaviuvadan** [comment]
> Hi @flaviuvadan , I think the issue is that your WATCH statement is not happening within the WithConn callback. Everytime `Do` is called on a Pool it's probably going to run the action on a different Conn than the previous `Do` call. So you're calling WATCH on one Conn, and then doing the rest of your transaction on a different Conn. Can you try moving the WATCH inside the WithConn and see if that works?

Thanks for the response @mediocregopher! I made that exact change and it fixed all the issues I was seeing. Going to close the issue.
