### ISSUE TITLE
New tag for v3

### ISSUE THREAD

**Issue by baranovoleg** [mediocregopher/radix#238]
Hi @mediocregopher 

Could you please create a new tag for v3 which includes this [PR?](https://github.com/mediocregopher/radix/pull/230)
Thanks a lot!

**Comment by mediocregopher** [comment]
Hi @baranovoleg , just merged some changes i've been wanting to put in and tagged `v3.6.0`, let me know how that works

**Comment by baranovoleg** [comment]
Now it's work fine fo me. Adding background calls Ping() for triggering refresh() on temporary dead connections works good.
Thanks!
