### ISSUE TITLE
Support for pipeline in cluster mode

### ISSUE THREAD

**Issue by larryzhu2018** [mediocregopher/radix#242]
I read the past issues before submitting the PR. Brian closed the PR before discussing the issues and fixes.
https://github.com/mediocregopher/radix/pull/241

My suggestion in the PR description  should have addressed the past issues

**Comment by mediocregopher** [comment]
I'll just import your last comment from the PR here and we can go off that:

> these are local operations with regarding to rlock, right?

Yes they are, but for any significantly sized set of keys all those rlocks are going to add up, I wouldn't want that to be the implementation used by the library.

> can you tell me how do you do that? basically I would like to group the keys for the same server. you cannot use key slots to group as that would be too many groups and not enough message to make the pipeline meaningful

Basically you'll have some code like this:

```go
topo := cluster.Topo().Primaries()

addrForKey := func(key string) string {
	for _, t := range topo {
		for _, slot := range t.Slots {
			if s >= slot[0] && s < slot[1] {
				return t.Addr
			}
		}
	}
	panic(fmt.Sprintf("no slot for key %q", key))
}

keysByAddr := map[string][]string{}
for _, key := range keys {
	addr := addrForKey(key)
	keysByAddr[addr] = append(keysByAddr[addr], key)
}

for addr, keys := range keysByAddr {
	client, err := cluster.Client(addr)
	if err != nil {
		// cluster topology has likely changed since Topo was called, decide
		// what to do.
		panic("TODO")
	}

	err := client.Do(
		// something with keys
	)
}
```

You can see `addrForKeys` has been copied out but it's working directly off the topo instance instead of being called on cluster, so it's not incurring that rlock for every key.

**Comment by larryzhu2018** [comment]
> I'll just import your last comment from the PR here and we can go off that:
> 
> > these are local operations with regarding to rlock, right?
> 
> Yes they are, but for any significantly sized set of keys all those rlocks are going to add up, I wouldn't want that to be the implementation used by the library.
> 
> > can you tell me how do you do that? basically I would like to group the keys for the same server. you cannot use key slots to group as that would be too many groups and not enough message to make the pipeline meaningful
> 
> Basically you'll have some code like this:
> 
> ```go
> topo := cluster.Topo().Primaries()
> 
> addrForKey := func(key string) string {
> 	for _, t := range topo {
> 		for _, slot := range t.Slots {
> 			if s >= slot[0] && s < slot[1] {
> 				return t.Addr
> 			}
> 		}
> 	}
> 	panic(fmt.Sprintf("no slot for key %q", key))
> }
> 
> keysByAddr := map[string][]string{}
> for _, key := range keys {
> 	addr := addrForKey(key)
> 	keysByAddr[addr] = append(keysByAddr[addr], key)
> }
> 
> for addr, keys := range keysByAddr {
> 	client, err := cluster.Client(addr)
> 	if err != nil {
> 		// cluster topology has likely changed since Topo was called, decide
> 		// what to do.
> 		panic("TODO")
> 	}
> 
> 	err := client.Do(
> 		// something with keys
> 	)
> }
> ```
> 
> You can see `addrForKeys` has been copied out but it's working directly off the topo instance instead of being called on cluster, so it's not incurring that rlock for every key.
this is a better solution then. thanks for the pointers. 
This means to support pipeline we only need to make one change instead of two - we just need to change the check for the same key slot to check for  the same key server, right?

**Comment by mediocregopher** [comment]
> This means to support pipeline we only need to make one change instead of two - we just need to change the check for the same key slot to check for the same key server, right?

To handle that I recommend overwriting the `Keys` method of the `Pipeline` so that it only returns a single key from the set. That way there's no changes needed within radix at all :)

**Comment by larryzhu2018** [comment]
what is the reason for checking for the same key slot instead of just checking the key server?

And also can you give more details how to overwrite the keys to give a single key? Do you mean hash tag? What would be a good algorithm so that I can spread loads evenly to the redis servers. 

I have battle tested the changes in the PR with about 6 billion keys on a 62-node redis cluster for about 3-4 months.

**Comment by mediocregopher** [comment]
> what is the reason for checking for the same key slot instead of just checking the key server?

The behavior mimics the restrictions enforced by redis itself. For example MULTI/EXEC and EVAL will not accept transactions which modify keys belonging to different slots, even if the slots are on the same host. We do the same check for Pipeline, and all actions in radix, as a speedbump, so people realize the hazards of them doing so.

> And also can you give more details how to overwrite the keys to give a single key? Do you mean hash tag? What would be a good algorithm so that I can spread loads evenly to the redis servers.

I mean to overwrite the `Keys` method of pipeline by wrapping it in an outer type. Basically this:

```go
type actionFirstKey struct {
    Action
}

func (a actionFirstKey) Keys() []string {
    return a.Action.Keys()[:1]
}

// then to use it
pipe := radix.Pipeline(cmd1, cmd2)
err := cluster.Do(actionFirstKey{pipe})
```

**Comment by larryzhu2018** [comment]
hi Brian, can you please expand this and explain? Where is Keys() referenced? Why this override works? I do not see the dots connected.

**Comment by mediocregopher** [comment]
`Keys` is one of the methods of the `Action` interface, which is passed into the `Do` method. It is used by Cluster to determine which keys an action is modifying, so that it can direct the action to the correct node in the cluster. By overriding `Keys` you're essentially lying to Cluster about which keys are involved in the action (the action being Pipeline).

**Comment by larryzhu2018** [comment]
How does this work if  the pipeline checks if the keys from the pipeline execution are for the same key lot? Or are you saying by overriding keys(), it won't check if the keys are targeting the same slot for the same pipeline execution?

**Comment by mediocregopher** [comment]
Pipeline doesn't check whether the keys are from the same slot, Cluster is what does that. So yeah, by overriding `Keys` you're tricking Cluster into not being able to make that check properly.

**Comment by mediocregopher** [comment]
Closing this issue for now, please feel free to re-open if you'd like to discuss further.
