### ISSUE TITLE
Reading unacknowledged entries from a stream and switching to new ones

### ISSUE THREAD

**Issue by ollevche** [mediocregopher/radix#243]
Hello!

Thanks for the `StreamReader`. It helps a lot!

I'm building a service that reads entry (1), runs some processing logic (2), acknowledges read (3), and then repeats from the first step. I want it to read history (unacknowledged entries) on startup and then switch to reading new entries. 

[Streams Intro from Redis](https://redis.io/topics/streams-intro) provides an example in Ruby for that use-case. Is that possible with the current implementation of `StreamReader`?

It would be helpful to set some `StreamReader's` flag for switching to `>` id in case of no entries available by an existing id.

Here is the example in Ruby:

```
require 'redis'

if ARGV.length == 0
    puts "Please specify a consumer name"
    exit 1
end

ConsumerName = ARGV[0]
GroupName = "mygroup"
r = Redis.new

def process_message(id,msg)
    puts "[#{ConsumerName}] #{id} = #{msg.inspect}"
end

$lastid = '0-0'

puts "Consumer #{ConsumerName} starting..."
check_backlog = true
while true
    # Pick the ID based on the iteration: the first time we want to
    # read our pending messages, in case we crashed and are recovering.
    # Once we consumed our history, we can start getting new messages.
    if check_backlog
        myid = $lastid
    else
        myid = '>'
    end

    items = r.xreadgroup('GROUP',GroupName,ConsumerName,'BLOCK','2000','COUNT','10','STREAMS',:my_stream_key,myid)

    if items == nil
        puts "Timeout!"
        next
    end

    # If we receive an empty reply, it means we were consuming our history
    # and that the history is now empty. Let's start to consume new messages.
    check_backlog = false if items[0][1].length == 0

    items[0][1].each{|i|
        id,fields = i

        # Process the message
        process_message(id,fields)

        # Acknowledge the message as processed
        r.xack(:my_stream_key,GroupName,id)

        $lastid = id
    }
end
```

**Comment by mediocregopher** [comment]
Hello @ollevche , yes this is easily possible with radix. In the `Streams` field given to `StreamReaderOpts` simply pass `nil` as the map value for the stream, and it will use `>` for the id given to XREADGROUP. You can see that happening [here](https://github.com/mediocregopher/radix/blob/v3.6.0/stream.go#L317). Hope that helps!

**Comment by ollevche** [comment]
@mediocregopher that's okay in case of just reading new messages. I want to read pending messages first by specifying `0-0` id and then switch to the special `>` id. 

Seems like a single `StreamReader` can be used to read either by an exact id (i.e. `0-0`) or by the special one (`>`), but not both. Did i get it right?

**Comment by mediocregopher** [comment]
Ah, I misunderstood you're original message, sorry. Yes you have it right, you need to read from the `0-0` one until it yields no more results (use `NoBlock: true`), then switch to the `>` reader.

> It would be helpful to set some StreamReader's flag for switching to > id in case of no entries available by an existing id.

PRs are open :)
