### ISSUE TITLE
Automatically calling cluster secondaries

### ISSUE THREAD

**Issue by kollektiv** [mediocregopher/radix#249]
Hello, what are your thoughts on adding an option to the cluster client to automatically route readonly commands to the secondaries?

The output of [`COMMAND`](https://redis.io/commands/command) could be cached, and the cluster's `Do` could internally call `DoSecondary` if the command is readonly

**Comment by mediocregopher** [comment]
Hi @kollektiv , I don't think such an option should be added to radix unfortunately. It would add quite a bit of extra work behind the scenes of Cluster to make it work, and I'm not aware that enough people are requesting such a feature for it to be worthwhile. It sounds like something you could write as a wrapper around Cluster and make available to others though :)

If you haven't already checked out [v4](https://pkg.go.dev/github.com/mediocregopher/radix/v4#section-documentation) (still in beta, but fairly stable), there's a MultiClient interface there which wraps both Cluster and Sentinel, which might be cleaner if you're writing a wrapper around Cluster. Just a thought.

Sorry for the bad news, but feel free to submit any other ideas or bugs you come across :)

**Comment by kollektiv** [comment]
Thanks for the reply. I will look into making my own wrapper
