### ISSUE TITLE
When receiver has type of &interface{} redis error (prefix "-") causes panic("should never get here") in radix/v3

### ISSUE THREAD

**Issue by santriseus** [mediocregopher/radix#250]
Hi, I could see that issue described is fixed using the commit https://github.com/mediocregopher/radix/commit/0f326e0674c235a6054778c30cfd53c50b72e25c but looks like this change is missed in the latest version 3.6.0

**Comment by mediocregopher** [comment]
Hi @santriseus , I just pushed a new tag for `v3.7.0` which has that fix. Cheers!
