### ISSUE TITLE
Automatic grouping of actions into pipelines for clustered clients

### ISSUE THREAD

**Issue by kollektiv** [mediocregopher/radix#251]
Related to https://github.com/mediocregopher/radix/issues/88 and https://github.com/mediocregopher/radix/issues/45

Hello, I am curious what your thoughts are for grouping a `radix.Action` into a `radix.Pipeline` by cluster node,
for use cases such calling GET on 100 keys against a cluster client in a performant manner. 

The API could look something like this
```go
type ClusterClient interface {
  DoActions(ctx context.Context, actions ...Action) error
  DoSecondaryActions(ctx context.Context, actions ...Action) error
}
```

I image this would be useful to be able to pass in an arbitrary number of `radix.Action`s (Cmd or FlatCmd) to a cluster client and have them automatically be performed in an efficient way.

I've sketched out a function for doing GET's specifically against the v4 radix cluster client, but I think the code could be abstracted as an implementation for `DoActions` and `DoSecondaryActions`. I would be curious to hear feedback on this approach too.

```go
// clusteredGet runs GET for each key on a redis cluster. Keys are grouped into a pipeline for the right redis primary
func clusteredGet(ctx context.Context, client *radix.Cluster, keys ...string) ([]string, error) {
	topo := primaryNodes(client.Topo())

	pipelines := make([]*radix.Pipeline, len(topo))
	out := make([]string, len(keys))

	created := 0
	for i, key := range keys {
		index, err := nodeIndexForKey(topo, key)
		if err != nil {
			return nil, err
		}

		if pipelines[index] == nil {
			pipelines[index] = radix.NewPipeline()
			created++
		}

		action := radix.Cmd(&out[i], "GET", key)
		pipelines[index].Append(action)
	}

	actionable := make([]firstKeyAction, 0, created)
	for _, pipeline := range pipelines {
		if pipeline != nil {
			actionable = append(actionable, firstKeyAction{pipeline})
		}
	}

	eg, ctx := errgroup.WithContext(ctx)
	for _, pipeline := range actionable {
		pipeline := pipeline
		eg.Go(func() error {
			return client.Do(ctx, pipeline)
		})
	}

	if err := eg.Wait(); err != nil {
		return nil, err
	}

	return out, nil
}

type firstKeyAction struct {
	underlying radix.Action
}

func (f firstKeyAction) Properties() radix.ActionProperties {
	props := f.underlying.Properties()
	if len(props.Keys) > 0 {
		props.Keys = []string{props.Keys[0]}
	}
	return props
}

func (f firstKeyAction) Perform(ctx context.Context, c radix.Conn) error {
	return f.underlying.Perform(ctx, c)
}

func nodeIndexForKey(topo radix.ClusterTopo, key string) (int, error) {
	keySlot := radix.ClusterSlot([]byte(key))
	for i, node := range topo {
		for _, nodeSlot := range node.Slots {
			if keySlot >= nodeSlot[0] && keySlot < nodeSlot[1] {
				return i, nil
			}
		}
	}

	return 0, errors.New("could not determine node index")
}

func primaryNodes(topo radix.ClusterTopo) radix.ClusterTopo {
	var primaryNodes radix.ClusterTopo
	for _, node := range topo {
		if node.SecondaryOfAddr != "" && node.SecondaryOfID != "" {
			primaryNodes = append(primaryNodes, node)
		}
	}

	return primaryNodes
}

```

**Comment by mediocregopher** [comment]
Hi @kollektiv , this question gets brought up now and then, and my answer has always been that while code like yours would work in most cases, it's fairly "magical" and is prone to breaking during certain events like cluster node migrations. I'd rather leave the gory details of what happens during these events up to the user, since it's not _that_ hard to write a custom MGETer if you understand the internals of redis and radix (as you've shown), and I'd rather not make assumptions for the users who _don't_ understand these internals.

(Also, not totally related, but `ClusterTopo` already has a `Primaries` method which does essentially what your `primaryNodes` does :))
