### ISSUE TITLE
Receive buffer does not appear to get flushed correctly (v4 beta) 

### ISSUE THREAD

**Issue by thessem** [mediocregopher/radix#252]
I have the following code, which runs a Lua script that returns data (which I ignore), then runs a `PING`, and attempts to print the `PONG`.
```
package main

import (
	"context"
	"log"

	"github.com/mediocregopher/radix"
)

func main() {
	ctx := context.Background()
	client, err := radix.PoolConfig{}.New(
		ctx,
		"tcp",
		"localhost:36379",
	)
	if err != nil {
		panic(err)
	}

	luaScript := `
		return {ARGV[1], ARGV[2]}
	`

	err = client.Do(ctx, radix.NewEvalScript(luaScript).FlatCmd(
		nil,
		[]string{},
		"foo",
		"bar",
	))
	if err != nil {
		panic(err)
	}

	var pong interface{}
	err = client.Do(ctx, radix.Cmd(&pong, "PING"))
	if err != nil {
		panic(err)
	}
	log.Println(pong)
}
```

I get the following output if the script does not exist in the redis cache:
```
panic: NOSCRIPT No matching script. Please use EVAL.

goroutine 1 [running]:
main.main()
	<snip>/scratch.go:38 +0x3a9
exit status 2
```
noting that line 38 is the error from the `PING` command, not the Eval.

I get the following if the script exists in the redis cache:
```
2021/01/15 12:50:51 [[102 111 111] [98 97 114]]
```
which looks awfully like the result I ignored from the eval script (`[[foo] [bar]]`)

If line `25` is replaced with 
```
	var coolInterface interface{}
	err = client.Do(ctx, radix.NewEvalScript(luaScript).FlatCmd(
		&coolInterface,
		[]string{"test_key"},
		1,
		"foo",
		"bar",
	))
```
the output is
```
2021/01/15 12:55:24 PONG
```
as expected.

My suspicion is that the read stream isn't being flushed correctly when the receiver is nil due to something in line `126` in `conn_writer.go`, and the connection is getting reused with a non-nempty `br` since it's never read from by unmarshal, but I'm still trying to figure out what everything does under the hood.
```
			// if there's no unmarshaler then don't forward to the reader
			if mu.unmarshalInto == nil {
				mu.errCh <- nil
			} else if !cw.forwardToReader(mu) {
				return false
			}
```

**Expected Behaviour**
I don't think I should have to unmarshal my Lua script results into a `coolInterface`, since I often use my Lua scripts for their side-effects and not their returns.

**Comment by thessem** [comment]
Unrelated to the issue: the V4 beta more than doubles the throughput of my Lua heavy program, the connection re-use is extremely nice. Thanks 👍

**Comment by mediocregopher** [comment]
> My suspicion is that the read stream isn't being flushed correctly when the receiver is nil

Having not looked at the code yet I think that's a really good guess. I'll try to take a look this weekend if I can find a moment.

>  the V4 beta more than doubles the real world performance of my Lua heavy use case

That's great to hear! Thanks for being a beta tester of it :)

**Comment by mediocregopher** [comment]
@thessem I just pushed a fix for this, I'll release a new beta tag once I've addressed the other issues, but let me know if it works for you in the meantime.

**Comment by thessem** [comment]
Yep, this is fixed now. Thanks
