### ISSUE TITLE
Radix v3: Receiving errUnexpectedPrefix for some commands when trying to unmarshal to struct.

### ISSUE THREAD

**Issue by santriseus** [mediocregopher/radix#260]
Hi, we are trying to refactor our codebase and introduce the unmarshaling to structs. Approach with structs is really nice and for most of the commands we tried before it worked pretty well,  but we have an issue when trying it for command https://oss.redislabs.com/redistimeseries/commands/#tsinfo

We receive errUnexpectedPrefix prefix error, where expected is "$" and actual is "+". 
I debugged the raw Redis protocol content in the buffer and it looks like it happens because we expect that "keys" will be always a bulk string ($) rather than simple string (+).
Command which works fine (XINFO STREAM):
```
*14
$6
length
:9
$15
radix-tree-keys
:1
$16
radix-tree-nodes
:2
$17
last-generated-id
$15
1611019112058-0
$6
groups
:1
$11
first-entry
*2
$15
1611019111394-0
*2
$2
id
$9
p2zmi3m3p
$10
last-entry
*2
$15
1611019112058-0
*2
$2
id
$9
e17o29350
```
Command which fails (TS.INFO)
```
*24
+totalSamples
:3
+memoryUsage
:4234
+firstTimestamp
:1611292079917
+lastTimestamp
:1611292091222
+retentionTime
:0
+chunkCount
:1
+chunkSize
:4096
+chunkType
+compressed
+duplicatePolicy
$-1
+labels
*2
*2
$2
id
$3
111
*2
$6
sensor
$3
888
+sourceKey
$-1
+rules  
```

**Comment by mediocregopher** [comment]
@santriseus thanks for submitting the issue, I just pushed up a commit for v3 to support unmarshaling simple string fields into structs and will be tagging the release soon. Please re-open this issue if it doesn't work for you.
