### ISSUE TITLE
v4: Handling custom module commands

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#261]
radix currently keeps 2 lists (well maps, but who cares) of commands which it consolidates to find out whether a command is 1) blocking and 2) takes any keys. By default commands (with some exceptions) are assumed to take 1 key as the first argument and to be non-blocking. 

radix uses this information to decide where to send a command in a cluster and whether a command can be safely pipelined (since pipelining requires commands not to block).

This works well with built in commands since these are all well documented and stable, but may cause problems with custom commands provided by [Redis Modules](https://redis.io/topics/modules-intro). Since radix has no special knowledge of these commands it handles them like all other, non special cased commands, assuming they 1) take 1 key and 2) can be safely pipelined.

Both assumption are not necessarily true: A custom command can interpret its arguments in any way it wants and can [block](https://redis.io/topics/modules-blocking-ops) the client if it wants to.

While probably a rare case, I'm expecting these assumptions to cause some (probably hard to debug / find) problems in the future.

The best solution would be to add support for custom commands, but I think it would also be acceptable to just document the current state for now.

Unfortunately redis itself does not expose the information needed for us to automatically handle custom commands so supporting them in radix would probably require some kind of manual registration of commands.

**Comment by nussjustin** [comment]
@mediocregopher Just something that came to my mind a few minutes ago, when reading about and trying to implement a custom command that blocks. Haven't tested anything yet, but I don't I have missed anything important :-)

**Comment by mediocregopher** [comment]
My thinking around custom commands is that people could implement a wrapper around `Cmd` which returns the appropriate `ActionProperties` for whatever weird command they're working with. That does have the downside of likely being an extra memory allocation though, so maybe it's not the best solution. I guess an alternative could be to have a sibling type to `Cmd` and `FlatCmd` called `CmdConfig` which could have an `ActionProperties` field:

```go
type CmdConfig struct {
    // ActionProperties, if given, is used to generate the result of the
    // Properties method on Actions generated by CmdConfig.  If not given then
    // an ActionProperties will be inferred based on redis' built in set of
    // commands.
    ActionProperties func(cmd string, args ...string) ActionProperties }
}

func (cfg CmdConfig) Cmd(rcv interface{}, cmd string, args ...string) Action { ... }

func (cfg CmdConfig) FlatCmd(rcv interface{}, cmd string, args ...interface{}) Action { ... }

func Cmd(rcv interface{}, cmd string, args ...string) Action {
    (CmdConfig{}).Cmd(rcv, cmd, args...)
}

func FlatCmd(rcv interface{}, cmd string, args ...interface{}) Action {
    (CmdConfig{}).FlatCmd(rcv, cmd, args...)
}
```

Writing that out also makes me thinkg that EvalScript should probably have some way to change its properties as well, maybe `NewEvalScript` should get replaced with `EvalScriptConfig{}.New(script string)`....

Just ideas on it, thanks for bringing this up!

**Comment by nussjustin** [comment]
Oh wow, I didn't event think about using a custom `Action`. I really should stop writing these issues right before going to bed :-D

I like your idea for the `CmdConfig`. Seems simple and easy to use without adding any allocations or other overhead and without making the code unreadable. And using something like this for Lua scripts seems like another easy but nice win. SGTM.

**Comment by nussjustin** [comment]
Well, I'm kinda confused why this is still open. Merging the PR should have closed this issue o_o Well since this is still open (let's just pretend I planned this), can you go into more detail about your `EvalScriptConfig` idea? What exactly would you want to make configurable? The only thing I could think about, which wouldn't really be useful IMO, is disabling the `EVAL` in case the script is not cached.

**Comment by mediocregopher** [comment]
Well I didn't have anything specific in mind for EvalScript, just that if we wanted to modify it's properties it would be nice to already have the Config struct in place, rather than having the extraneous `NewEvalScript` function around. It could look like this:

```
type EvalScriptConfig struct {
    Script string // required
    
    // other options here later
}
```

It's mostly a forward compatibility concern, not that I think it will be immediately useful. But yeah, being able to disable `EVAL` would actually be possibly useful, so there ya go :)

(Gonna close this as well, I also don't know why it didn't :man_shrugging: )
