### ISSUE TITLE
[v4.0.0-beta.1] flushTicker need go 1.15, but go.mod is 1.13

### ISSUE THREAD

**Issue by nimoc** [mediocregopher/radix#263]
My local environment go version is 1.14

I found error:
![image](https://user-images.githubusercontent.com/3949015/109266984-cfd64480-7843-11eb-99bd-9e8441d853b7.png)

I checked the problem and found out:

```go
flushTicker   interface {
		Stop()
		Reset(time.Duration)
}
```
https://github.com/mediocregopher/radix/blob/v4/conn_writer.go#L22-L25

----

time.NewTicker

https://github.com/mediocregopher/radix/blob/v4/conn_writer.go#L48

> go1.15 support time.Ticker{}.Reset(time.Duration) https://golang.org/doc/go1.15#time
---

go.mod 1.13
https://github.com/mediocregopher/radix/blob/v4/go.mod#L10

The go.mod version should be changed to 1.15 ？

**Comment by mediocregopher** [comment]
Good catch @nimoc, thanks! Just pushed a commit changing the go version.
