### ISSUE TITLE
v4: Run tests with RESP 3 enabled

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#266]
Currently all tests use the default RESP protocol version RESP 2.

RESP 3 has a lot of changes which can cause problems with commands that expect to receive responses of specific types.

I patched `conn.go` to always use RESP 3 like this:

```diff
diff --git a/conn.go b/conn.go
index 97f63ac..ea94d86 100644
--- a/conn.go
+++ b/conn.go
@@ -334,6 +334,11 @@ func (d Dialer) Dial(ctx context.Context, network, addr string) (Conn, error) {
                conn.writer(ctx, d.WriteFlushInterval)
        })
 
+ if err := conn.Do(ctx, Cmd(nil, "HELLO", "3")); err != nil {
+         conn.Close()
+         return nil, err
+ }
+
        if d.AuthUser != "" {
                if err := conn.Do(ctx, Cmd(nil, "AUTH", d.AuthUser, d.AuthPass)); err != nil {
                        conn.Close()
```

This results in a lot of errors for pubsub and streams related logic which do not happen with RESP 2. These are obviously bugs in radix and should be fixed before the v4 release.

As part of fixing these bugs and preventing future regressions I propose that we

1. Add a new `Protocol` field to `Dialer` which allows to set the RESP version used for new connections.
2. Add a new flag / environment variable that enables RESP 3 for all test connections by setting the `Protocol` field for `dial`.

**Comment by nussjustin** [comment]
The problem with the streams lies in the encoding of the `StreamEntries` which changes between RESP 2 and 3. In RESP 2 the result of a `XREAD` call looks like this:

```
127.0.0.1:6379> XREAD STREAMS stream 0-0
1) 1) "stream"
   2) 1) 1) "1615795972182-0"
         2) 1) "a"
            2) "b"
            3) "c"
            4) "d"
            5) "e"
            6) "f"
```

That is an array containing arrays which contain the stream name (in this case `"stream"`) and another array containing the read entries.

In RESP 3 the same command returns the following:

```
127.0.0.1:6379> XREAD STREAMS stream 0-0
1# "stream" =>
  1) 1) "1615795972182-0"
      2) 1) "a"
         2) "b"
         3) "c"
         4) "d"
         5) "e"
         6) "f"
```

Here the out-most array has become a map with the stream name as key and the stream entries array as value.

Since we a) parse the response as a `[]StreamEntries` and b) expect an array in `(*StreamEntries).UnmarshalRESP` decoding the response fails.

Fixing this probably means updating `(*StreamEntries).UnmarshalRESP` to support skipping the array header (since we can just read the map key and value like this was an array of 2 elements) and adding a custom `Unmarshaler` implementation for `[]StreamEntries` that avoids the map parsing logic and instead just let's the `*StreamEntries` handle both key and value for each map entry.

The same problem also happens with `XREADGROUP`.

**Comment by mediocregopher** [comment]
oof, I hadn't realized that switching to RESP 3 mode would actually change the responses of certain existing commands, I figured that would be for changes going forward.

I agree it'd be good to set the protocol on the Dialer, as long as it defaults to RESP 2. If we do something like attempt to use RESP 3 and fallback to RESP 2 we might put someone in a situation where they upgrade from an old redis to the latest one and now all their code unmarshals responses in a subtly different way.

A flag for tests would be great, that's a good idea. We can modify the travis runner to attempt the tests with both set.

**Comment by nussjustin** [comment]
Ok, this is the second time a PR from me was merged without the issue being closed. The PR even has the word "Fixes" underlined with tooltip saying that the merge will close this issue. It seems that Github really likes toying with me.

**Comment by mediocregopher** [comment]
lol, come on github get it together
