### ISSUE TITLE
radix do not reset the rcv when executing a command

### ISSUE THREAD

**Issue by shrimptttttttttt** [mediocregopher/radix#267]
```
func TestCmdAction(t *T) {
	c := dial()
	key := randStr()
	var mapValue = make(map[string]string)
	mapValue["bar"] = "car"
	mapValue["car"] = "bar"

	err := c.Do(FlatCmd(nil, "HMSET", key, mapValue))
	if err != nil {

	}
	var outputMap map[string]string
	err = c.Do(FlatCmd(&outputMap, "HGETALL", key))

	err = c.Do(FlatCmd(nil, "DEL", key))

	err = c.Do(FlatCmd(&outputMap, "HGETALL", key))
        // The output map doesn't reset.
	if err != nil {

	}
}
```

You can see from the debug results. Even the key was deleted, the output map doesn't be reset and keep the old value. 
![image](https://user-images.githubusercontent.com/46477443/111432097-8b99de00-8737-11eb-9a9c-97f76d3995f8.png)

Is it a bug? As I don't think it's a good way to force user reset output before calling. And is there any solution?

**Comment by nussjustin** [comment]
[Maps and structs do not get reset when unmarshaling into them](https://github.com/mediocregopher/radix/blob/ed8bf9d3f9e23cf860eb17693ac26e5cb5482534/resp/resp2/resp.go#L1022-L1115).

I'm not sure what behaviour we want here. I think having maps and structs be "overriden" is more natural (and more common in Go?)

@mediocregopher WDYT?

**Comment by mediocregopher** [comment]
For marshaling and unmarshaling logic I've used the `encoding/json` package as my guiding light for these sorts of questions, and the json package doesn't reset its receiver types:

```go
package main

import (
	"encoding/json"
	"log"
)

func main() {
	var m map[string]string

	if err := json.Unmarshal([]byte(`{"foo":"bar"}`), &m); err != nil {
		panic(err)
	}
	log.Printf("m:%+v", m)

	if err := json.Unmarshal([]byte(`{"biz":"buz"}`), &m); err != nil {
		panic(err)
	}
	log.Printf("m:%+v", m)

	if err := json.Unmarshal([]byte(`{}`), &m); err != nil {
		panic(err)
	}
	log.Printf("m:%+v", m)
}
```

Produces:

```
2021/03/17 16:51:36 m:map[foo:bar]
2021/03/17 16:51:36 m:map[biz:buz foo:bar]
2021/03/17 16:51:36 m:map[biz:buz foo:bar]
```

I agree that it's odd, but it also greatly simplifies explaining/understanding how marshaling/unmarshaling works to be able to say "it works like the json package" than to have to document all the weird little edge cases like this one.

**Comment by nussjustin** [comment]
Oh yeah, right. Forgot that's how `encoding/json` and friends work. Yeah, not clearing is easier, so just documenting the fact should be enough here.

**Comment by mediocregopher** [comment]
Going to close this as a "Won't Fix", sorry @shrimptttttttttt
