### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by Bysmyyr** [mediocregopher/radix#270]
Hi,

any hints how to use Radix with Redis with TLS?  (v4)

**Comment by nussjustin** [comment]
The [Dialer](https://pkg.go.dev/github.com/mediocregopher/radix/v4#Dialer) has a [NetDialer](https://pkg.go.dev/github.com/mediocregopher/radix/v4#Dialer.NetDialer) field which can be used to change the dialing behaviour. Setting this to a [tls.Dialer](https://golang.org/pkg/crypto/tls/#Dialer) should be enough to get TLS working.

If you are using a pool (via [PoolConfig](https://pkg.go.dev/github.com/mediocregopher/radix/v4#PoolConfig)) you must set the [Dialer](https://pkg.go.dev/github.com/mediocregopher/radix/v4#PoolConfig.Dialer) field to a custom [Dialer](https://pkg.go.dev/github.com/mediocregopher/radix/v4#Dialer) as secribed above.

**Comment by Bysmyyr** [comment]
Thanks, got it working, here sample for next one thinking how to do this. Includes also cluster-config:

```
dialer := radix.Dialer{
		AuthPass: conf.Redis.Password,
		AuthUser: conf.Redis.User,
}
	
dialer.NetDialer = &tls.Dialer{
	NetDialer: nil,
	Config:    nil,
}
cfg := radix.ClusterConfig{PoolConfig: radix.PoolConfig{
	Dialer: dialer,
}}
redis, err = cfg.New(context.Background(), []string{conf.Redis.ConnString()})
```
