### ISSUE TITLE
v4: Potential for messages to be lost due to context deadline

### ISSUE THREAD

**Issue by mediocregopher** [mediocregopher/radix#274]
### Background

This bug primarily affects subscription based use-cases, such as pubsub or streams.

The following sequence of events can happen:

1) [EncodeDecode](https://github.com/mediocregopher/radix/blob/bcfb640342e3115c83b77c0d7833f82b33f28210/conn.go#L117) is called on `Conn` with a context that has some kind of deadline.

2) The command information gets passed through the codepath until it reaches the `reader` within `Conn`, [here](https://github.com/mediocregopher/radix/blob/bcfb640342e3115c83b77c0d7833f82b33f28210/conn.go#L70).

3) [Unmarshal](https://github.com/mediocregopher/radix/blob/bcfb640342e3115c83b77c0d7833f82b33f28210/conn.go#L85) is called, and blocks.

4) At the same moment, the call to `Unmarshal` successfully reads a message, and the context is canceled.

5) Before the `reader` can send back a message to the response channel [here](https://github.com/mediocregopher/radix/blob/bcfb640342e3115c83b77c0d7833f82b33f28210/conn.go#L96), the original call to `EncodeDecode` unblocks on the [doneCh](https://github.com/mediocregopher/radix/blob/bcfb640342e3115c83b77c0d7833f82b33f28210/conn.go#L136), because the context was canceled.

The result is that `context.DeadlineExceeded` or `context.Canceled` is returned from `EncodeDecode`, even though a message was successfully read from the connection. That message is simply dropped.

For most use-cases this isn't a big deal, but for something like pubsub where it's expected for messages to be infrequent and context deadline exceeding to happen normally, it will almost definitely result in messages being randomly dropped.

This bug also happens to affect the `Stub`, so whatever fix is applied here must get applied there as well.

### Solution

The `Conn` needs to be reworked no matter what. It's the biggest bottleneck of radix due to all the channel read/writes. I've taken a stab at this a couple of times but it hasn't worked out yet.

It'd be nice if golang provided a way to cancel a read off a connection with a context, because the lack of being able to do that is really what's hurting us here. The alternative seems to be something along the lines of storing the dropped message for the next read, and somehow signaling back to the reader that the message was indeed dropped.

**Comment by nussjustin** [comment]
> It'd be nice if golang provided a way to cancel a read off a connection with a context

It should be possible to cancel a read by setting a read deadline in the past. From the `SetDeadline` documentation (which also applies to `SetReadDeadline`):

> A deadline is an absolute time after which I/O operations fail instead of blocking. The deadline applies to all future and **pending I/O**, not just the immediately following call to Read or Write. After a deadline has been exceeded, the connection can be refreshed by setting a deadline in the future.

Whenever the context used for `EncodeDecode` is closed we could set a deadline. This way the reader would be responsible for returning the error.

**Comment by mediocregopher** [comment]
Oh cool I didn't know about that! That seems more straightforward than what I was thinking (something using a TeeReader and some custom bytes.Buffer/bufio.Reader implementations that woulda been a mess). I wonder if having the deadline get set to the past could be done without spawning a new go-routine within reader for each Unmarshal call....

**Comment by nussjustin** [comment]
Couldn't we just do this [here](https://github.com/mediocregopher/radix/blob/bcfb640342e3115c83b77c0d7833f82b33f28210/conn.go#L137) and then continue waiting until either the conn is closed or the reader signals us that it's done?

**Comment by mediocregopher** [comment]
It's going to be a bit more complicated than that I think, cause you could have multiple EncodeDecode calls going simultaneously. If the EncodeDecode call which is currently being served doesn't get cancelled, but the one which will get served _next_ does, then that next call will cause the currently being served one to be timedout.

**Comment by nussjustin** [comment]
If we could identify the `connMarshalerUnmarshaler` (e.g. using an atomically incremented sequence number) then we could track the currently processed `connMarshalerUnmarshaler` on the `conn` and then check this number before setting the timeout. 

Basically create the `connMarshalerUnmarshaler` like this

```go
mu := connMarshalerUnmarshaler{
	seq: atomic.AddUint64(&conn.seq, 1), // new field on *conn
	ctx:           ctx,
	marshal:       m,
	unmarshalInto: u,
	errCh:         c.getErrCh(),
}
``` 

And change the select case to something like this:

```go
select {
case <-doneCh:
	c.currSeqMu.Lock()
	if c.currSeq != mu.seq {
		// either mu was already processed, in which case we can read the result or is still in the queue in which case it will be skipped
		c.currSeqMu.Unlock()
		select {
		case err := <-mu.errCh:
			c.putErrCh(mu.errCh)
			return err
		default:
			return ctx.Err()
		}
	}
	// mu is currently being processed, cancel it
	c.conn.SetReadDeadline(time.Unix(0, 0))
	c.currSeqMu.Unlock()
	select {
	case <-closedCh:
		return proc.ErrClosed
	case err := <-mu.errCh:
		c.putErrCh(mu.errCh)
		return err
	}
```

Then `reader` would need to obtain the lock after receiving the `connMarshalerUnmarshaler` and update the current sequence number

```go
case mu := <-c.rCh:
	c.currSeqMu.Lock()
	c.currSeq = mu.seq
	if err := mu.ctx.Err(); err != nil {
```

And temporarily release it when unmarshaling so the other goroutine can read the sequence 

```go
	c.currSeqMu.Unlock()
	err := resp3.Unmarshal(c.br, mu.unmarshalInto, c.rOpts)
	c.currSeqMu.Lock()
	if err != nil {
```

And then release it after sending the result

```go
	mu.errCh <- err
	c.currSeqMu.Unlock()
```

This ~should~ may work™

**Comment by nussjustin** [comment]
I tried implementing this today, but ran into a problem:

When cancelling a read we still need to discard the unread value as otherwise the next `connMarshalerUnmarshaler` would read the (unread) response to the previous `connMarshalerUnmarshaler`. While this is easy to do (and I did actually implement this), this breaks the logic in `(*pubSubConn).spin` which expects the value to remain in the buffer.

Looking at the code for `(*pubSubConn).spin` I see that each iteration creates a new sub-context with a small timeout that is used to limit the wait duration, but I don't understand why this should be necessary. Without the timeout, the problem should not arise. 

@mediocregopher Can you explain why the timeout for recevigin the PUBSUB messages is necessary? Btw. you can see my stab at this problem [here](https://github.com/mediocregopher/radix/compare/v4...nussjustin:v4-fix-unmarshal-cancel-race?expand=1)

**Comment by mediocregopher** [comment]
@nussjustin lol, damnit, we were both working on this at the same time. I pushed my branch with my attempt [here](https://github.com/mediocregopher/radix/pull/279). That doesn't fix the Stub yet, I've set aside some time tomorrow to do so.

I think you're right that if we just don't do a timeout in the `pubSubConn.spin` we could avoid the issue, but what I didn't mention in the original post was that I ran into this because I was trying to rewrite the pubsub code. Essentially I wanted to move it from using channels to being a simple interface with a `Next`-like method on it. When I've used v3's pubsub code in the wild I've found it pretty unwieldy, and the channels add in additional weird edge-cases shutdown logic.

You can see the new interface I was working on [here](https://github.com/mediocregopher/radix/blob/v4-newpubsub/pubsub2.go#L15). Obviously once it's ready I'll rename it and ditch the old one. But anyway, as it relates to _this_ issue, that implementation really requires that unread messages remain in the buffer, since `Next` is synchronous.

> When cancelling a read we still need to discard the unread value as otherwise the next connMarshalerUnmarshaler would read the (unread) response to the previous connMarshalerUnmarshaler.

I believe you're suggesting we _need_ to discard the subsequent messages as a result of #277, is that right? If so, I think the solution there is going to be outside of Conn; it should be up to Pool to track whether a Conn has returned an error or not, and deals with propagating that to other commands using the same Conn and then closing the Conn. Tbh I thought it already did this, but maybe that code is just broken.

Anyway, sorry to step on your toes here, we both chose the same day after an 18 day break to tackle this :sweat_smile:

**Comment by nussjustin** [comment]
> I believe you're suggesting we need to discard the subsequent messages as a result of #277, is that right?

What I meant is that if we have 2 commands, let's call them `A` and `B`, which have both already been send to Redis, and `A` times out reading from the connection (because of the read deadline) the response for `A` will still be send by Redis at some point, before Redis can then execute and send the response for command `B`. In that case we need to skip the response of `A` since we already returned an error for `A`.

In my branch I handled this by [checking for context errors and discarding the response ](https://github.com/nussjustin/radix/blob/90d8ee15468129553bb753e83726e9eb4b62aa9d/conn.go#L130-L132)after sending the error to the goroutine that called `EncodeDecode` (to avoid blocking the goroutine until the read finished).

> Anyway, sorry to step on your toes here, we both chose the same day after an 18 day break to tackle this

Well _obviously_. What else did you expect to happen?

**Comment by mediocregopher** [comment]
> In that case we need to skip the response of A since we already returned an error for A.

I don't think it's going to be quite that simple. If the response for A was only partially read then Conn would have to somehow be able to discard the latter part of A's message when it comes time to read for B. The way the resp package works now doesn't make that easy, and it should be such a rare case that I don't think it's worth jumping through tons of hoops for.

So there's a few cases that need to be handled here:

1. - A's message is successfully read prior to context being canceled, no error is returned, B read its message normally.
2. - A's message is not read at all prior to context being canceled, context error is returned wrapped in ErrConnUsable, A's message is discarded prior to B reading.
3. - A's message is partially read prior to context being canceled, context error is returned unwrapped, connection is closed, all further calls on the Conn return an error ("conn closed" or something like that).

Knowing whether the message has been partially read is simple, just need to wrap `net.Conn` with something which counts the number of bytes read within the `Read` call and allows for fetching and resetting that number.

**Comment by mediocregopher** [comment]
@nussjustin I just pushed a commit to my [PR](https://github.com/mediocregopher/radix/pull/279) that I think covers all cases. I _think_ I've covered all cases correctly, but my code looks a lot different to yours so I was hoping you could take a look at it to make sure I didn't miss something :pray:
