### ISSUE TITLE
How to get multiple keys without MGET?

### ISSUE THREAD

**Issue by mghifariyusuf** [mediocregopher/radix#283]
can I get multiple keys without MGET?

https://redis.io/commands/mget
in there it command is MGET key1 key2

in my company I didn't allowed using MGET because the keys is very much and it will make redis slower

in radix there is pipeline for multiple commands, can I using pipeline for multiple GET ?

**Comment by nussjustin** [comment]
You can use the `Pipeline` function to pipeline multiple `GET` commands:

```go
if err := conn.Do(radix.Pipeline(
    radix.Cmd(&rcv1, "GET", "key1"),
    radix.Cmd(&rcv2, "GET", "key2"),
    radix.Cmd(&rcv3, "GET", "key3"),
    // ...
)); err != nil {
    // handle error
}
```

Or you could use a lua script using, which may be faster. You can find [an example of using lua scripts](https://pkg.go.dev/github.com/mediocregopher/radix/v3#example-EvalScript) in the documentation.

**Comment by mghifariyusuf** [comment]
@nussjustin can I use `Pipeline` for multiple `GET` commands for only one variable? Maybe store it in a slice?
From your code example it needs to define the variable rcv first as much as amount of keys

**Comment by nussjustin** [comment]
You could do something like this:

```go
vals := make([]string, len(keys)) // Change the type to whatever type you need
cmds := make([]radix.CmdAction, len(keys))
for i, key := range keys {
    cmds[i] = radix.Cmd(&vals[i], "GET", key)
}
if err := conn.Do(radix.Pipeline(cmds...)); err != nil {
    // handle error
}
```

Or you could implement your own `CmdAction`.

**Comment by mghifariyusuf** [comment]
@nussjustin thankyou for your insight! I never know how to do it before and from your explanation it worked! So I will close this issue. Thankyou once again 😁
