### ISSUE TITLE
sentinel spin is blocked

### ISSUE THREAD

**Issue by lp2jx0309** [mediocregopher/radix#286]
version:3.2.0

The server is sentinel mode, 3 sentinel node and  2 data node. When the server is powered down and powered on again laterly, the master and replica  nodes are switched. At this time, the client cannot sense the changes, because the Sentinel.spin()  is blocked.
further more，pubsub.PSubscribe() method holds lock "c.csL" and pubsub.do() method wait to receive "c.cmdResCh"， but, pubsub.closeInner() method is waiting to hold lock "c.csl".
please review the code and confirm wheather my analysis  correct, thanks @mediocregopher 

the stack is:

goroutine 238 [chan receive, 6053 minutes]:
github.com/mediocregopher/radix/v3.(*pubSubConn).do(0xc000261600, 0x1, 0x1f9ddbc, 0x9, 0xc000967510, 0x1, 0x1, 0x0, 0x0)
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub.go:281 +0x195
github.com/mediocregopher/radix/v3.(*pubSubConn).Subscribe(0xc000261600, 0xc000a4f320, 0xc000967510, 0x1, 0x1, 0x0, 0x0)
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub.go:323 +0x264
github.com/mediocregopher/radix/v3.(*persistentPubSub).refresh.func1(0xc0003df880, 0x0)
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub_persistent.go:56 +0x158
github.com/mediocregopher/radix/v3.(*persistentPubSub).refresh(0xc000451700)
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub_persistent.go:87 +0x67
github.com/mediocregopher/radix/v3.(*persistentPubSub).refresh.func1.1(0xc000a4fd40, 0xc000451700, 0x2320540, 0xc0003df880)
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub_persistent.go:77 +0x161
created by github.com/mediocregopher/radix/v3.(*persistentPubSub).refresh.func1
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub_persistent.go:69 +0x2b0
		

goroutine 685963 [semacquire, 6053 minutes]:
sync.runtime_SemacquireMutex(0xc000261614, 0x483500, 0x1)
        /usr/local/go1.14.12/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000261610)
        /usr/local/go1.14.12/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
        /usr/local/go1.14.12/src/sync/mutex.go:81
sync.(*RWMutex).Lock(0xc000261610)
        /usr/local/go1.14.12/src/sync/rwmutex.go:98 +0x97
github.com/mediocregopher/radix/v3.(*pubSubConn).closeInner.func1()
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub.go:293 +0x5d
sync.(*Once).doSlow(0xc000261648, 0xc000c57ed0)
        /usr/local/go1.14.12/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
        /usr/local/go1.14.12/src/sync/once.go:57
github.com/mediocregopher/radix/v3.(*pubSubConn).closeInner(0xc000261600, 0x22c2b00, 0xc0007d87d0, 0x7ff13c1a25a8, 0xc0007d87d0)
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub.go:292 +0x94
github.com/mediocregopher/radix/v3.(*pubSubConn).spin(0xc000261600)
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub.go:258 +0x252
created by github.com/mediocregopher/radix/v3.newPubSub
        /root/.mvnGoLang/.go_path/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.0/pubsub.go:211 +0xe5

**Comment by mediocregopher** [comment]
@lp2jx0309 some of the locking logic in both sentinel and the persistent pubsub code has changed since v3.2.0, could you try upgrading your radix package and seeing if this is still an issue you're running into? If anything it would be helpful to have an updated stack-trace.

**Comment by lp2jx0309** [comment]
@mediocregopher thanks, the issue has been solved by upgrding.

**Comment by mediocregopher** [comment]
Glad to hear! will close the issue then.
