### ISSUE TITLE
may add maxlifetime in the connection pool？

### ISSUE THREAD

**Issue by fare83** [mediocregopher/radix#289]
in my project, redis addr use domain name, and domain name lookup ip  will be change  in some times。may add maxlifetime in the connection pool like database/sql ?  it can help for auto reconnect in some scenarios like nslookup result change。thank you。

**Comment by mediocregopher** [comment]
Hi @fare83 , I would be interested in adding this feature, would you be able to implement a PR for it?

**Comment by fare83** [comment]
Hi @mediocregopher, I pull a PR for it. Please code review for it, thank you.
