### ISSUE TITLE
OpenTelemetry tracing manual instrumentation support

### ISSUE THREAD

**Issue by filipecosta90** [mediocregopher/radix#295]
In the same way as seen on the  OpenTelemetry instrumentation for`go-redis` it would be extremely beneficial to create a similar package for radix. **Not only we can track the overhead of the client code, but we can also precisely trace errors/latency spikes/timeouts/etc...**

Some further info:
- [Small example of goredis manual instrumentation](https://github.com/go-redis/redis/tree/master/extra/redisotel/example)
- [Full example of HTTP service + Redis backed (with client instrumentation)](https://github.com/filipecosta90/opentelemetry-go-http-sample)

## Important Note: Semantic conventions to follow while preparing a package for manual instrumentation.
While this is not mandatory, we should aim for standardization across clients/languages/DBs. Here's the spec on DB semantic conventions:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md

PS: will gladly contribute to this matter.

**Comment by mediocregopher** [comment]
Hi @filipecosta90 , sorry it's taken me so long to get back to you. I'm willing to advise in the creation of a package which implements OpenTelemetry instrumentation with radix, however, just to be clear, it's not something I think should actually be a _part_ of radix. I've put in some effort to make radix instrumentable without needing to pick an "official" instrumentation framework; anyone should be able to get any metrics they need out of the library via the `trace` package, custom callback functions, and interface wrappers.

It should be possible for someone to put together a separate package which uses these to wrap radix for OpenTelemetry specifically, and anyone who cares to can use that.

**Comment by mediocregopher** [comment]
Going to close this for now, feel free to re-open if there's any questions you have about how to integrate OpenTelemetry.
