### ISSUE TITLE
Why doesn't 'saneDefault' handle error response? 

### ISSUE THREAD

**Issue by shrimptttttttttt** [mediocregopher/radix#296]
In radix do command, I pass a *interface{} to the Cmd's rcv
```
func Cmd(rcv interface{}, cmd string, args ...string) CmdAction {
	c := getCmdAction()
	*c = cmdAction{
		rcv:  rcv,
		cmd:  cmd,
		args: args,
	}
	return c
}
```

Server returns an error response starts with an error prefix, namely '-', then we receive a panic as follows
```
func saneDefault(prefix byte) interface{} {
	// we don't handle errPrefix because that always returns an error and
	// doesn't touch I
	switch prefix {
	case arrayPrefix[0]:
		ii := make([]interface{}, 8)
		return &ii
	case bulkStrPrefix[0]:
		bb := make([]byte, 16)
		return &bb
	case simpleStrPrefix[0]:
		return new(string)
	case intPrefix[0]:
		return new(int64)
	}
	panic("should never get here")
}
```

My question is what's the reason of this design?
I expect to receive an error response, rather than process panics.

**Comment by mediocregopher** [comment]
Hi @shrimptttttttttt this is not an intentional design decision, simply a hole in the logic which needs to be fixed, thanks for bringing it to my attention :) I will come up with a fix in the next week or so (unless someone beats me to it 😉 )

**Comment by mediocregopher** [comment]
Well weeks became months, but in any case I was able to come back to this to investigate. @shrimptttttttttt I'm not able to reproduce any panic by passing an `*interface{}` into an erroring `Cmd` on either `v3` or `v4`. Here's the test cases I tried:

**v3**:

```go
func TestBlah(t *testing.T) {
    c := dial()

    var into interface{}
    err := c.Do(Cmd(&into, "UNKNOWN", "COMMAND"))

    var respErr resp2.Error
    ok := errors.As(err, &respErr)

    assert.True(t, ok)
    assert.True(t, strings.HasPrefix(respErr.E.Error(), "ERR unknown command `UNKNOWN`"))
}
```

**v4:**

```go
func TestBlah(t *testing.T) {
    c := dial()

    var into interface{}
    err := c.Do(context.Background(), Cmd(&into, "UNKNOWN", "COMMAND"))

    var respErr resp3.SimpleError
    ok := errors.As(err, &respErr)

    assert.True(t, ok)
    assert.True(t, strings.HasPrefix(respErr.S, "ERR unknown command `UNKNOWN`"))
}
```

Do you have a test case of your own which is producing a panic? If so that would be very helpful to see.
