### ISSUE TITLE
Protocol error: invalid multibulk length.

### ISSUE THREAD

**Issue by Trial97** [mediocregopher/radix#299]
Hi @mediocregopher,

First, let me thank you for this awesome library.
I encountered the following error when I tried to use HMSet: `-ERR Protocol error: invalid multibulk length`.
After some investigation regarding this, I found out that it was because of the large number of arguments I used in that command(https://github.com/StackExchange/StackExchange.Redis/issues/201#issuecomment-98639005).
I am confused on whether we should handle the error in our code or maybe better in your library?

Thanks,
Trial97

**Comment by mediocregopher** [comment]
@Trial97 In my opinion that error should be handled in your code. There's not really anything for radix to do about that except forward the error along, is there?

**Comment by Trial97** [comment]
Hi @mediocregopher,

Thanks for your quick reply.
I followed your advice and fixed it in my code: https://github.com/cgrates/cgrates/blob/3e2ff64ee1f6b52ad664a7cf5be526c3415186c3/engine/storage_redis.go#L1202-L1235

Thanks,
Trial97
