### ISSUE TITLE
Cannot be used when using special characters in the password

### ISSUE THREAD

**Issue by iSwiftLiu** [mediocregopher/radix#301]
v3 version Cannot be used when using special characters in the password.

password example: q!#@/erwadasDD

with NewPool

**Comment by mediocregopher** [comment]
Hi @iSwiftLiu, can you give me more details about this? Some example code showing how you're initializing the pool would be great, along with whatever error you're experiencing :pray:

**Comment by iSwiftLiu** [comment]
Hi @mediocregopher, the code used is https://github.com/yannh/redis-dump-go

```
func RedisURL(redisHost string, redisPort string, redisDB string, redisPassword string) string {
	switch {
	case redisDB == "":
		return "redis://:" + redisPassword + "@" + net.JoinHostPort(redisHost, redisPort)
	case redisDB != "":
		return "redis://:" + redisPassword + "@" + net.JoinHostPort(redisHost, redisPort) + "/" + redisDB
	}
	return ""
}
redisURL := RedisURL(redisHost, fmt.Sprint(redisPort), fmt.Sprint(db), redisPassword)
client, err := radix.NewPool("tcp", redisURL, 1)
	if err != nil {
		return nil, err
	}
	defer client.Close()
```
```
dial tcp: address redis://:q!#@/erwadasDD@127.0.0.1:6379: too many colons in address
```

**Comment by iSwiftLiu** [comment]
Sorry for the operation error closed

**Comment by mediocregopher** [comment]
Hi @iSwiftLiu, the issue is likely occuring because you're constructing the URL manually and so the password isn't getting escaped properly. Try using the [url](https://pkg.go.dev/net/url) to construct your URL instead, that should result in a properly escaped url string.

**Comment by iSwiftLiu** [comment]
> Hi @iSwiftLiu, the issue is likely occuring because you're constructing the URL manually and so the password isn't getting escaped properly. Try using the [url](https://pkg.go.dev/net/url) to construct your URL instead, that should result in a properly escaped url string.


thank you very much. it is normal after using url.QueryEscape(redisPassword).
