### ISSUE TITLE
Backoff Retry During Network Errors

### ISSUE THREAD

**Issue by pandasachin91** [mediocregopher/radix#304]
Is it possible to Implement BackOff and retry when we receive Network Error From Redis.

If its already Implemented could you please  point me to the documentation if any ?

**Comment by mediocregopher** [comment]
@pandasachin91 there's no builtin backoff/retry within the driver, I think that would be outside of the scope of the project. You can implement this on your end by catching errors returned from Pool or Conn or whatever you're interacting with. You could even wrap the Pool implementation to do it semi transparently.
