### ISSUE TITLE
Incorrect deserialisation of an array with errors

### ISSUE THREAD

**Issue by nerg4l** [mediocregopher/radix#305]
Recently I started to work with RedisTimeSeries which has a [`TS.MADD` command](https://oss.redis.com/redistimeseries/commands/#tsmadd). The specialty of this command is the returned array which can contain both `int64` and `error` because in case of an error it continues the execution. This is not handled correctly in radix. Instead of deserialising each value radix fails at the first error it encounters.

Error:

```
response returned from Conn: unmarshaling message off Conn: ERR TSDB: the key is not a TSDB key
```

Example:

```go
package main

import (
	"context"
	"github.com/mediocregopher/radix/v4"
	"log"
	"testing"
	"time"
)

func TestClient_MAdd(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	client, _ := (radix.PoolConfig{}).New(ctx, "tcp", "localhost:6379")
	err := client.Do(ctx, radix.FlatCmd(nil, "TS.CREATE", "known:key"))
	if err != nil {
		t.Error(err)
	}
	defer client.Do(ctx, radix.FlatCmd(nil, "DEL", "known:key"))
	var val interface{}
	args := []interface{}{
		"known:key", 946684800000, 1,
		"missing:key", 946684800000, 1,
		"known:key", 946684800001, 2,
	}
	err = client.Do(ctx, radix.FlatCmd(&val, "TS.MADD", args...))
	if err != nil {
		t.Error(err)
	}
	log.Println(val)
}
```

I tested the same command with `github.com/go-redis/redis/v8`, `github.com/gomodule/redigo`, and `github.com/joomcode/redispipe`. All three of them deserialises the array correctly (`int64`, `error`, `int64`).

**Comment by nussjustin** [comment]
Just opened a draft PR (#306) with a possible solution.

Can you take a look at the PR and tell me if this would work for you?

**Comment by nerg4l** [comment]
@nussjustin Looks good to me and handles the response of `TS.MADD` as needed for my case. I added one comment about a code comment. Thanks.
