### ISSUE TITLE
Do we support auto resolve DNS

### ISSUE THREAD

**Issue by huanwu** [mediocregopher/radix#310]
If pass in the DNS when connect to redis, if the ip of the DNS change, will the library auto resolve the DNS?

**Comment by TUo23r32** [comment]
Heyyyy @huanwu,

this has to be checked on your side. Once the TCP connection is established, it's established.

**Comment by mediocregopher** [comment]
To expand a bit, DNS should get resolved for every new connection which is made. So if you're using Pool, and old connections happen to be closed for one reason or another, then new connections should get whatever the latest DNS entries are there.
