### ISSUE TITLE
Using radix.Maybe with WATCH

### ISSUE THREAD

**Issue by ghost** [mediocregopher/radix#312]
Hi @mediocregopher :wave:,

while learning to use Radix, I have tried to use `radix.Maybe` to detect whether an `EXEC` statement returns a Null reply (see https://redis.io/commands/exec/). The main idea is to be able to return a distinguishable error type to callers in case a call has failed due to concurrent access. From the documentation, it seemed to me that `radix.Maybe` could be used to wrap a `radix.Tuple` and to detect via it's `Null` field, whether actually a Tuple was returned or not.

To validate this assumption, I wrote the learning test attached below.

Unfortunately, instead of the test passing, I received the following error on `EXEC`'s `conn.Do` call:

> response returned from Conn: unmarshaling message off Conn: expected array of size 3 but got array of size 0

So I wanted to ask you if this error is intentional, meaning that `radix.Maybe` is not supposed to be used in conjunction with Tuples?
And, if so, is there another way short of using an `[]interface{}` as `rcv` to detect abovementioned condition?
Or am I maybe just using it in a wrong way? :smile: 

Thank you for developing and maintaining Radix - I really enjoy its more minimal approach compared to `go-redis/redis` :slightly_smiling_face: 

Best Regards,
Lucas

---

The failing test:

```go
ctx := context.Background()

newTestDB(ctx, t, nil) // flushes the Redis database used for testing

client1 := rawRedisClient(ctx, t) // returns a radix.Client
client2 := rawRedisClient(ctx, t)

fooWatched := make(chan struct{}, 1)
fooSet := make(chan struct{}, 1)

var waitGroup sync.WaitGroup
waitGroup.Add(2)

go func() {
	defer waitGroup.Done()

	err := client1.Do(ctx, radix.WithConn("", func(ctx context.Context, conn radix.Conn) error {
		err := conn.Do(ctx, radix.Cmd(nil, "WATCH", "foo"))
		require.NoError(t, err)

		err = conn.Do(ctx, radix.Cmd(nil, "MULTI"))
		require.NoError(t, err)

		err = conn.Do(ctx, radix.Cmd(nil, "GET", "foo"))
		require.NoError(t, err)

		err = conn.Do(ctx, radix.Cmd(nil, "GET", "foo"))
		require.NoError(t, err)

		err = conn.Do(ctx, radix.Cmd(nil, "GET", "foo"))
		require.NoError(t, err)

		fooWatched <- struct{}{}
		<-fooSet

		var foo1, foo2, foo3 string
		var result radix.Maybe
		result.Rcv = radix.Tuple{&foo1, &foo2, &foo3}

		err = conn.Do(ctx, radix.Cmd(&result, "EXEC"))
		require.NoError(t, err)

		assert.True(t, result.Null)
		assert.Zero(t, foo1)
		assert.Zero(t, foo2)
		assert.Zero(t, foo3)

		return nil
	}))
	require.NoError(t, err)
}()

go func() {
	defer waitGroup.Done()

	err := client2.Do(ctx, radix.WithConn("", func(ctx context.Context, conn radix.Conn) error {
		<-fooWatched

		err := conn.Do(ctx, radix.Cmd(nil, "SET", "foo", "bar"))
		require.NoError(t, err)

		fooSet <- struct{}{}

		return nil
	}))
	require.NoError(t, err)
}()

waitGroup.Wait()
```

**Comment by mediocregopher** [comment]
Hello @golane-lucas , thank you for the kind words about radix :)

This is the intended behavior of `Maybe`. As the docs state:

> When unmarshaling takes place Maybe will **also** populate its other fields accordingly.

So unmarshaling into `Rcv` always takes place.

What I would do for your use-case is to first check the `Null` field of the `Maybe`, and only if that's false check for the error.

```
if result.Null {
    // EXEC returned NULL
} else if err != nil {
    // something has actually gone wrong
}
```

`Null` could only be true if a proper response was successfully returned, so in this case the error _must_ be the unmarshal error.

Hope that helps!
