### ISSUE TITLE
Unsubscribe All is not available in v3

### ISSUE THREAD

**Issue by MoDa89** [mediocregopher/radix#315]
Hi @mediocregopher,

I noticed Unsubscribe() in v3 doesn't issue a UnsubscribeAll to server in case channelNames array is empty. I know it's available in v4, but I can't move to v4 with live loads at the moment, is there any workaround this one for v3?

Thank you.

**Comment by mediocregopher** [comment]
Hi @MoDa89 , unfortunately I think that would constitute a backwards incompatible change. It's possible that someone is calling `Unsubscribe` with a variable number of channels as an argument, and has relied on the fact that an empty set of channels is essentially a no-op. I agree it _should_ work the way that v4 works, but I think we're stuck with it.

In reviewing your request I noticed that the logic in v4 isn't _quite_ right (#318), so thanks for making me look into it :)
