### ISSUE TITLE
Not able to connect to Azure Redis

### ISSUE THREAD

**Issue by SudhakarSundar** [mediocregopher/radix#319]
Iam using the Radix to connect to Azure redis cache, I'am always getting the below error

time="2022-06-02T12:50:23-05:00" level=fatal msg="no pools available"
exit status 1

I was using github.com/mediocregopher/radix/v3 v3.4.1 and then upgraded to github.com/mediocregopher/radix/v3 v3.8.0 but the issue is still the same.

Iam able to connect to a standalone Redis but facing this issue while connecting to azure redis cache. Is there any limitation on the same.

My connection code is as below

// this is a ConnFunc which will set up a connection which is authenticated
// and has a 1 minute timeout on all operations
func CustomConnFunc(network, addr string) (radix.Conn, error) {
	return radix.Dial(network, addr,
		radix.DialTimeout(1*time.Minute),
		radix.DialAuthPass(redisPass),
	)
}

func CreateCluster(redisMasters []string, redisAuth string) error {

	redisPass = redisAuth

	// this cluster will use the ClientFunc to create a pool to each node in the
	// cluster. The pools also use our customConnFunc, but have more connections
	poolFunc := func(network, addr string) (radix.Client, error) {
		return radix.NewPool(network, addr, 100, radix.PoolConnFunc(CustomConnFunc))
	}

	c, err := radix.NewCluster(redisMasters, radix.ClusterPoolFunc(poolFunc))
	if err != nil {
		log.Fatal(err)
	}

	Cluster = c

	return err
}

**Comment by mediocregopher** [comment]
Hi @SudhakarSundar, I just pushed up a commit which improves the error handling in `NewCluster`, it should return a more useful error now which might help you figure our why you can't connect. Feel free to re-open the issue if you still need help debugging it.
