### ISSUE TITLE
Preventing unnecessary connections open and close when initializing a cluster

### ISSUE THREAD

**Issue by drakeeeleee** [mediocregopher/radix#334]
* Problem
  * The current code can make connections open and closed them unnecessarily, when the redis cluster's addr is a domain name, not ip.
  * For example, there is a cluster having 2 nodes. And [`clusterAddr`](https://github.com/mediocregopher/radix/blob/682f25c57e96c703442d538c9c9e529435839c01/cluster.go#L181) is `redis-node1.infra.com`. 
    * redis-node1.infra.com - 10.0.0.1
    * redis-node2.infra.com - 10.0.0.2
  * Then it makes the connection `redis-node1.infra.com` at [here](https://github.com/mediocregopher/radix/blob/682f25c57e96c703442d538c9c9e529435839c01/cluster.go#L211)
  * And then it opens the connections `10.0.0.1` and `10.0.0.2`, and closes `redis-node1.infra.com` at [here](https://github.com/mediocregopher/radix/blob/682f25c57e96c703442d538c9c9e529435839c01/cluster.go#L470)

* Causes
  * `CLUSTER SLOTS` command always returns their IP addresses. So the connections are made always by using the IPv4s at [here](https://github.com/mediocregopher/radix/blob/682f25c57e96c703442d538c9c9e529435839c01/cluster.go#L230)
  * But `clusterAddr` can be `domain name` and the pool can be initialized by the domain name.
  * So duplicated connection of `domain name` and `its ip` is unnecessarily opened and closed.

* Suggestion
  * Suggestion 1) When making new connection [here](https://github.com/mediocregopher/radix/blob/682f25c57e96c703442d538c9c9e529435839c01/pool.go#L456), if `p.addr` is a domain name, `p.addr` can be replaced to `c`'s network address.
  * Suggestion 2) If `p.addr` is a domain name when initializing the cluster, we can resolve it at first. I recommend this.

**Comment by mediocregopher** [comment]
@drakeeeleee Can you describe what sorts of issues these extra connections are causing for you? It's true there is probably a way to initialize the cluster without creating these extra connections, but it would involve introducing more complexity to `Cluster` (which is complex enough, imo). So unless you're attempting to fix a real issue, and there's no other way around that issue, then I don't know that this is worth it.

**Comment by mediocregopher** [comment]
@drakeeeleee I'm going to go ahead and close this, feel free to re-open if you'd like to continue the conversation :pray:

**Comment by drakeeeleee** [comment]
@mediocregopher Thanks for your response. The reason why I check it is below.

my environment suffers from lots of redis connection issues beyond 10k. So I look down what happen in detail in that situation and add some unit tests related the connections. In that process, I found this issue.

I hope this problem is fixed. But if you're worried about the increasing complexity, now is good enough.
If you understand my situation and agree with need for solving this issue, feel free to tell me :bow:
