### ISSUE TITLE
sentinel master connection get's closed state

### ISSUE THREAD

**Issue by mrkmrtns** [mediocregopher/radix#336]
## Background
We have been happily using `radix` in production almost a year with `sentinel` (2 slaves, 1 master - for both `sentinels` and `redis` instances themself as well). Very beginning we randomly discovered issue when `redis` instances were changed in production (for example some `redis` pods got killed and newone was created) then sometimes underlying `redis` connection stopped working. Each `redis` command got error `closed`. After digging at that time I discovered that this error is defined here:
https://github.com/mediocregopher/radix/blob/84dff11dc04084d1d5f3003d5b50535d4165ffd4/internal/proc/proc.go#L13 - so something closed that connection for some reason.

Nevertheless as we did not have much time then to dig more we made workaround - when `redis` command get's such error we close `sentinel` client, make newone and repeat command - this has been worked well without any issues already a year, but it did not seem right that such thing happened in first place.

Lately I started to dig in again and restarting `redis` instances in our `test` kubernetes cluster and problem was pretty much repeatable - at some moment `master` connection was `closed` and all further commands ended up with `closed` error. I started to debug `radix` and tried to understand what exactly happens and I discovered possible problem.

## Problem
Basically problem comes from here:
https://github.com/mediocregopher/radix/blob/84dff11dc04084d1d5f3003d5b50535d4165ffd4/sentinel.go#L218

Function `func (sc *Sentinel) client(ctx context.Context, addr string) (Client, error)` is used for two things:
1. discover `slave` instance for `DoSecondary` command when passed `addr` is empty
2. ensure that `client` exists when `sentinel` is created and in `innerSpin`

Basically let's imagine that we have three redis instances, and `clients` mapping looks like this in the beginning:
1. `1.1.1.1:6379` - `master` - client `addr` 1.1.1.1:6379
2. `1.1.1.2 :6379` - `slave` - client `addr` 1.1.1.2:6379
3. `1.1.1.3 :6379` - `slave` - client `addr` 1.1.1.3:6379

Problem seems to happen when first new slave is made and then code in line `218` does not make for it new connection, instead it uses `master` connection for that. For example new connection is made and mapping looks like this:
`1.1.1.4 :6379` - `slave` - client `addr` 1.1.1.1:6379 (uses same client as current `master`)

Now if later this `pod` is removed for whatever reason then in `ensureClients` function detects that this `connection` should be closed (happens here: https://github.com/mediocregopher/radix/blob/84dff11dc04084d1d5f3003d5b50535d4165ffd4/sentinel.go#L331). But as this points to `master` connection then actually `master` is closed. From now all requests to master using actual `master` mapping `1.1.1.1:6379` - `master` - client `addr` 1.1.1.1:6379 end up with `closed` error.

As I'm suspicious why it's not discovered by others then maybe I'm missing totally here something.

## Solution
Potential solution in PR  - https://github.com/mediocregopher/radix/pull/335

Basically this PR changes littlebit `client` function logic. It only sets `client` to `master` forcefully when `addr` was empty (and if no `slave` client was found like before) - meaning `DoSecondary` was called. In other cases it actually tries to find `client` by it's correct `addr`. If it's not found then new client is made what should be correct behavior imo.

We tested that patch out in our test Kubernetes cluster and we made multiple rounds of killing all `redis` instances - now everything worked as expected, no `closed` errors anymore.

Also all tests are passing as before.

Any comments, questions and ideas are welcome.

**Comment by marekmartins** [comment]
sorry for tagging @mediocregopher , but maybe You can take a look 🥺 
yesterday I added this issue as I missed the correct procedure first, there is linked PR

would like to get some feedback how we can go forward as it's real problem for us

**Comment by mrkmrtns** [comment]
sorry for tagging @mediocregopher , but maybe You can take a look 🥺 
yesterday I added this issue as I missed the correct procedure first, there is linked PR

would like to get some feedback how we can go forward as it's real problem for us

**Comment by mediocregopher** [comment]
Hello! Thank you for taking the time to debug and fix this issue. I'll be back from holiday in the middle of the month, I'll be able to take a look then. Sorry for the delay.

**Comment by mediocregopher** [comment]
Just merged the fix, this was some great bit of debugging @mrkmrtns , thank you so much for the help! Can you do a final check to make sure that the master branch is working for you? If so I'll tag a new release.

**Comment by mediocregopher** [comment]
Ah sorry, closed by accident.

**Comment by marekmartins** [comment]
will do tomorrow 👍

**Comment by mrkmrtns** [comment]
You're welcome!
will check tomorrow 👍

**Comment by mrkmrtns** [comment]
@mediocregopher so I tested again with latest master, we killed one by one all `sentinels` and `redis` instances in Kubernetes cluster and no issues.
Now all works as expected!

**Comment by marekmartins** [comment]
@mediocregopher when You plan to make release?

**Comment by mrkmrtns** [comment]
@mediocregopher when You plan to do release?

**Comment by mediocregopher** [comment]
@mrkmrtns v4.1.2 has been tagged.
