### ISSUE TITLE
Umarshal failures after Clustered Redis Master failover

### ISSUE THREAD

**Issue by bmabryvs** [mediocregopher/radix#337]
We saw continuous, unexpected errors occur in an application using radix v4.1.1 connected to a clustered redis after a redis master failover:

`response returned from Conn: unmarshaling message off Conn: message body "PONG", can't unmarshal into *map[string]string`

**To elaborate**:

We saw the following two error types occur in an application after a redis master failure:

- `command ["HMSET" "id" "test" "value"] in pipeline returned error: CLUSTERDOWN The cluster is down`
- `unmarshaling message off Conn: EOF `

These errors may be reasonably expected when a master goes down. However, the redis nodes then elected and failed over to a new master, and we then saw a slow trickle of unmarshal failures like:

- `response returned from Conn: unmarshaling message off Conn: message body "PONG", can't unmarshal into *map[string]string`
- `response returned from Conn: unmarshaling message off Conn: message body "0", can't unmarshal into *map[string]string`
- etc.

These occurred intermittently until we made the decision to restart the applications that were affected. After restart, the unmarshal errors stopped being logged.

A short analysis of the issue revealed around ~1% of requests to redis were affected by the unmarshal issues. Based on the intermittent nature, and the resolution on restart, it would appear that a few redis connections had gotten stuck in a bad state. Possibly similar to what was reported in: https://github.com/mediocregopher/radix/issues/313. However, the application was using v4.1.1 which includes the fix for that issue.

**To recreate**:

I've been able to reproduce this issue using a locally clustered redis, and boiled it down to the below code to re-create with a high degree of reliability. Run the cluster, run the test code below, and at any point, kill a redis master node. After the redis nodes stabilize, I see intermittent failures due to the unmarshal issues mentioned above.

However, I haven't had the chance to identify where/(if?) the connections may be getting into a bad state.

```
logger.Info("Start redis spam")

for i := 0; i < 1000; i++ {
	go simulateReq(cluster, logger, i)
	time.Sleep(50 * time.Millisecond)
}


// Simulate a request that makes a couple redis calls
func simulateReq(cluster *radix.Cluster, logger *zap.SugaredLogger, iteration int) {
	loopID := fmt.Sprintf("Loop%d", iteration)
	loopCtx, cancel := context.WithTimeout(context.Background(), time.Millisecond*10000)
	defer cancel()

	actionSet := radix.Cmd(nil, "HMSET", loopID, "test", "value", "another", "here")
	actionExpire := radix.Cmd(nil, "PEXPIRE", loopID, "1500")
	p := radix.NewPipeline()
	p.Append(actionSet)
	p.Append(actionExpire)
	err := cluster.Do(loopCtx, p)
	if err != nil {
		logger.Error(loopID, zap.Error(err))

		return
	}

	var m map[string]string
	err = cluster.Do(loopCtx, radix.Cmd(&m, "HGETALL", loopID))
	if err != nil {
		logger.Error(err)

		return
	}

	if (iteration % 100) == 0 {
		logger.Info(loopID)
	}
}
```

**Comment by mediocregopher** [comment]
Hello bmabryvs, thanks for you bringing this up a d coming up with a reproducible test case! I recently refactored the Conn code due to a similar issue which was brought up. That change is on master at commit 84dff11dc04084d1d5f3003d5b50535d4165ffd4, but not yet tagged in a release. Could you let me know if that fixes the issue? If not I'll need to investigate further when I'm back from vacation.

**Comment by bmabryvs** [comment]
@mediocregopher thanks for the quick response! I grabbed the latest commit you mentioned on the v4 branch and added it to both the boiled down test case and the application that originally encountered this failure mode.

From what I can see, your latest commit also fixes the issue I encountered. The refactored `conn` package does appear to resolve the underlying issue of connections getting into a bad state.  Several re-tests have shown no error messages after the redis nodes stabilize after a master failure.

I'll try pinning to that commit for now.

Sorry to bother you on your vacation at all here, but I am curious if you thought any other changes are needed before that refactor is ready for a release?

**Comment by mediocregopher** [comment]
@bmabryvs that's great to hear! As far as when it will be tagged in a
release, I like to let changes wait a little while before tagging, to try
and maximize the number of solved issues which can get included. As it
stands I would like to address #336 before tagging, though I haven't had a
chance to look at it in-depth yet. I should be able to next week.

**Comment by mediocregopher** [comment]
@bmabryvs v4.1.2 has been tagged.
