### ISSUE TITLE
pubsub is not thread safe

### ISSUE THREAD

**Issue by mrkmrtns** [mediocregopher/radix#338]
## Problem
We discovered in testing phase that `pubsub` is not thread safe. We use persistent pubsub, but by code seems that it does not matter and regular is affected the same way. Problem seems to come from that internal maps `psubs` and `subs` are not protected by mutex or anything like this:
https://github.com/mediocregopher/radix/blob/402e6192db4b167bd130085b9014251976740aae/pubsub.go#L514

Should it be thread safe? I can help with PR and protect it with `rwmutex` if needed as it's important for us.

We can't also protect outside with `mutex` because of function:
`func (p *persistentPubSubConn) refresh(ctx context.Context) error {` as it read's those maps and we are not controlling when it happens.

**Comment by mediocregopher** [comment]
Hi @mrkmrtns , PubSubConn is not intended to be thread-safe and is explicitly documented as not being so:

```
// PubSubConn wraps an existing Conn to support redis' pubsub system. Unlike
// Conn, a PubSubConn's methods are _not_ thread-safe.
```

You can easily wrap the interface in your own code-base in order to make it thread-safe, if you care to, but it's not something I'm looking to support at this time.

**Comment by mrkmrtns** [comment]
Sorry I missed that :( 
Thank You for fast response, I will wrap interface.

**Comment by mrkmrtns** [comment]
Sorry, reopening as I need advice 🙏 
How can I wrap it, especially `Next` call seems problematic to me.
This touches map here:
https://github.com/mediocregopher/radix/blob/402e6192db4b167bd130085b9014251976740aae/pubsub.go#L369

I can't very well wrap `Next` into any mutex, it would block all `subscribe` and `unsubscribe` calls what need also that `mutex`.
The thing is `Next` blocks unknown time.

For me seems that only inside `radix` library it would be easy to do with `rwmutex` or use some concurrency safe and performant `Map`. Either way if You decide that You could support it then judging by code it's very easy to add without affecting functionality and I can prepare PR.

Nevertheless maybe I'm missing here something. Any ideas, proposals? 🥺 
Just the thing is that we need solution for subscribing and unsubscribing after we are already listening `Next` in loop.

**Comment by mrkmrtns** [comment]
Anyway who ever needs it. We ended up copying `pubsub.go` over and modifying it our own side and replaced `map` with thread safe version.
