### ISSUE TITLE
Canceling a blocking operation with no timeout leaves the connection hanging

### ISSUE THREAD

**Issue by sebc-vm** [mediocregopher/radix#344]
When the context passed to a blocking Redis command with no timeout is canceled, I would expect the command to terminate immediately and the connection to be released back to the pool.

However, what I observe is that while the call terminates, the connection does not appear to be released to the pool.  Once the pool is exhausted, further calls also hang even if the context is canceled.

Here is a short program reproducing these issue:

```go
package main

import (
	"context"
	"log"
	"github.com/mediocregopher/radix/v4"
	"time"
)

func main() {
	rc, err := (radix.PoolConfig{Size: 2}).New(context.Background(), "tcp", "127.0.0.1:6379")
	if err != nil {
		panic(err)
	}
	for {
		ctx, _ := context.WithTimeout(context.Background(), 1*time.Second)
		var rcv []string
		err := rc.Do(ctx, radix.Cmd(&rcv, "BLPOP", "foo", "0"))
		if err != nil {
			log.Printf("error: %v", err)
		}
	}
}
```

The program will print as many errors as the pool size, then hang indefinitely. This behavior is observed with radix v4.1.3, Go v1.20.5, Redis v7.0.11, on Arch Linux.

The documentation does not seem to discuss this situation.

I am wondering if radix should be expected to immediately close the connection when the context is canceled, and re-open a connection in the background to avoid exhausting the pool.

It may also make sense for context cancellation to interrupt operations waiting for a connection from the pool, though this is a separate issue.

A work-around in my application is to use a large enough pool and set a short timeout on blocking operations and repeat them, but this is not perfect.

A fix for these issues would be greatly appreciated.

**Comment by mediocregopher** [comment]
Hi @sebc-vm , thanks for the detailed bug report :pray: 

> I am wondering if radix should be expected to immediately close the connection when the context is canceled, and re-open a connection in the background to avoid exhausting the pool.

At a high level yes, that would be my expectation as well, there seems to be something wrong with the reconnect logic. I'll try to get to this sometime in the next week or so.

> It may also make sense for context cancellation to interrupt operations waiting for a connection from the pool, though this is a separate issue.

That's a good point to bring up, I'll have to look into that as well.

**Comment by mediocregopher** [comment]
@sebc-vm I have pushed a commit to master which I believe fixes this issue. If you could check it out on your end, I'll tag a release once we close this ticket.

**Comment by sebc-vm** [comment]
@mediocregopher I checked out the commit, tested the changes, and can confirm that it does fix the problem. Thank you so much!

**Comment by mediocregopher** [comment]
Release tagged :rocket:
