### ISSUE TITLE
v4: is there any way to run `--cluster check/fix` commands

### ISSUE THREAD

**Issue by 4n4nd** [mediocregopher/radix#352]
In this scaling guide: https://redis.io/docs/management/scaling/, there are a few commands being used to check the redis cluster status and fixing issues. Is how can these be executed using the radix client?

**Comment by mediocregopher** [comment]
Hi @4n4nd, the `--cluster check/fix` options described in that document are part of the `redis-cli` program, which is usually shipped with the redis server itself (details depend on your operating system). radix can only issue individual [redis commands](https://redis.io/commands/), and there's no individual command for check/fix.

You _could_ theoretically figure out what commands `--cluster check/fix` is performing, and then emulate that using radix, but you'd have to look at the redis-cli source code to figure it out; it's not something radix supports natively (nor any other redis driver, I'd expect).

Hope this helps!

**Comment by 4n4nd** [comment]
That makes sense. Thanks for your help!
