### ISSUE TITLE
v3: 2 separate connections for issuing regular commands and persistentpubsub ?

### ISSUE THREAD

**Issue by yash-nisar** [mediocregopher/radix#353]
Hi, we have a use case where we're Redis to issue regular commands for rate limiting and listening to a channel for expired key events. Currently, we are creating 2 connections.

I wanted to ask if the same connection can be re-used ? What is the recommendation ?

I also saw that if the same connection is re-used, it will anyway create a new connection ?
```
p := &persistentPubSub{
  dial:    func() (Conn, error) { return opts.connFn(network, addr) },
  opts:    opts,
  subs:    chanSet{},
  psubs:   chanSet{},
  cmdCh:   make(chan pubSubCmd),
  closeCh: make(chan struct{}),
}
```

I'm asking because we're trying to use entra id authentication which will force us to send AUTH periodically before the token expires else the connection would be terminated by Azure Redis.

@mediocregopher Any thoughts ?

**Comment by mediocregopher** [comment]
Hi @yash-nisar !

> I wanted to ask if the same connection can be re-used ? What is the recommendation ?

Unfortunately no, the connection within PubSubConns can't be extracted in any way.

> I also saw that if the same connection is re-used, it will anyway create a new connection ?

I'm not sure what you mean by this... if you're referring to the `dial` field, that is only called if there's been an error in the underlying connection and persistent pub sub conn is creating a new connection.

>  send AUTH periodically before the token expires else the connection would be terminated by Azure Redis.
There is certainly no _nice_ way to do this. I can offer a possible hacky solution, which I haven't tested (and can't test, cause I don't have an Azure account). If it doesn't work then hopefully it at least displays the theory:

```go
type hackyConn struct {
    radix.Conn
    l sync.Mutex
    stopCh chan struct{}
}

// newHackyConn is a radix.ConnFunc
func newHackyConn(network, addr string) (radix.Conn, error) {
    inner, err := radix.Dial(network, addr)
    if err != nil {
        return nil, err
    }

    conn := &hackyConn{
        Conn: inner,
        stopCh: make(chan struct{}),
    }

    go func() {
        t := time.NewTicker(1 * time.Minute)
        defer t.Stop()

        for {
            select {
            case <-t.C:
                err := conn.Encode(radix.Pipeline(
                    radix.Cmd(nil, "CLIENT", "REPLY", "SKIP"),
                    radix.Cmd(nil, "AUTH", "whatever"),
                ))
                if err != nil {
                    // TODO HANDLE ERROR, log or something
                }
            case <-conn.stopCh:
                return
            }
        }
    }()

    return conn, nil
}

func (c *hackyConn) Encode(m resp.Marshaler) error {
    c.l.Lock()
    defer c.l.Unlock()
    return c.inner.Encode(m)
}

func (c *hackyConn) Close() error {
    close(c.stopCh)
    return c.inner.Close()
}
```

You would then pass `newHackyConn` into the persistent pub sub conn via PersistentPubSubConnFunc.

The lock around `Encode` is necessary because the PubSubConn may also be trying to use Encode to write a Ping message at the same time, and that would cause a panic. Luckily PubSubConn never uses `Do`, or I don't think this solution would be possible.

The `CLIENT REPLY SKIP` might not be necessary, but it should at least not hurt anything.

Hopefully this helps! I'd be curious if it works, if not I might be able to help more but it's also possible this just can't be done.

**Comment by yash-nisar** [comment]
Hi @mediocregopher, thanks for getting back to me !
Here's what I'm trying to do:

This client is then returned to be used to issue regular redis commands: 
```
df := func(network, addr string) (radix.Conn, error) {

	dialOpts = append(dialOpts, radix.DialTimeout(1*time.Minute),radix.DialAuthUser(clientID, accessToken.Token), radix.DialUseTLS(tlsConfig))

	connFn, err := radix.Dial(network, addr, dialOpts...)
	if err != nil {
		return nil, err
	}
	
	once.Do(func() {
		go refreshTokenPeriodically(ctx, accessToken, connFn, clientID)
	})
	
	return connFn, nil
}

opts := []radix.PoolOpt{radix.PoolConnFunc(df), radix.PoolWithTrace(poolTrace(&stats, healthCheckActiveConnection, srv))}

poolFunc := func(network, addr string) (radix.Client, error) {
	return radix.NewPool(network, addr, poolSize, opts...)
}

client, err = radix.NewCluster(urls, radix.ClusterPoolFunc(poolFunc))
```
I have also created another connection (separately for pubsub) to listen to keyevent notifications:
```
// Every node of a Redis cluster generates events about its own subset of the keyspace 
// as described above. However, unlike regular Pub/Sub communication in a cluster, events' 
// notifications are not broadcasted to all nodes. Put differently, keyspace events are 
// node-specific. This means that to receive all keyspace events of a cluster, clients need 
// to subscribe to each of the nodes.

topo := client.(*radix.Cluster).Topo().Primaries()
msgCh := make(chan radix.PubSubMessage)

dfPubSub := func(network, addr string) (radix.Conn, error) {
	dialOpts = append(dialOpts, radix.DialTimeout(1*time.Minute))

	connFn, err := radix.Dial(network, addr, dialOpts...)
	if err != nil {
		return nil, err
	}

	once.Do(func() {
		go refreshTokenPeriodically(ctx, accessToken, connFn, clientID)
	})

	return connFn, nil
}

// create a connection to each primary over which to subscribe to keyspace changes
for _, clusterNode := range topo {
	pubSubConn := radix.PersistentPubSub(redisSocketType, clusterNode.Addr, dfPubSub)

	// there's no need to check errors from PersistentPubSub, it will always be nil
	pubSubConn.Subscribe(msgCh, "__keyevent@0__:expired")
}

// Wait forever receiving PubSub messages
go func() {
	for {
		select {
		case msg := <-msgCh:
			expiredKey := string(msg.Message)
			tenantID := strings.Split(expiredKey, "/")[0]
			checkError(client.Do(radix.Cmd(nil, "SREM", tenantID, expiredKey)))
		case <-ctx.Done():
			return
		}
	}
}()
```
So my question is:
1. Can I use df at both places instead of creating a new dfPubSub ? Is this Conn responsible for creating a connection ?
2. My concern is if I have 2 connections, I'll have to create 2 subroutines to call AUTH separately. I'm trying to understand if this can be avoided.

**Comment by yash-nisar** [comment]
> Hi @yash-nisar !
> 
> > I wanted to ask if the same connection can be re-used ? What is the recommendation ?
> 
> Unfortunately no, the connection within PubSubConns can't be extracted in any way.
> 
> > I also saw that if the same connection is re-used, it will anyway create a new connection ?
> 
> I'm not sure what you mean by this... if you're referring to the `dial` field, that is only called if there's been an error in the underlying connection and persistent pub sub conn is creating a new connection.
> 
> > send AUTH periodically before the token expires else the connection would be terminated by Azure Redis.
> > There is certainly no _nice_ way to do this. I can offer a possible hacky solution, which I haven't tested (and can't test, cause I don't have an Azure account). If it doesn't work then hopefully it at least displays the theory:
> 
> ```go
> type hackyConn struct {
>     radix.Conn
>     l sync.Mutex
>     stopCh chan struct{}
> }
> 
> // newHackyConn is a radix.ConnFunc
> func newHackyConn(network, addr string) (radix.Conn, error) {
>     inner, err := radix.Dial(network, addr)
>     if err != nil {
>         return nil, err
>     }
> 
>     conn := &hackyConn{
>         Conn: inner,
>         stopCh: make(chan struct{}),
>     }
> 
>     go func() {
>         t := time.NewTicker(1 * time.Minute)
>         defer t.Stop()
> 
>         for {
>             select {
>             case <-t.C:
>                 err := conn.Encode(radix.Pipeline(
>                     radix.Cmd(nil, "CLIENT", "REPLY", "SKIP"),
>                     radix.Cmd(nil, "AUTH", "whatever"),
>                 ))
>                 if err != nil {
>                     // TODO HANDLE ERROR, log or something
>                 }
>             case <-conn.stopCh:
>                 return
>             }
>         }
>     }()
> 
>     return conn, nil
> }
> 
> func (c *hackyConn) Encode(m resp.Marshaler) error {
>     c.l.Lock()
>     defer c.l.Unlock()
>     return c.inner.Encode(m)
> }
> 
> func (c *hackyConn) Close() error {
>     close(c.stopCh)
>     return c.inner.Close()
> }
> ```
> 
> You would then pass `newHackyConn` into the persistent pub sub conn via PersistentPubSubConnFunc.
> 
> The lock around `Encode` is necessary because the PubSubConn may also be trying to use Encode to write a Ping message at the same time, and that would cause a panic. Luckily PubSubConn never uses `Do`, or I don't think this solution would be possible.
> 
> The `CLIENT REPLY SKIP` might not be necessary, but it should at least not hurt anything.
> 
> Hopefully this helps! I'd be curious if it works, if not I might be able to help more but it's also possible this just can't be done.

So in our case, do you think I can use the `hackConn` for both pubsub and issuing regular redis commands ?

**Comment by yash-nisar** [comment]
Btw, inspiration was taken from this: https://github.com/envoyproxy/ratelimit/blob/ca55e1b31d023d8b8aedb8a21ca3b769fb632e95/src/redis/driver_impl.go#L73

**Comment by yash-nisar** [comment]
Thanks @mediocregopher !
