### ISSUE TITLE
Redis stream additions

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#47]
This proposal isn't full-fledged as is but is meant as a starting point.

### Problem

Redis 5 is out and we can finally use streams. Unfortunately the values returned by the stream commands are quiet more complex than those returned by most other commands, which makes them awkward to use with this package, especially when efficiency is important (which is quiet common when using Redis, at least for my use cases).

### Examples

`XRANGE` returns an (RESP) array of "stream entries" which are themselves arrays of 2 elements of which the first is the entry ID and the second another array of key-value pairs. The entry ID consists of two unsigned 64 bit integers (time and sequence number) combined with a dash.

Also when paginating a stream via `XRANGE` the entry IDs are inclusive so one must increment (or decrement if using `XREVRANGE`) the ID which means parsing the ID, incrementing/decrementing the sequence part and, if the value over- or underflows, incrementing/decrementing the time part and setting the sequence part to 0/`math.MaxUint64`.

```
> XRANGE somestream - +
1) 1) 1526985054069-0
   2) 1) "duration"
      2) "72"
      3) "event-id"
      4) "9"
      5) "user-id"
      6) "839248"
2) 1) 1526985069902-0
   2) 1) "duration"
      2) "415"
      3) "event-id"
      4) "2"
      5) "user-id"
      6) "772213"
... other entries here ...
```

`XREAD` and `XREADGROUP` return an array of 2 element arrays that consist of the stream group and an array of entries in the format returned by `XRANGE`.

```
> XREAD COUNT 2 STREAMS mystream writers 0-0 0-0
1) 1) "mystream"
   2) 1) 1) 1526984818136-0
         2) 1) "duration"
            2) "1532"
            3) "event-id"
            4) "5"
            5) "user-id"
            6) "7782813"
      2) 1) 1526999352406-0
         2) 1) "duration"
            2) "812"
            3) "event-id"
            4) "9"
            5) "user-id"
            6) "388234"
2) 1) "writers"
   2) 1) 1) 1526985676425-0
         2) 1) "name"
            2) "Virginia"
            3) "surname"
            4) "Woolf"
      2) 1) 1526985685298-0
         2) 1) "name"
            2) "Jane"
            3) "surname"
            4) "Austen"
```

There's also `XPENDING` which returns it's response in a different format, depending on how it is used.

```
> XPENDING mystream group55
1) (integer) 1
2) 1526984818136-0
3) 1526984818136-0
4) 1) 1) "consumer-123"
      2) "1"
```

```
> XPENDING mystream group55 - + 10
1) 1) 1526984818136-0
   2) "consumer-123"
   3) (integer) 196415
   4) (integer) 1
```

`XCLAIM` returns output it the same format as `XRANGE` unless the `JUSTID` option is given, in that case only IDs are returned and no key-value pairs.

### Proposal

I propose that we add some convenience types / functions for working with Redis Streams either as part of the radix or resp package, or via a new sub package. Having the stream convenience stuff in an external package would probably deter people from using radix

Also having the functionality here could help with performance (e.g. we could reuse the readUint function for reading the IDs without allocating strings).

Ignoring naming (which is hard!) for now, something like this comes to my mind:

```go
type StreamsEntries map[string]Entries // unmarshals output of XREAD/XREADGROUP
func (StreamsEntries) UnmarshalRESP(*bufio.Reader) error

type Entries []Entry // unmarshals output of XRANGE
func (Entries) UnmarshalRESP(*bufio.Reader) error

type Entry struct {
    ID EntryID
    Fields map[string]string
}
func (Entry) UnmarshalRESP(*bufio.Reader) error

type EntryID struct {
    Time uint64
    Sequence uint64
}

func (EntryID) MarshalRESP(*bufio.Writer) error
func (EntryID) UnmarshalRESP(*bufio.Reader) error
func (EntryID) Prev() EntryID
func (EntryID) Next() EntryID
func (EntryID) Before(EntryID) bool // optional, nice-to-have
```

**Comment by mediocregopher** [comment]
Great proposal, I'm definitely in favor. I have a couple notes:

I basically don't expect anyone to look into the `resp` package unless they're at the level of implementing their own marshalers/unmarshalers, so special-case marshaler/unmarshalers, like `MaybeNil` or this, would go in the `radix` package. We could move the readUint function into an `internal` package, I expect that'll need to be done anyway when resp3 rolls around.

Naming is definitely hard, but it's worth pinning down in the beginning. Imo every name should start with "Stream", so someone perusing the docs can know at a glance whether or not it's important to them, and so it all gets grouped together in the docs (which are sorted alphabetically).

What I would do for this is something like the following:

```go
type StreamEntryID struct {...}
type StreamEntry struct {...}
```

I'm not sure it's actually needed to have `[]StreamEntry` and `map[string][]StreamEntry` be wrapped as their own types, as opposed to having the docs for `StreamEntry` say "For XRANGE use `[]StreamEntry`, for XREAD use...etc". Is avoiding reflection inside `resp2.Any` the main reason you wanted to do that?

Finally, one quick thing, it's not clear to me what the `Before` method of `EntryID` would do, so maybe that should be renamed as well.

Thanks for putting this together, and for keeping up with the stream stuff so closely :P One unrelated thing: I'm considering moving this package to a repo just called `radix`, to account for the module stuff. I haven't totally decided on if that's the right thing to do, I figure I'd leave a note on this repo for a while telling people to switch to there, but I guess keep an eye out in case that happens.

**Comment by nussjustin** [comment]
> We could move the readUint function into an internal package, I expect that'll need to be done anyway when resp3 rolls around.

Yeah, that was my idea, too.

> Naming is definitely hard, but it's worth pinning down in the beginning. Imo every name should start with "Stream", so someone perusing the docs can know at a glance whether or not it's important to them, and so it all gets grouped together in the docs (which are sorted alphabetically).

Agree and I'm okay with the "Stream" prefix.

> I'm not sure it's actually needed to have []StreamEntry and map[string][]StreamEntry be wrapped as their own types, as opposed to having the docs for StreamEntry say "For XRANGE use []StreamEntry, for XREAD use...etc". Is avoiding reflection inside resp2.Any the main reason you wanted to do that?

If I'm not mistaken the `XREAD` response would need to be a `[]map[string][]StreamEntry` where every map would only have 1 entry, which would be quiet inefficient and awkward. 

> Finally, one quick thing, it's not clear to me what the Before method of EntryID would do, so maybe that should be renamed as well.

Before (named after [time.Time.Before](https://golang.org/pkg/time/#Time.Before)) would do a simple less-than comparison. I implemented this once and found it quiet handy, but it's not hard to implement and can be left out or instead we could implement a `Compare` style method that returns -1, 0 or 1 for <, == and >. 

> Thanks for putting this together, and for keeping up with the stream stuff so closely :P

No Problem :-)

**Comment by mediocregopher** [comment]
> If I'm not mistaken the XREAD response would need to be a []map[string][]StreamEntry where every map would only have 1 entry, which would be quiet inefficient and awkward.

Oh you're right, that's annoying >_< how do you feel about `type StreamEntriesByName map[string][]StreamEntry`? It's a long name, but I feel like if it's something shorter like just `StreamEntries` or `StreamRange` it might get confused for being `[]StreamEntry`.

> Before (named after time.Time.Before) would do a simple less-than comparison.

I gotcha, so it'd return a bool. That seems fine to me! Compare doesn't seem necessary, someone could do the same with `Before` and `==` if they need.

**Comment by nussjustin** [comment]
> Oh you're right, that's annoying >_< how do you feel about type StreamEntriesByName map[string][]StreamEntry? It's a long name, but I feel like if it's something shorter like just StreamEntries or StreamRange it might get confused for being []StreamEntry.

Yeah that would be ok.

We could also add a `Scanner` like type for streams that iterates over one or more streams with `XREAD` (or, if a group is set, `XREADGROUP`) and scans into a `[]StreamEntry`. The stream name could be exposed via a method on the type or just as a second (or first) parameter to the `Next` function.

Something like

```go
type StreamScannerOpts struct {
    Streams []string
    Group string // optional
    Noack bool // only used when Group != ""
    Block time.Duration // or maybe "Timeout time.Duration"
    Count int
}

type StreamScanner interface {
    Next(stream *string, entries *[]StreamEntry) bool
    Close() error
}

func NewStreamScanner(c Client, opts StreamScannerOpts) StreamScanner
```

In fact we could even just provide this, *instead* of a `StreamEntriesByName` type.

**Comment by mediocregopher** [comment]
> In fact we could even just provide this, instead of a StreamEntriesByName type.

I really like that! Makes way more sense in terms of usability and naming. Maybe `StreamReader` would be a better name though, since it's not using any of the SCAN calls. But otherwise yeah, this seems like a really good plan.

**Comment by nussjustin** [comment]
I'm considering to change the `Next` method on `StreamReader` to

```go
Next(entries map[string][]StreamEntry) bool
```

The way I initially thought of this, the `StreamReader` would need to buffer everything internally which could give a false sense of efficiency and adds quiet some accounting for this to the code.

Any thoughts?

I also changed `StreamReaderOpts.Streams` to be a `map[string]*StreamEntryID` since having just one start ID (as in my example above) doesn't work and added a `Consumer string` field for the consumer name.

**Comment by mediocregopher** [comment]
> Any thoughts?

That makes sense, it still needs to take in a pointer to the `map[string][]StreamEntry` though, doesn't it?

**Comment by nussjustin** [comment]
> That makes sense, it still needs to take in a pointer to the map[string][]StreamEntry though, doesn't it?

You're right. I also changed the return type to `int` for now, since this works better with how I'm currently reusing maps (resetting all slices to len 0 but not deleting them. so len(entries) never decreases.)

I pushed a WIP StreamReader to my branch, including some small optimizations and a fix to the `BufferedPrefix` function (previously, on unexpected input, the function would just block. No it fails properly). Currently only the `XREAD` case is tested, so `XREADGROUP` specific semantics will probably fail.

**Comment by mediocregopher** [comment]
> You're right. I also changed the return type to int for now, since this works better with how I'm currently reusing maps (resetting all slices to len 0 but not deleting them. so len(entries) never decreases.)

The `len(entries)` would indicate the length of the slice which was filled in for a particular stream, right? And the user would discover which stream that was because it's the only key in the map?

**Comment by nussjustin** [comment]
I currently reuse stream names and entry slices in the map to avoid some allocations. This is just an optimization but this means that `len(*entries)` never decreases. This avoids at least 3 stream allocations per stream read (stream name, map slot, entries slice). The disadvantage is that users need to check every slice in the map for `len(slice) > 0`.

I could change it so the map would only contain the streams with new entries (still reusing map slots at least), but that would cause quite a few more allocations (my current benchmarks, which reads 32 entries, goes from 75 to 140 allocations). What do you think? 

Also after thinking about the return value of `Next` once more, I realised that `int` doesn't really give anything (I got the error checking wrong in my head before. I think), so I changed it back.

**Comment by mediocregopher** [comment]
Rather than have the user deal with the map and parsing it properly, would it instead be better to have `Next` return `(string, []StreamEntry, bool)` or something like that? It'd mean keeping track of the map internally, and perhaps not actually making a call to redis on every call to `Next` (which I think is what you were originally doing), but it would perhaps be less confusing to use and wouldn't require any more allocations than what you're currently doing.

**Comment by nussjustin** [comment]
Next try. The `(string, []StreamEntry, bool)` makes the logic a bit easier, so I went with it for now. I opened a WIP PR (#51). There are still open `TODO`'s, but so far it seems to work, although I don't like how much code the StreamReader implementation has.
