### ISSUE TITLE
Reading response of FT.SEARCH command of redisearch module

### ISSUE THREAD

**Issue by markschmid** [mediocregopher/radix#48]
Again more of a question than an issue (is there a different way to ask questions?).

We're using the redisearch module and the response of the search command [FT.SEARCH](https://oss.redislabs.com/redisearch/Commands/#ftsearch) is defined as follows:

```Array reply, where the first element is the total number of results, and then pairs of document id, and a nested array of field/value.```

I fail to understand which Go slice/map/struct/interface data type i need to hand to the radix.Cmd() for parsing the response into. Any help appreciated and btw, I really like this library.

**Comment by mediocregopher** [comment]
Nope, this is a fine place to ask questions :)

Man, that command's return is unfortunately formatted. You've got a couple options though:

The first is to hand it an `*[]interface{}`, which will populate each element and automatically choose a type based on the redis type being returned:

```go
var ret []interface{}
err := r.Do(radix.Cmd(&ret, "FT.SEARCH", "..."))
```

`ret[0]` will be an `int64` (I think), then `ret[1]` should be a string (a document id), then `ret[2]` a `[]interface{}`, where each element is a `string` (the field/values), then `ret[3]` another document id, etc...

-----

Alternatively, if you don't like the types chosen by radix, you can use the `resp2` package to implement your own unmarshaler, something like this:

```go
type FTSearchRes struct {
    NumResults int
    Results map[string]map[string]string // docID -> field -> value
}

func (ftSearchRes *FtSearchRes) UnmarshalRESP(br *bufio.Reader) error {
    // read off the array head of the outermost array reply
    var header resp2.ArrayHeader
    if err := header.UnmarshalRESP(br); err != nil {
        return err
    }

    // read off first element of the outermost array reply. The Any type automatically handles
    // type conversion and such
    if err := (resp2.Any{I: &ftSearchRes.NumResults}).UnmarshalRESP(br); err != nil {
        return err
    }
    header.N--

    // cycle through rest of the elements in pairs, the first of the pair being the docID,
    // the second being an array of field/value pairs, which can be easily captured by Any.
    ftSearchRes.Results = map[string]map[string]string{}
    for i := 0; i < header.N/2; i++ {
        var docID string
        if err := (resp2.Any{I: &docID}).UnmarshalRESP(br); err != nil {
            return err
        } else if err := (resp2.Any{I: &(ftSearchRes.Results[docID])}).UnmarshalRESP(br); err != nil {
            return err
        }
    }
    return nil
}

// then to use it
var res FTSearchRes
err := r.Do(radix.Cmd(&res, "FT.Search", "..."))
```

That's off the top of my head, so it might not work perfectly, but hopefully it conveys the idea. Let me know if I can clarify it further.

**Comment by markschmid** [comment]
Awesome response, thanks!!
I'm currently going the option 1 route. The response elements are actually []uint8. It's a good exercise for having a closer look at Go data types for me :)

**Comment by mediocregopher** [comment]
Ah that makes sense, `uint8` is the same as `byte`, so those are `[]byte`, which you can easily cast to a `string` if you need. I'll go ahead and close this, let me know if you have any other questions!
