### ISSUE TITLE
Stub Blocks When Running Pipeline Action

### ISSUE THREAD

**Issue by armsnyder** [mediocregopher/radix#49]
The `radix.Stub` `Conn` works fine when its `Do` method is called with a `CmdAction` argument. However, if you call its `Do` with a pipeline (`[]CmdAction`), it blocks indefinitely.

The following code runs and exits correctly:
```go
stub := radix.Stub("", "", func(args []string) interface{} {
	return nil
})
stub.Do(radix.Cmd(nil, "PING"))
stub.Do(radix.Cmd(nil, "PING"))
```
The following code blocks on the call to `Do` and does not exit:
```go
stub := radix.Stub("", "", func(args []string) interface{} {
	return nil
})
stub.Do(radix.Pipeline(radix.Cmd(nil, "PING"), radix.Cmd(nil, "PING")))
```
I think this has to do with how `Stub`'s `Decode` method blocks if its buffer is empty.

**Comment by mediocregopher** [comment]
Hey @armsnyder, thanks for pointing this out! You're right, `Stub` doesn't handle pipeline's correctly. I remember running into this once but I guess I forgot to make a note to come back later and fix it. I'll try to look into it further soon.

**Comment by armsnyder** [comment]
Thanks for the fix!
