### ISSUE TITLE
How to subscribe keyspace notifications in cluster mode?

### ISSUE THREAD

**Issue by kayalardanmehmet** [mediocregopher/radix#54]
I need to listen expired events in my application. As I know, keyspace notifications are node-specific unlike regular pub/sub. So, to catch expired events for all keys I need to attach all nodes in cluster mode. How can I achieve this with radix? I couldn't find any solution.

**Comment by mediocregopher** [comment]
Hi @kayalardanmehmet, thanks for submitting the issue. You could do something approximately like this:

```go

msgCh := make(chan radix.PubSubMessage, 10)
topo := cluster.Topo().Primaries()

// create a connection to each primary over which to subscribe to keyspace changes
for _, clusterNode := range topo {
    pubSubConn := radix.PersistentPubSub("tcp", clusterNode.Addr, nil)

    // there's no need to check errors from PersistentPubSub, it will always be nil
    pubSubConn.Subscribe(msgCh, "__keyspace@0__:mykey")    
}

for msg := range msgCh {
    // handle msg
}
```

Note a couple of things:

- That example subscribes to every primary node in the cluster. If you want only a specific primary, your logic may be different.

- If the cluster topology changes you may have to `Close` the associated `pubSubConn` and resubscribe with a new one. You can check if the cluster topology changes by checking if the return from `Topo` changes.

- each `PubSubMessage` does not contain the node which generated it. If you need that information you'll have to make a different `msgCh` for each node and keep a mapping between them.

Hope this helps!

**Comment by kayalardanmehmet** [comment]
Hi @mediocregopher, thanks for you reply! This was very helpful.
