### ISSUE TITLE
Sentinel Client method leaks secondary pools

### ISSUE THREAD

**Issue by nussjustin** [mediocregopher/radix#56]
Disclaimer: This is all theoretical and I haven't tested it. I only looked at the code and stepped through this scenario in my head.

The [Sentinel.Client](https://godoc.org/github.com/mediocregopher/radix#Sentinel.Client) method says

> NOTE the Client should _not_ be closed.

This can be a problem since Clients to secondaries are created by calling the [SentinelPoolFunc](https://godoc.org/github.com/mediocregopher/radix#SentinelPoolFunc), which is primarily used for creating a long lived pool for connections to the primary and has the same configuration for primaries and secondaries.

If the returned pool for one of the secondaries is not closed, the pool can leak connections (at least for some time, depending on the pool configuration/implementation). But users don't know this and are told to not close the returned Client.

Note that for the case where an user wants a client for the primary they really must not call Close.

This doesn't seem like a big problem to me, since I don't expect many people to manually use connections to secondaries, but is still worth fixing.

I thought about two ways to solve this, but there are probably others:

1. Save (and reuse) the non-primary pools and close them when necessary (on Master change).
2. Always return a fresh Client, using the [SentinelConnFunc](https://godoc.org/github.com/mediocregopher/radix#SentinelConnFunc), even for the primary and tell users to manually close the connections.

**Comment by nussjustin** [comment]
My concrete idea for 1 would be to changes `sc.secsM` to a `map[string]Client` and then add `nil` Clients for new secondaries in `setClients` and `.Close` + `delete` old secondaries from `sc.secsM`. This could even be extended so that all connections (master + secondaries) are handled the same way and `Do` would just basically just do `sc.Client(sc.primAddr)` to get the master connection.

**Comment by mediocregopher** [comment]
Hey @nussjustin, thanks for pointing this out! You're definitely right that the current behavior isn't ideal, I guess I got lazy while implementing what's there. I like your idea to keep open Clients in `secsM`, judging by the TODO I left inside the `Client` method that was my original intention, I just didn't do it >_<

I'll try to tackle this later tonight.
