### ISSUE TITLE
go-redis vs radix performance

### ISSUE THREAD

**Issue by gadelkareem** [mediocregopher/radix#62]
I tested radix against go-redis on a caching library I am developing https://github.com/gadelkareem/cachita and got better results with go-redis. 
go-redis: https://github.com/gadelkareem/cachita/tree/test/go-redis
```
BenchmarkRedisCacheWithInt-8             	     500	   2764354 ns/op	    2525 B/op	      67 allocs/op
BenchmarkRedisCacheWithString-8          	     500	   2927454 ns/op	    2548 B/op	      68 allocs/op
BenchmarkRedisCacheWithMapInterface-8    	     500	   2954466 ns/op	    5167 B/op	      95 allocs/op
BenchmarkRedisCacheWithStruct-8          	     500	   2884623 ns/op	    6802 B/op	     117 allocs/op
```
radix: https://github.com/gadelkareem/cachita/tree/test/radix
```
BenchmarkRedisCacheWithInt-8             	     500	   4158970 ns/op	    2282 B/op	      62 allocs/op
BenchmarkRedisCacheWithString-8          	     300	   4136612 ns/op	    2316 B/op	      63 allocs/op
BenchmarkRedisCacheWithMapInterface-8    	     300	   4150110 ns/op	    4703 B/op	      89 allocs/op
BenchmarkRedisCacheWithStruct-8          	     300	   4274845 ns/op	    6241 B/op	     111 allocs/op
```
I prefer the radix syntax but I had to do the switch for performance. Although I used `FlatCmd` to avoid resp.Marshaler as I am handling it using msgpack.

**Comment by nussjustin** [comment]
The current version of radix does automatic pipelining which improves performance when sending concurrent requests to redis, but negatively effects non-concurrent workloads.

From what I see your benchmarks are all run in a single goroutine. This is basically the worst-case for the automatic pipelining and introduces a high latency overhead for each call do `Do`.

You could try to disable the automatic pipelining using `PoolPipelineWindow(0, 0)` on your Pool.

Alternatively you could change your benchmarks to access the cache concurrently (using e.g. `(*B).RunParallel`) for both radix and go-redis. radix should easily outperform go-redis on concurrent access and you can probably tune the automatic pipelining for even better throughput/latency for your package (by default commands a buffered for up to 150 microseconds, which should work well for most uses but the optimal value depends on your usage and workload).

**Comment by gadelkareem** [comment]
Thanks for your reply. I am actually using RunParallel for most test  https://github.com/gadelkareem/cachita/blob/test/radix/redis_test.go#L10 so it is indeed using concurrency.

Would that change your conclusion?

**Comment by nussjustin** [comment]
Also you should avoid expensive error checks in your benchmarks (testify is quite expensive and requires locks, which whould again serialise the benchmarks even with (*B).RunParallel)

**Comment by gadelkareem** [comment]
Yep! much better results. Thanks for the tips ;)
go-redis: https://github.com/gadelkareem/cachita/tree/test/go-redis
```
BenchmarkRedisCacheWithInt-8             	    3000	    803333 ns/op	    1471 B/op	      43 allocs/op
BenchmarkRedisCacheWithString-8          	    3000	    776620 ns/op	    1479 B/op	      44 allocs/op
BenchmarkRedisCacheWithMapInterface-8    	    3000	    591221 ns/op	    3797 B/op	      68 allocs/op
BenchmarkRedisCacheWithStruct-8          	    3000	    513130 ns/op	    4782 B/op	      74 allocs/op
```
radix: https://github.com/gadelkareem/cachita/tree/test/radix
```
BenchmarkRedisCacheWithInt-8             	    5000	    342156 ns/op	    1122 B/op	      33 allocs/op
BenchmarkRedisCacheWithString-8          	    5000	    321191 ns/op	    1132 B/op	      34 allocs/op
BenchmarkRedisCacheWithMapInterface-8    	    5000	    334021 ns/op	    3212 B/op	      58 allocs/op
BenchmarkRedisCacheWithStruct-8          	    3000	    334561 ns/op	    4101 B/op	      63 allocs/op
```

**Comment by nussjustin** [comment]
^o_o^

**Comment by mediocregopher** [comment]
Glad this got worked out! Gonna go ahead and close it, @gadelkareem feel free to open more issues if you have any other questions/problems.
