### ISSUE TITLE
missing "v3" related while installing

### ISSUE THREAD

**Issue by ictar** [mediocregopher/radix#65]
hello, 
when installing, I meet the problem below:
```
$ go get github.com/mediocregopher/radix
package github.com/mediocregopher/radix/v3/internal/bytesutil: cannot find package "github.com/mediocregopher/radix/v3/internal/bytesutil" in any of:
	/usr/local/go/src/github.com/mediocregopher/radix/v3/internal/bytesutil (from $GOROOT)
	/home/ictar/go_workspace/src/github.com/mediocregopher/radix/v3/internal/bytesutil (from $GOPATH)
package github.com/mediocregopher/radix/v3/resp: cannot find package "github.com/mediocregopher/radix/v3/resp" in any of:
	/usr/local/go/src/github.com/mediocregopher/radix/v3/resp (from $GOROOT)
	/home/ictar/go_workspace/src/github.com/mediocregopher/radix/v3/resp (from $GOPATH)
package github.com/mediocregopher/radix/v3/resp/resp2: cannot find package "github.com/mediocregopher/radix/v3/resp/resp2" in any of:
	/usr/local/go/src/github.com/mediocregopher/radix/v3/resp/resp2 (from $GOROOT)
	/home/ictar/go_workspace/src/github.com/mediocregopher/radix/v3/resp/resp2 (from $GOPATH)
```

is there anyone could help me to find v3 folder?

**Comment by ictar** [comment]
sadly, it also fails:
```
$ go version
go version go1.9.2 linux/amd64
$ go get github.com/mediocregopher/radix/v3
package github.com/mediocregopher/radix/v3: cannot find package "github.com/mediocregopher/radix/v3" in any of:
	/usr/local/go/src/github.com/mediocregopher/radix/v3 (from $GOROOT)
	/home/ictar/go_workspace/src/github.com/mediocregopher/radix/v3 (from $GOPATH)
```

**Comment by nussjustin** [comment]
Please try with Go 1.9.7 or higher. The module support was backported to 1.9.7 and 1.10.3:

> The approach uses the "Major Branch" approach and relies on the "minimal module awareness" that was backported to 1.9.7 and 1.10.3. 

(https://github.com/golang/go/wiki/Modules)

This is also noted in the radix README:

> As long as you are using the latest update of your major go version (1.9.7+, 1.10.3+, 1.11+) the module-aware go get should work correctly with the new import path.

Also please note that radix tries to follow the [official support / release policy of Go](https://golang.org/doc/devel/release.html#policy):

> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

**Comment by ictar** [comment]
Thank you for your reminding.  We don't have upgrade plan for go recently.  Thus unfortunately v3 is not available for us.

**Comment by mediocregopher** [comment]
I'm going to go ahead and close this, unfortunately there's not much which can be done on radix's end for it.
