### ISSUE TITLE
bench result confusing

### ISSUE THREAD

**Issue by shrimptttttttttt** [mediocregopher/radix#67]
I run ```Go go test -v -run=XXX -bench=GetSet -benchmem >/tmp/radix.stat ``` the result is 

```Go
goos: linux
goarch: amd64
pkg: github.com/mediocregopher/radix
BenchmarkSerialGetSet/radix-32             10000            118389 ns/op              68 B/op          4 allocs/op
BenchmarkSerialGetSet/redigo-32            10000            101131 ns/op              86 B/op          5 allocs/op
BenchmarkSerialGetSet/redispipe-32          3000            577234 ns/op             169 B/op          8 allocs/op
BenchmarkSerialGetSet/redispipe_pause0-32                  10000            140855 ns/op             168 B/op          8 allocs/op
BenchmarkParallelGetSet/radix/no_pipelining-32             30000             41502 ns/op             302 B/op          8 allocs/op
BenchmarkParallelGetSet/radix/one_pipeline-32             100000             19035 ns/op             113 B/op          4 allocs/op
BenchmarkParallelGetSet/radix/default-32                  100000             14458 ns/op             155 B/op          4 allocs/op
BenchmarkParallelGetSet/redigo-32                          10000           3131131 ns/op            7998 B/op         28 allocs/op
PASS
ok      github.com/mediocregopher/radix 42.769s
```

While the result in your repo is

```
# go test -v -run=XXX -bench=GetSet -benchmem >/tmp/radix.stat
# benchstat radix.stat
name                                     time/op
SerialGetSet/radix                         89.1µs ± 7%
SerialGetSet/redigo                        87.3µs ± 7%
ParallelGetSet/radix/default-8             5.47µs ± 2%  <--- The good stuff
ParallelGetSet/redigo-8                    27.6µs ± 2%
ParallelGetSet/redispipe-8                 4.16µs ± 3%

name                                      alloc/op
SerialGetSet/radix                          67.0B ± 0%
SerialGetSet/redigo                         86.0B ± 0%
ParallelGetSet/radix/default-8              73.0B ± 0%
ParallelGetSet/redigo-8                      138B ± 4%
ParallelGetSet/redispipe-8                   168B ± 0%

name                                       allocs/op
SerialGetSet/radix                           4.00 ± 0%
SerialGetSet/redigo                          5.00 ± 0%
ParallelGetSet/radix/default-8               4.00 ± 0%
ParallelGetSet/redigo-8                      6.00 ± 0%
ParallelGetSet/redispipe-8                   8.00 ± 0%
```

Why my test results shows ``` Go BenchmarkParallelGetSet/redigo-32 (3131131 ns/op)``` is much worse than ``` Go BenchmarkParallelGetSet/radix/no_pipelining-32(41502 ns/op)``` ????

And your bench result doesn't list the results of radix using pipelining.

**Comment by shrimptttttttttt** [comment]
It seems the redispipe@0.9.0 deps on errorx@v0.1.0, but the errorx@v0.1.0 didn't contains the commit about `RegisterPrintableProperty`..

**Comment by shrimptttttttttt** [comment]
another problem is ```Go BenchmarkParallelGetSet ``` executes failed, error is
```Go
goos: darwin
goarch: amd64
pkg: github.com/mediocregopher/radix/v3
BenchmarkParallelGetSet/radix/no_pipelining-8         	   50000	     24491 ns/op
BenchmarkParallelGetSet/radix/one_pipeline-8          	  300000	      4763 ns/op
BenchmarkParallelGetSet/radix/default-8               	  500000	      3323 ns/op
--- FAIL: BenchmarkParallelGetSet/redigo-8
    bench_test.go:192: read tcp 127.0.0.1:51701->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51700->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51703->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51702->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51704->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51707->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51710->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51708->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51709->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51705->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51706->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51711->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51713->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51712->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51716->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51714->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51715->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51719->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51717->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51720->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51718->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51722->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51721->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51724->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51723->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51725->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51727->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51728->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51726->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51733->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51730->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51731->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51729->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51734->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51735->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51732->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51747->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51739->127.0.0.1:6379: read: connection reset by peer
    bench_test.go:192: read tcp 127.0.0.1:51740->127.0.0.1:6379: read: connection reset by peer
```

**Comment by mediocregopher** [comment]
Hi @shrimptttttttttt! There's a couple things to note:

* Note the line `benchstat radix.stat` in the repo's result, that tool helps format the output of benches. You can add a `-count` argument to the go test call and benchstat will help determine the variability between the different runs as well.

* I'm not entirely sure why redigo is so slow for you, it should come in just faster than the `radix/no_pipelining` benchmark.

* The repo's benchmark does list the result of radix+pipelining, as that's the default (`ParallelGetSet/radix/default`). I left out the other radix benchmarks because I thought they'd only make things more confusing, and they require non-default configuration to produce anyway.

Hope that clears things up a little, let me know if you have any other questions!

**Comment by shrimptttttttttt** [comment]
Thank you for reply.

> Hi @shrimptttttttttt! There's a couple things to note:
> 
> * Note the line `benchstat radix.stat` in the repo's result, that tool helps format the output of benches. You can add a `-count` argument to the go test call and benchstat will help determine the variability between the different runs as well.
> * I'm not entirely sure why redigo is so slow for you, it should come in just faster than the `radix/no_pipelining` benchmark.
> * The repo's benchmark does list the result of radix+pipelining, as that's the default (`ParallelGetSet/radix/default`). I left out the other radix benchmarks because I thought they'd only make things more confusing, and they require non-default configuration to produce anyway.
> 
> Hope that clears things up a little, let me know if you have any other questions!

`Note the line benchstat radix.stat in the repo's result, that tool helps format the output of benches. You can add a -count argument to the go test call and benchstat will help determine the variability between the different runs as well.`

Ok, I got this.

`I'm not entirely sure why redigo is so slow for you, it should come in just faster than the radix/no_pipelining benchmark.`
I'm confused either, I thought redigo shoud have similar performance with radix with no pipeline. And I found out that ``` conn := red.Get() ``` cost huge time, from us to seconds. 

 Another question is the code below doesn't benifit, as ``` pool.MaxActive ``` is zero.  But ```radix``` will create connection when creating a new pool.

```Go
func fillRedigoPool(pool *redigo.Pool) {
	var conns []redigo.Conn
	for pool.MaxActive > pool.ActiveCount() {
		conns = append(conns, pool.Get())
	}
	for _, conn := range conns {
		_ = conn.Close()
	}
}
```


> * The repo's benchmark does list the result of radix+pipelining, as that's the default (`ParallelGetSet/radix/default`). I left out the other radix benchmarks because I thought they'd only make things more confusing, and they require non-default configuration to produce anyway.

Is ```ParallelGetSet/radix/default``` comparing to ```redigo``` fair? because ```ParallelGetSet/radix/default``` has pipeline and bench case of ```redigo``` doesn't have pipeline.

So is it necessary to write some bench cases for ```redigo``` with pipeline, as ```redigo``` supports pipeline too.

Thanks again and look forward to your reply.

**Comment by shrimptttttttttt** [comment]
> At least in my tests for the pipelining, where I played with different pool sizes, prefilling the pool helped give more consistent timings, but I'm not currently sure if this helps with the redigo defaults.

Yeah, I know prefilling the pool will benifit, but the default value of ```pool.MaxActive``` for redigo is zero, and in the cases of ```bench_test.go```you don't set  ```pool.MaxActive``` and you only set ```pool.MaxIdle```, so you don't prefill the pool for redigo actually in your case.

So is this will be better?

```Go
func fillRedigoPool(pool *redigo.Pool) {
	var conns []redigo.Conn

        // use pool.MaxIdle instead of pool.MaxActive
	for pool.MaxIdle > pool.ActiveCount() {
		conns = append(conns, pool.Get())
	}
	for _, conn := range conns {
		_ = conn.Close()
	}
}
``` 

Another difference is my testing server is 32CPUs, and your bench result in radix repo shows your testing server is 8CPUs. So I tried to set ```runtime.GOMAXPROCS(0)``` to 8 manully.

After those two changes, I finally got some bench result seems like make sense

```Go
$go test -v -run=XXX -bench=GetSet -benchmem
goos: linux
goarch: amd64
pkg: github.com/mediocregopher/radix
BenchmarkSerialGetSet/radix-8         	   10000	    122495 ns/op	      68 B/op	       4 allocs/op
BenchmarkSerialGetSet/redigo-8        	   10000	    101563 ns/op	      86 B/op	       5 allocs/op
BenchmarkSerialGetSet/redispipe-8    	    3000	    580200 ns/op	     169 B/op	       8 allocs/op
BenchmarkSerialGetSet/redispipe_pause0-8         	   10000	    140394 ns/op	     168 B/op	       8 allocs/op
BenchmarkParallelGetSet/radix/no_pipelining-8    	   50000	     37119 ns/op	     143 B/op	       6 allocs/op
BenchmarkParallelGetSet/radix/one_pipeline-8     	  100000	     17783 ns/op	      81 B/op	       4 allocs/op
BenchmarkParallelGetSet/radix/default-8          	  100000	     14403 ns/op	     107 B/op	       4 allocs/op
BenchmarkParallelGetSet/redigo-8                 	   10000	    120410 ns/op	    2031 B/op	      11 allocs/op
BenchmarkParallelGetSet/redispipe-8              	  100000	     14073 ns/op	     183 B/op	       8 allocs/op
```

So can you do some bench result under 32CPUs server?  Seems like the performance decreases hugely for redigo with number of goroutine increasing.

 

> Yes, it is fair. redigo only supports manual pipelining (which radix supports to), but the pipelining in the benchmarks is about automatic pipelining, as done by redispipe and, since #61 was merged, radix. redigo does not have support for automatic pipelining yet, and there is no issue for this as far as I see.

Ok, I got this and I'm sorry for this question as I didn't get to know redigo deeply.  I just saw redigo supports pipeline too in their repo. And thanks for your tremendous work for auto pipelining and thanks for your question.

**Comment by nussjustin** [comment]
> Yeah, I know prefilling the pool will benifit, but the default value of pool.MaxActive for redigo is zero, and in the cases of bench_test.goyou don't set pool.MaxActive and you only set pool.MaxIdle, so you don't prefill the pool for redigo actually in your case.

Yes, you're right. Wanna send a PR?

> So can you do some bench result under 32CPUs server? Seems like the performance decreases hugely for redigo with number of goroutine increasing.

Maybe this is something the redigo developers could do :-) I don't think there's anything wrong on our side. Our benchmark is quote simple and uses the redigo pool like one would do in a normal program (get a connection, execute some commands, put away the connection).

Also please note that the `BenchmarkParallelGetSet` benchmarks manually set the parallelism to `GOMAXPROCS * 8`. So if you have `GOMAXPROCS=8` the benchmarks will run with 64 goroutines. With `GOMAXPROCS=32` the benchmarks will run 256 concurrent goroutines.

This was done to get more meaningful results since in most cases you will have much more goroutines running and trying to access Redis than you will have CPU cores (or whatever you set `GOMAXPROCS` to). Also when using only `GOMAXPROCS` goroutines (e.g. 8 instead of 64) the difference between redigo, radix and redispipe becomes much smaller, since the amount of work is to small.

**Comment by shrimptttttttttt** [comment]
> Yes, you're right. Wanna send a PR?
OK, I will send a PR if all my bench tests are done.

> Also please note that the `BenchmarkParallelGetSet` benchmarks manually set the parallelism to `GOMAXPROCS * 8`. So if you have `GOMAXPROCS=8` the benchmarks will run with 64 goroutines. With `GOMAXPROCS=32` the benchmarks will run 256 concurrent goroutines.

actually, if parallelism is `GOMAXPROCS * 8`, the actually number of goroutine is `GOMAXPROCS * 8 * GOMAXPROCS`, as you can see the code in ```benchmark.go```

```Go
func (b *B) RunParallel(body func(*PB)) {
	...
	numProcs := b.parallelism * runtime.GOMAXPROCS(0)
	var wg sync.WaitGroup
	wg.Add(numProcs)
	for p := 0; p < numProcs; p++ {
		go func() {
			defer wg.Done()
			pb := &PB{
				globalN: &n,
				grain:   grain,
				bN:      uint64(b.N),
			}
			body(pb)
		}()
	}
	...
}
```

**Comment by shrimptttttttttt** [comment]
I write another bench test case as belows. 

```Go
func BenchmarkParallelGetSet(b *B) {
	parallel := runtime.GOMAXPROCS(0) * 8
	i := uint32(1)
	do := func(b *B, fn func(*rand.Rand)) {
		b.SetParallelism(parallel)
		b.RunParallel(func(pb *PB) {
			rng := rand.New(rand.NewSource(int64(atomic.AddUint32(&i, 1))))
			for pb.Next() {
				fn(rng)
			}
		})
	}

	b.Run("radix", func(b *B) {
		radix, err := Dial("tcp", "10.244.0.16:7061")
		if err != nil {
			b.Fatal(err)
		}
		defer radix.Close()
		if err != nil {
			b.Fatal(err)
		}
		b.ResetTimer()
		do(b, func(rng *rand.Rand) {
			key := "foo" + strconv.Itoa(rng.Intn(65536))
			if err := radix.Do(Cmd(nil, "SET", key, "value")); err != nil {
				b.Fatal(err)
			}
		})
	})

}
```

The error is 
```
goos: darwin
goarch: amd64
pkg: github.com/mediocregopher/radix/v3
FAIL: BenchmarkParallelGetSet/radix-8
    bench_test.go:261: short write
    bench_test.go:261: short write
    bench_test.go:261: short write
    bench_test.go:261: short write
    bench_test.go:261: unknown type prefix 'r'
    bench_test.go:261: EOF
    bench_test.go:261: read tcp xxxx:xxx->xxx:xxx: read: connection reset by peer
    bench_test.go:261: EOF
--- FAIL: BenchmarkParallelGetSet
```

Is it because radix client multi-thread safe? Seems like the sent cmd buffer is out of order.

**Comment by nussjustin** [comment]
The Client returned by `Dial` (a `radix.Conn`) is *not* thread-safe/concurrency-safe. You should use a Pool instead, which can be used concurrently.

**Comment by mediocregopher** [comment]
> actually, if parallelism is `GOMAXPROCS * 8`, the actually number of goroutine is `GOMAXPROCS * 8 * GOMAXPROCS`

Woah, that's news to me. This means the pool sizing isn't correct in the benchmarks then, right @nussjustin ?

**Comment by nussjustin** [comment]
> Woah, that's news to me. This means the pool sizing isn't correct in the benchmarks then, right @nussjustin ?

Seems so. Shouldn't really affect the benchmarks with automatic pipelining, but the non-pipelined benchmarks could be affected quite a bit. We should either reduce the parallelism (and instead tune this via GOMAXPROCS or the -cpus flag) or increase the pool size.

**Comment by shrimptttttttttt** [comment]
> > Woah, that's news to me. This means the pool sizing isn't correct in the benchmarks then, right @nussjustin ?
> 
> Seems so. Shouldn't really affect the benchmarks with automatic pipelining, but the non-pipelined benchmarks could be affected quite a bit. We should either reduce the parallelism (and instead tune this via GOMAXPROCS or the -cpus flag) or increase the pool size.

Yes, so maybe you guys can do some bench mark for fun. Check out whether ```cost time /op``` increases tremendously for redigo when ```GOMAXPROCS=32``` and goroutine num to ```32 * 32 * 8 = 8192```

I know it seems like should be explained by redigo, but if you have time  can you guys dig deeper a little bit?

**Comment by nussjustin** [comment]
PR #70 changes the parallelism/concurrency to be just GOMAXPROCS^2, so that with GOMAXPROCS=32 the benchmarks would "only" run 1024 concurrent goroutines.

I was planning on running the benchmarks on 2 VMs at some point (one for the client, probably 32 cores, and one for Redis) to get some more realistic numbers, but never got to it. Maybe I can find some time and motivation for this week :-)

**Comment by nussjustin** [comment]
Benchmark results running with `-cpu` 32 and 64 with 2 seperate VMs (32 dedicated vCPUs for the client, 2 dedicated vCPUs for the server):

```
name                                   time/op
ParallelGetSet/radix/default-32        2.15µs ± 0%
ParallelGetSet/radix/default-64        2.05µs ± 0%
ParallelGetSet/radix/no_pipelining-32  26.3µs ± 0%
ParallelGetSet/radix/no_pipelining-64  34.4µs ± 0%
ParallelGetSet/radix/one_pipeline-32   4.74µs ± 0%
ParallelGetSet/radix/one_pipeline-64   5.08µs ± 0%
ParallelGetSet/redigo-32               27.9µs ± 0%
ParallelGetSet/redigo-64               28.5µs ± 0%
ParallelGetSet/redispipe-32            2.02µs ± 0%
ParallelGetSet/redispipe-64            1.71µs ± 0%

name                                   alloc/op
ParallelGetSet/radix/default-32         72.0B ± 0%
ParallelGetSet/radix/default-64         84.0B ± 0%
ParallelGetSet/radix/no_pipelining-32    116B ± 0%
ParallelGetSet/radix/no_pipelining-64    119B ± 0%
ParallelGetSet/radix/one_pipeline-32    69.0B ± 0%
ParallelGetSet/radix/one_pipeline-64    69.0B ± 0%
ParallelGetSet/redigo-32                 119B ± 0%
ParallelGetSet/redigo-64                 120B ± 0%
ParallelGetSet/redispipe-32              168B ± 0%
ParallelGetSet/redispipe-64              172B ± 0%

name                                   allocs/op
ParallelGetSet/radix/default-32          4.00 ± 0%
ParallelGetSet/radix/default-64          4.00 ± 0%
ParallelGetSet/radix/no_pipelining-32    6.00 ± 0%
ParallelGetSet/radix/no_pipelining-64    6.00 ± 0%
ParallelGetSet/radix/one_pipeline-32     4.00 ± 0%
ParallelGetSet/radix/one_pipeline-64     4.00 ± 0%
ParallelGetSet/redigo-32                 6.00 ± 0%
ParallelGetSet/redigo-64                 6.00 ± 0%
ParallelGetSet/redispipe-32              8.00 ± 0%
ParallelGetSet/redispipe-64              8.00 ± 0%
```

Results are as expected and don't really differ from what I see when testing with only 4 / 8 cores.

`redis-cli --latency`

```
min: 0, max: 7, avg: 0.69 (2029 samples)
```

`redis-cli --intrinsic-latency 100`

```
Max latency so far: 1 microseconds.
Max latency so far: 4 microseconds.
Max latency so far: 11 microseconds.
Max latency so far: 16 microseconds.
Max latency so far: 17 microseconds.
Max latency so far: 25 microseconds.
Max latency so far: 26 microseconds.
Max latency so far: 69 microseconds.
```

**Comment by mediocregopher** [comment]
@nussjustin you're the best 🙏 I'll update the numbers on the README and make sure it includes a description of the setup.

**Comment by mediocregopher** [comment]
Actually I suppose I should wait for the results after #71 , if you were planning on re-running after that.

**Comment by nussjustin** [comment]
Nearly forgot to mention: While testing I had a few problems with sockets getting closed (still haven't found out why). Sometimes everything worked and I could open the 4096 connections and sometimes most sockets would just get closed immediately, but the errors from filling the pool are currently ignored. Maybe we should report them somehow? We could add a `ErrCh` similar to `Cluster` and `Pool`. 

Any other suggestions?

**Comment by mediocregopher** [comment]
I've had issues with the redis-server not liking it when you open lots of connections simultaneously in the passed, but I also thought that in redis v5 that got improved. Maybe not enough. 4096 _is_ a lot of connections to open simultaneously tho, even for high-load cases I've generally made do with less than a 1000.

> Maybe we should report them somehow? We could add a `ErrCh` similar to `Cluster` and `Pool`.

Yeah there's a TODO in there to do that, I just never got around to it. I'll do that now real quick.

**Comment by mediocregopher** [comment]
I went ahead and updated the README's benchmark section with justin's latest results that he posted above. @shrimptttttttttt I'm gonna go ahead and close this, if you still have any questions please feel free to reopen it though.
