### ISSUE TITLE
Deadlocks on pubsub.close and/or pubsub.unsubscribe

### ISSUE THREAD

**Issue by renevall** [mediocregopher/radix#73]
Hey, we are experiencing some deadlocks with close() and unsubscribe(). We currently running a setup where we use websockets and rooms. Sometimes we need to close/tear down the room, and that triggers a method on the rooms that calls for the unsubscribing. 

Now, subscribe on my structure is a method that receives an output channel of "messages" structure and a done channel. It runs in it's own routine and starts an endless for loop. The endless loop is the one reading from the pubsub subscribe channel, then transforms the []byte into messages and it is sent to output channel.

When the cancel signal comes, done channel receives a value and I called the unsubscribe method. 3/4 of the time, the unsubscribe would just block waiting for the mutex of the connection to be freed. It never happens. And I have no idea or control on who has the lock and why it is stuck. 

I have a defer code that tells me when the routine ends, again 3/4 of the times it doesn't and I can still ping point it to the unsubscribe.

Now, I originally tried one "global connection" approach thinking that I was going to be able use "channels" to multiplex the connect. Every new subscribe goes to a different channel. Now the deadlock was bringing the server down because all redis conn just stop working. 

So I went ahead and now I create one conn per subscription, that avoid all the system getting freezes. And I stopped unsubscribing altogether and now I just close the conn. Upon logs inspection, I can see the close hanging just like unsubscribe was.

**Comment by mediocregopher** [comment]
Hi @renevall, I'll try to take a deeper look into this in the morning, but
can you tell me now if you're using the normal PubSubConn or the persistent
one? That'll help me narrow down the problem. Thanks!

**Comment by renevall** [comment]
@mediocregopher sure, I'm using persistent pubsub.

Another clue on this is the following:

Originally when the teardown process started I would post a msg to the same redis room announcing the tear down. But that msg was looping back to the channel that for a fraction of a second had a subscription still. That created a deadlock too. So what I do now is, close the subscription first, and the just post the message. 

That leads me to believe the deadlock happens between reading/subscribe and the other too, as if reading is waiting to read something in order to free the lock. But anyway, let me know and I can make a video to show the issue live.

**Comment by mediocregopher** [comment]
I found the deadlock which you encountered in the first iteration of your code, when you were calling Unsubscribe, and fixed that. It's tagged as `v3.2.3` I'm not sure what you were encountering when you were using Close, but it's possible that the code got blocked if you had stopped reading from your message channels before Close had returned. It's not obvious in the docs that you had to do this, so I added notes to Unsubscribe/PUnsubscribe/Close mentioning this. The channels must be read until the methods have returned, or the internal go-routine might be blocked writing to them while Close is waiting for its turn.

I'll be honest and say that the pubsub code is a bit of a mess, and I wouldn't be surprised if there were still some weird issues lurking in there, so please don't be afraid to reopen this or make a new issue if you see something strange.
