### ISSUE TITLE
radix v3 illegally uses internal package

### ISSUE THREAD

**Issue by blazingkin** [mediocregopher/radix#77]
`go get github.com/mediocregopher/radix.v3`

Returns

```
go/src/github.com/mediocregopher/radix.v3/stream.go:13:2: use of internal package github.com/mediocregopher/radix/internal/bytesutil not allowed
```

**Comment by blazingkin** [comment]
`go version` is `go version go1.11.1 darwin/amd64`
Although this is also failing on the `golang:1.10.3` docker image

**Comment by mediocregopher** [comment]
Hi Alex! Please note that the packages name was changed a while ago, it's
now just radix. So try `go get github.com/mediocregopher/radix/v3` (or try
without the `v3` if your go version is really old and not module aware).

**Comment by blazingkin** [comment]
Thanks!
