### ISSUE TITLE
Does radix support go 1.9.3?

### ISSUE THREAD

**Issue by shrimptttttttttt** [mediocregopher/radix#78]
Hi，I see you docs mentioned

> This project's name was recently changed from radix.v3 to radix, to account for go's new module system. As long as you are using the latest update of your major go version (1.9.7+, 1.10.3+, 1.11+) the module-aware go get should work correctly with the new import 

I' was wondering does radix support go 1.9.3? Except for change ```import path```, is there any other incompatibility problems?

**Comment by mediocregopher** [comment]
Hey @shrimptttttttttt , the problem with using `1.9.3` is that radix uses some internal packages, such as `github.com/mediocregopher/radix/v3/resp`. The `v3` part of that is part of the module system and not a real directory. So even if you change the import paths in _your_ code the import paths within radix would still not make sense to the compiler, unless the compiler is 1.9.7+ and understands modules.

**Comment by shrimptttttttttt** [comment]
> Hey @shrimptttttttttt , the problem with using `1.9.3` is that radix uses some internal packages, such as `github.com/mediocregopher/radix/v3/resp`. The `v3` part of that is part of the module system and not a real directory. So even if you change the import paths in _your_ code the import paths within radix would still not make sense to the compiler, unless the compiler is 1.9.7+ and understands modules.

Yeah, I know, I try to import github radix to my repo, this will fix the import path probelm. But I am wondering is there any other incompatibility problems?

**Comment by mediocregopher** [comment]
I attempted to run tests on radix using 1.9.7 and they would not work, due to using a newer function from the `rand` package. But I did manage to get a basic program with 1.9.7, so I would tentatively say yes, you can use 1.9.7 and radix together.

Note that this package only aims to support the most recent two go versions (atm that's 1.12 and 1.11), so it's possible that 1.9 won't be supported in the future, and your best bet is to try to stay up-to-date with your go versions.

1.9.3 will not work at all.

**Comment by shrimptttttttttt** [comment]
> I attempted to run tests on radix using 1.9.7 and they would not work, due to using a newer function from the `rand` package. But I did manage to get a basic program with 1.9.7, so I would tentatively say yes, you can use 1.9.7 and radix together.
> 
> Note that this package only aims to support the most recent two go versions (atm that's 1.12 and 1.11), so it's possible that 1.9 won't be supported in the future, and your best bet is to try to stay up-to-date with your go versions.
> 
> 1.9.3 will not work at all.

Can you point out where 1.9.3 can not work? I fork radix to my own repo, and change import path, and it works fine. Anything I missing?

**Comment by shrimptttttttttt** [comment]
I mean the main process, I saw you use rand interfaces of higher go version. But will the main process works fine?

**Comment by mediocregopher** [comment]
> Can you point out where 1.9.3 can not work? I fork radix to my own repo, and change import path, and it works fine. Anything I missing?

Ooooh I hadn't realized you meant you'd forked radix, then yes that will work fine.

**Comment by shrimptttttttttt** [comment]
> > Can you point out where 1.9.3 can not work? I fork radix to my own repo, and change import path, and it works fine. Anything I missing?
> 
> Ooooh I hadn't realized you meant you'd forked radix, then yes that will work fine.

Ok, thanks very much!
