### ISSUE TITLE
how to mset by cmd or flatcmd?

### ISSUE THREAD

**Issue by harrybi** [mediocregopher/radix#79]

**Comment by mediocregopher** [comment]
Hi @harrybi, you can do an mset just like any other command:

```go
err := client.Do(radix.Cmd(nil, "MSET", "key1", "val1", "key2", "val2"))
```

you could also pass in a map using a FlatCmd:

```go
err := client.Do(radix.FlatCmd(nil, "MSET", map[string]string{
    "key1": "val1",
    "key2": "val2",
})
```

you could _also_ pass a struct into FlatCmd:

```go
type Struct struct {
    Key1 string `redis:"key1"`
    Key2 string `redis:"key2"`
}

err := client.Do(radix.FlatCmd(nil, "MSET", Struct{
    Key1: "val1",
    Key2: "val2",
})
```

Hope this helps!

**Comment by mediocregopher** [comment]
Also note that FlatCmd is very forgiving with types, so you don't have to use `string`. You could use `int` or `float64` or `[]byte` or nearly any other primitive type.

**Comment by harrybi** [comment]
my mset args type:
map[string]interface{}{"k1":1, "k2":[]byte, "k3":string}

**Comment by mediocregopher** [comment]
Ah, you're right. This is what I get for answering questions so late at night. `FlatCmd` only supports commands with only one key argument at the front, like `HMSET` and `ZADD`. `MSET` is not supported, you'll have to use a normal `Cmd` for that. Sorry for the confusion!

**Comment by mediocregopher** [comment]
Gonna go ahead and close this, feel free to reopen it if you have any other questions!
