### ISSUE TITLE
how to get conn.RemoteAddr

### ISSUE THREAD

**Issue by xuecai** [mediocregopher/radix#84]
i use pool in my project.
i see where is a public api for ioErrConn like Do, but there is private api for pool.get and pool.put.
i want to use ioErrConn.(net.Conn).RemoteAddr().
may pool.get  be a public api ?

**Comment by mediocregopher** [comment]
Hi @xuecai, would the WithConn action work for you? It let's you get access to a Conn from a Client (like a Pool), and from there you can call NetConn on the Conn and then RemoteAddr on that.

**Comment by xuecai** [comment]
i got it, thank you!

**Comment by xuecai** [comment]
i use Do(WithConn) and it cost 3 alloc/op more than Do(Cmd).
maybe add a sync.Pool for performance?

**Comment by mediocregopher** [comment]
Judging from the code I wouldn't expect there to be any extra allocations from using WithConn specifically, it's possible they're coming from the closure you're passing into it, depending on what you're doing. I can take a closer look in the next week or so.

**Comment by nussjustin** [comment]
Let's try it. Code:

```go
package main

import (
	"net"
	"testing"

	radix "github.com/mediocregopher/radix/v3"
)

var addr net.Addr

func BenchmarkRemoteAddr(b *testing.B) {
	client, err := radix.Dial("tcp", "127.0.0.1:6379")
	if err != nil {
		b.Fatal(err)
	}
	defer client.Close()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if err := client.Do(radix.WithConn("", func(conn radix.Conn) error {
			addr = conn.NetConn().RemoteAddr()
			return nil
		})); err != nil {
			b.Fatal(err)
		}
	}
}
```

Benchmark result:

```bash
$ go test -bench . -benchmem -memprofile mem.pprof
goos: linux
goarch: amd64
pkg: conn
BenchmarkRemoteAddr-8   	20000000	        99.0 ns/op	      48 B/op	       2 allocs/op
PASS
ok  	conn	2.094s
```

Profile:

```bash
$ go tool pprof -alloc_objects -top mem.pprof     
File: conn.test
Type: alloc_objects
Time: Mar 20, 2019 at 3:58pm (CET)
Showing nodes accounting for 42845145, 100% of 42845145 total
      flat  flat%   sum%        cum   cum%
  21775000 50.82% 50.82%   21775000 50.82%  github.com/mediocregopher/radix/v3.WithConn
  21070145 49.18%   100%   21070145 49.18%  github.com/mediocregopher/radix/v3.(*connWrap).NetConn
         0     0%   100%   42845145   100%  conn.BenchmarkRemoteAddr
         0     0%   100%   21070145 49.18%  conn.BenchmarkRemoteAddr.func1
         0     0%   100%   21070145 49.18%  github.com/mediocregopher/radix/v3.(*connWrap).Do
         0     0%   100%   21070145 49.18%  github.com/mediocregopher/radix/v3.(*withConn).Run
         0     0%   100%   42845145   100%  testing.(*B).launch
         0     0%   100%   42845145   100%  testing.(*B).runN
```

```bash
$ go tool pprof -alloc_objects -list=WithConn mem.pprof 
Total: 42845145
ROUTINE ======================== github.com/mediocregopher/radix/v3.WithConn in /home/justinn/.gopath/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/action.go
  21775000   21775000 (flat, cum) 50.82% of Total
         .          .    501://
         .          .    502:// NOTE that WithConn only ensures all inner Actions are performed on the same
         .          .    503:// Conn, it doesn't make them transactional. Use MULTI/WATCH/EXEC within a
         .          .    504:// WithConn for transactions, or use EvalScript
         .          .    505:func WithConn(key string, fn func(Conn) error) Action {
  21775000   21775000    506:	return &withConn{[1]string{key}, fn}
         .          .    507:}
         .          .    508:
         .          .    509:func (wc *withConn) Keys() []string {
         .          .    510:	return wc.key[:]
         .          .    511:}
```

```bash
$ go tool pprof -alloc_objects -list=NetConn mem.pprof  
Total: 42845145
ROUTINE ======================== github.com/mediocregopher/radix/v3.(*connWrap).NetConn in /home/justinn/.gopath/pkg/mod/github.com/mediocregopher/radix/v3@v3.2.3/radix.go
  21070145   21070145 (flat, cum) 49.18% of Total
         .          .    244:func (cw *connWrap) Decode(u resp.Unmarshaler) error {
         .          .    245:	return u.UnmarshalRESP(cw.brw.Reader)
         .          .    246:}
         .          .    247:
         .          .    248:func (cw *connWrap) NetConn() net.Conn {
  21070145   21070145    249:	return connLimited{cw.Conn}
         .          .    250:}
         .          .    251:
         .          .    252:// ConnFunc is a function which returns an initialized, ready-to-be-used Conn.
         .          .    253:// Functions like NewPool or NewCluster take in a ConnFunc in order to allow for
         .          .    254:// things like calls to AUTH on each new connection, setting timeouts, custom
```

![Screenshot from 2019-03-20 16-00-46](https://user-images.githubusercontent.com/6443781/54694942-60b92700-4b29-11e9-9533-6ce41fe0519c.png)

So yeah, both `radix.WithConn` and `(Conn).NetConn` allocate memory. I expected the first but not the second one.

**Comment by nussjustin** [comment]
The allocation in `NetConn` comes from wrapping the `net.Conn` to avoid calls to `Read`, `Write` and `Close` which should not be called as documented on `radix.Conn`. Is this really necessary? Since it's already documented, wrapping the conn just for this seems unnecessary. I don't think we go to such great lengths at other points in the code (e.g. we don't try to prevent a single "WATCH" on a pool, although it indicates a bug in basically 100% of all cases).

The allocation in `WithConn` is necessary, but could easily be avoided with a `sync.Pool` if we forbid calling `Run` twice (tbh, I don't like that idea. Calling a `WithConn`-`Action` twice seems rather likely for some cases, e.g. when using Sentinel).

**Comment by mediocregopher** [comment]
Yeah I'm ok with getting rid of the wrapper around `net.Conn`, I wasn't thinking about performance when I wrote that lol. But yeah I'd also be hesitant to disallow reusing WithConn to save an allocation.

**Comment by nussjustin** [comment]
Sent #85, which removes one allocation bringing us done to the one allocation for `WithConn`.

Since we can't avoid the allocation inside `WithConn`, removing the last allocation would require just not using `WithConn` at all either by us adding a new method to `Pool` that returns one of the `net.Addr`s or the user implementing a custom `Action` which does the same as `WithConn` but which can be reused. I don't think we should change anything on the radix side and instead let users implement their own `Action` in case they care about this one allocation.

**Comment by xuecai** [comment]
thanks .
I will write a custom action in my project .
