### ISSUE TITLE
Cannot rogrammatically perform MGET query.

### ISSUE THREAD

**Issue by Vistian** [mediocregopher/radix#87]
There doesn't seem to be a way to perform an MGET query where I have a variable number of keys that need looking up.  Calls to radix.Cmd and radix.FlatCmd have a set number of arguments and I can't pass a slice of keys to either.  Is this correct and is there a way around this?  Thanks.

**Comment by mediocregopher** [comment]
Hi @Vistian , here's the function signature for `Cmd`:

```go
func Cmd(rcv interface{}, cmd string, args ...string) CmdAction
```

the `...string` indicates a variadic type, so `args` can be zero or more strings. So to do an MGET you would do:

```go
var []vals string
err := client.Do(radix.Cmd(&vals, "MGET", "key1", "key2", "key3"))
```

or, if you have a slice of strings in a variable already, you can do:

```go
keys := []string{"key1", "key2", "key3"}
var []vals string
err := client.Do(radix.Cmd(&vals, "MGET", keys...)
```

Hope that helps!

**Comment by Vistian** [comment]
That does help.  Thank you very much for your help and for providing this client!

**Comment by mediocregopher** [comment]
Np! I'm glad you're finding it useful :)
