### ISSUE TITLE
Questions about Sync() in Cluster

### ISSUE THREAD

**Issue by kimtree** [mediocregopher/radix#93]
Hi, I got more questions while I'm benchmarking your library.

I was trying to get a count for calling Sync() function while running a huge amount of insertion command. This investigation helps me to know how much time needed for cluster changing and how does this affect overall performance.
For more detail, I modified the like below
``` cluster.go
type Cluster struct {
        ~ blah blah ~
        CounterSync uint32 // This is what I added to get a count
}
func (c *Cluster) Sync() error {
        atomic.AddUint32(&c.CounterSync, 1) // This is what I added to get a count
        p, err := c.pool("")
        if err != nil {
                return err
        }
        c.syncDedupe.do(func() {
                err = c.sync(p)
        })
        return err
}
```
And also, I added some sort of lines for measure time like below
```
func (c *Cluster) sync(p Client) error {
        start := time.Now()

        ~  blah blah ~

        fmt.Printf("\n%d", time.Since(start).Nanoseconds())
        return nil
}
```
And this is my benchmark code (40 goroutines)
```
func BenchmarkTestQPS(b *testing.B) {
	b.Run("zincrby", func(b *testing.B) {
		client := radixClusterWithAuthPass(20) // This function will return Cluster which has 20 connections in each pool

		b.ResetTimer()
		b.RunParallel(func(pb *testing.PB) {
			for pb.Next() {
				client.Do(radix.Cmd(nil, "ZINCRBY", "test_key", "1", "test_data"))
			}
		})
		b.StopTimer()
                 fmt.Println("Value Of CounterSync:  ", client.CounterSync)
	})
}
```
And the result seemed like this
```
2883036
592498
605760
586586
756704
661927
535979
506501
580632
Value Of CounterSync:  3
```
This seems that sync() function called 9 times while the counter shows only 3. Do you have any idea what's happening here?

**Comment by mediocregopher** [comment]
Hi @kimtree! That really is odd, I can't imagine why that would be happening. I tried to replicate your results and was not able to. I more or less made the same changes you did, you can see my diff 
[here](https://github.com/mediocregopher/radix/files/3117690/qps.diff.txt), and this is the output I get:

```
>>> go test -v -run=xxx -bench=QPS .       
sync took: 8.897832ms                                              
Value Of CounterSync:   1                                 
goos: linux                                                  
goarch: arm64                                                             
pkg: github.com/mediocregopher/radix/v3                                           
BenchmarkTestQPS/zincrby-4              sync took: 8.732518ms             
Value Of CounterSync:   1                                                         
sync took: 16.892442ms                                             
Value Of CounterSync:   1                                          
sync took: 8.669641ms                                        
Value Of CounterSync:   1                                    
   50000             20217 ns/op                                          
PASS                                                         
ok      github.com/mediocregopher/radix/v3      1.432s
```

I'm not 100% on how benchmarks work but it seems to be running the full benchmark multiple times. I also didn't use an actual cluster (which I think you might be), but the client code shouldn't change its behavior due to that.

A couple of questions for you:

- Can you give me a full diff and the exact `go test` command you're using to get that output? That way I can see if there's anything else that might be happening.

- You mentioned you're doing tests on performance during failover, were you performing a cluster change while running this? That shouldn't cause this behavior but it would help narrow down the cause at least.

**Comment by kimtree** [comment]
Hi @mediocregopher, Thanks for the quick reply!
I found the reason why my benchmark result was wrong that's because I didn't use `defer client.Close()` for my benchmark. It seems like the previous Cluster didn't close at that time and then I created new Cluster for the tests and It printed `sync took: xxx ms` several times.
Benchmarking in Go runs several rounds with b.N counts, and also Cluster created as the same count as benchmark rounds! And the result was reasonable for this theory.

```
run  1
sync took: 3.660978ms <-- First Sync() while creating cluster
round total: 0 benchmark total: 0
Value Of CounterSync:  1
close

run  100
sync took: 8.531856ms <-- First Sync() while creating cluster
round total: 0 benchmark total: 0
Value Of CounterSync:  1
close

run  10000
sync took: 2.583651ms <-- First Sync() while creating cluster
round total: 0 benchmark total: 0
Value Of CounterSync:  1
close

run  1000000
sync took: 2.864352ms <-- First Sync() while creating cluster

sync took: 626.678µs <-- Previous 3 + current 1 clusters' Sync() by ClusterSyncEvery option
sync took: 587.329µs
sync took: 590.229µs
sync took: 608.601µs

sync took: 619.82µs <-- Previous 3 + current 1 clusters' Sync() by ClusterSyncEvery option
sync took: 583.708µs
sync took: 647.244µs
sync took: 588.398µs
round total: 11 benchmark total: 11
Value Of CounterSync:  3
close

run  2000000
sync took: 10.197806ms <-- First Sync() while creating cluster

sync took: 665.783µs <-- Previous 4 + current 1 clusters' Sync() by ClusterSyncEvery option
sync took: 661.464µs
sync took: 630.861µs
sync took: 618.034µs
sync took: 656.25µs

sync took: 600.851µs <-- Previous 4 + current 1 clusters' Sync() by ClusterSyncEvery option
sync took: 600.583µs
sync took: 677.997µs
sync took: 681.03µs
sync took: 611.132µs

sync took: 576.997µs <-- Previous 4 + current 1 clusters' Sync() by ClusterSyncEvery option
sync took: 542.971µs
sync took: 642.52µs
sync took: 709.56µs
sync took: 654.432µs

sync took: 608.615µs <-- Previous 4 + current 1 clusters' Sync() by ClusterSyncEvery option
sync took: 636.182µs
sync took: 601.149µs
sync took: 598.038µs
sync took: 692.8µs

sync took: 627.43µs <-- Previous 4 clusters' Sync() by ClusterSyncEvery option
sync took: 686.405µs
sync took: 559.461µs
sync took: 660.681µs
<-- Current cluster 1 is not reached to 25 seconds, so didn't sync at this time
round total: 24 benchmark total: 36
Value Of CounterSync:  5
close
```

Additionally, I'm planning to add measurement variables for monitoring performance and the status of handling Redis requests for our actual product. How do you think about adding measurement variables like the way I wrote for this benchmark (like CounterSync), and give it to the user optionally with Cluster/PoolOpts? I will prepare the PR if you don't mind for adding measurements.

**Comment by mediocregopher** [comment]
> How do you think about adding measurement variables like the way I wrote for this benchmark (like CounterSync), and give it to the user optionally with Cluster/PoolOpts? I will prepare the PR if you don't mind for adding measurements.

This is definitely something I've been thinking about how best to do, but I'd like to wait until more information about the [RESP3 protocol](https://gist.github.com/antirez/2bc68a9e9e45395e297d288453d5d54c) comes out, as it has built into it an [attribute type](https://gist.github.com/antirez/2bc68a9e9e45395e297d288453d5d54c#attribute-type) which would get potentially return information that would be returned from the Client along with other measurements likes number of syncs and so on. So I think we should hold off for now, thank you though!

**Comment by kimtree** [comment]
IMHO, It seems the RESP3 is premature to consider right now. (refer: http://antirez.com/news/126)
What I'm trying to do is investigating the measurements from the client side first because we already have a DevOps team who has responsibility for the Redis server itself. So, we need to store the data like how many connections are made, how many times "MOVED" response returned, how many new connections are made when the pool is full, how many errors occur when establishing the connection, etc. We're planning to use your library on a production level within one or two months with the measurement data we need. So, I'll try to send PR for the details ASAP and we can discuss more. Thanks!

**Comment by nussjustin** [comment]
@kimtree sounds good. never really got around to propose or even implement something, since I'm not currently using radix in any important production systems, but I agree that we need a way to get this kind of information.

**Comment by mediocregopher** [comment]
I also agree that metrics/attributes would be great, and I have an idea about how they could be implemented in a forwards compatible manner. A `Client` could optionally implement an interface like this:

```
type ClientAttributed interface {
    Client
    // Attributes returns a copy of all available attributes
    Attributes map[string]interface{}
    // Attribute returns the current value of a particular attribute
    Attribute(string) interface {}
}
```

(I'm using the words "metrics" and "attributes" interchangeably here, so it doesn't get confusing down the road when this same functionality gets used for RESP3 attributes)

This would be implemented by each Client (Conn, Pool, Sentinel, Cluster) with appropriate attributes, such as number of commands, number of syncs, time of last sync, last failed instance address, etc...

That way we don't have to define a ton of fields on each client, we allow people to still be able to wrap the built-in clients with their own while not obfuscating attribute data, and attributes are programmatically iterable.

@nussjustin @kimtree what do you think?

**Comment by mediocregopher** [comment]
Another thing, that interface would potentially allow for nested attributes (if such a thing is desired), e.g. a cluster could have an attribute for each instance, `instance-ADDR-attrs`, the value of which is the `Attributes()` return from the client for that instance.

**Comment by nussjustin** [comment]
@mediocregopher I don't like using untyped values for everything. They are cumbersome to use, especially when you now what you want to access (which I guess will be most cases) and don't need everything. Also you can't know all the possible values without looking at the code or calling the function and looking at the output.

With structs users know exactly what is available and we can still always add fields without breaking anything. For connections in a Pool/Cluster/Sentinel and RESP3 attributes we could still have maps where needed, but they could just be part of a struct or have structs as values.

Another idea I had in mind was something like the `[httptrace.ClientTrace](https://golang.org/pkg/net/http/httptrace/#ClientTrace)` from the stdlib, which is just a struct full of optional callbacks which are called at specific times when not nil. This way users could collect the information they need themselves and could even do it more efficient (although the difference would probably be negligible for 99.999% of users). This could also be used with RESP3 attributes, but I still haven't really given this much thought right now.

**Comment by kimtree** [comment]
Oh, I thought so simple that I just trying to add some variables I need in the Cluster struct for the first time. @mediocregopher 's idea sounds suitable, but I also prefer to use strict type for the variables that in line with the Golang's philosophy.

And, I agree with the idea @nussjustin mentioned. Using a hook is more human readable, and people can manipulate the information they need at the point. Also, I like to use the way that stdlib implements personally.

**Comment by mediocregopher** [comment]
I agree strong typing would be nicer, but it also adds a lot of overhead in terms of maintenance, both for us and for users. And it really explodes the size of the api.

The use-case I have in my head for this is someone exporting this data to a tool like Prometheus or statsd, where it'll be collected and graphed out. For that case an untyped map would be a lot less work to set up than anything typed, and would be able to gain any further keys we add without the user having to go in and manually add cases for the new fields.

For the API explosion problem, it might make sense to put all the new types in a sub-package. But that still leaves the manual labor problem.

What are the use-cases you see for this? Timeseries metrics are pretty much all I've ever wanted this kind of data for, so I'm curious what others are thinking for it.

**Comment by kimtree** [comment]
That makes sense. We're also using Prometheus for monitoring and I agree that we need to consider  API explosion problem.

What we're trying to measure is for detecting our REDIS server outage rapidly. The measurements we've considered is in what I mentioned before.

> how many connections are made, how many times "MOVED" response returned, how many new connections are made when the pool is full, how many errors occur when establishing the connection, etc

I guess we need to store metrics for both Cluster and each pool(by hostname). AFAIK, I can't access a Pool directly from the Cluster since Cluster only hold Pool connection itself, not a Pool struct. So, we need to implement for accessing each pool's metric values from the Cluster struct as well.

**Comment by nussjustin** [comment]
I agree with the explosion of the API surface, but given that we could hide most of this in a sub-package I don't think it's too much of a problem, although it may be a lot to maintain. On the other hand having an untyped map full of different values also requires too be carefull not to break something and we would still need to think about how to structure the data inside the map. A format that makes sense for e.g. Prometheus may be a bad fit for some other tool.

Also not everyone just dumps everything out to Prometheus (or something similiar) and even with a tool like this depending on the metric you may even want to do calculations inside the application itself (e.g. a Prometheus "summary").

I also can not think about a good way to represent per node / pool metrics in e.g. a Cluster that way. Do you separate the per node metrics from the metrics of the Cluster itself or do you put it all into one map? And if you put it all into one map, do you use sub-maps? What about (possible) per Conn/Client metrics? How would you structure all this so that it could easily be exported for e.g. Prometheus without manually accessing and asserting values from the map(s)? 

Maybe we should think more about what metrics we actually want to expose (at least initially) and think about how this could be structured. @kimtree listed a few metrics already, but there are much more thinks we could track (and we haven't touched Sentinel or standalone Client/Conn metrics yet)

**Comment by mediocregopher** [comment]
Seeing the code in #99 made me a lot more comfortable with the idea of doing traces. If I _really_ want to do something with untyped maps later I can base it off of the traces and hide that away in the trace package. And you're right @nussjustin, there's a lot of warts in the idea that would need to be worked out.

As far as metrics to expose and structure, I discussed the structure I'm thinking of a bit in #99, [here](https://github.com/mediocregopher/radix/pull/99#pullrequestreview-240293171). Here's some metrics I'm thinking about for Pool, broken down by Client/metric/reported fields.

```
(all metrics have Address for when tracing is used with Sentinel/Cluster)
- Pool
    - Connection created
        - Address
        - Reason (initialization, pool empty, refiller)
        - Time to connect (or fail)
        - Connection error, if there is one
        - Pool size
        - Buffer size
    - Connection buffered
        - Address
        - Buffer size
    - Connection closed
        - Address
        - Reason (Close called, pool+buffer full, buffer drained)
        - Pool size
        - Buffer size
        - Close error, if there is one
```

One thing that occured to me when writing that is that writing tests for the traces is going to be a pain, but they're going to make other tests easier more than likely.

**Comment by kimtree** [comment]
Thank you guys for discussing with me about the issues above. I think we can close this issue for now. Thanks again!
